;;; Compiled by f2cl version 2.0 beta Date: 2006/05/05 20:28:21 
;;; Using Lisp CLISP 2.38 (2006-01-24) (built on guru.build.karan.org)
;;; Options: ((:prune-labels nil) (:auto-save t) (:relaxed-array-decls t)
;;;  (:coerce-assigns :as-needed) (:array-type ':array) (:array-slicing t)
;;;  (:declare-common nil) (:float-format single-float))

(in-package :common-lisp-user)


(|COMMON-LISP|::|LET*|
 ((|FORTRAN-TO-LISP|::|CON| #1=1.28d0) (|FORTRAN-TO-LISP|::|HALF| #2=0.5d0)
  (|FORTRAN-TO-LISP|::|LTONE| #3=5.0d0) (|FORTRAN-TO-LISP|::|ONE| #4=1.0d0)
  (|FORTRAN-TO-LISP|::|UTZERO| #5=12.5d0) (|FORTRAN-TO-LISP|::|ZERO| #6=0.0d0))
 (|COMMON-LISP|::|DECLARE|
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #1# #1#)
   |FORTRAN-TO-LISP|::|CON|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #2# #2#)
   |FORTRAN-TO-LISP|::|HALF|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #3# #3#)
   |FORTRAN-TO-LISP|::|LTONE|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #4# #4#)
   |FORTRAN-TO-LISP|::|ONE|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #5# #5#)
   |FORTRAN-TO-LISP|::|UTZERO|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #6# #6#)
   |FORTRAN-TO-LISP|::|ZERO|))
 (|COMMON-LISP|::|DEFUN| |FORTRAN-TO-LISP|::|ALNORM|
  (|FORTRAN-TO-LISP|::|X| |FORTRAN-TO-LISP|::|UPPER|)
  (|COMMON-LISP|::|DECLARE|
   (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
    |FORTRAN-TO-LISP|::|X|)
   (|COMMON-LISP|::|TYPE| |F2CL-LIB|::|LOGICAL| |FORTRAN-TO-LISP|::|UPPER|))
  (|COMMON-LISP|::|PROG|
   ((|FORTRAN-TO-LISP|::|Y| #6#) (|FORTRAN-TO-LISP|::|Z| #6#)
    (|FORTRAN-TO-LISP|::|UP| |COMMON-LISP|::|NIL|)
    (|FORTRAN-TO-LISP|::|ALNORM| #6#))
   (|COMMON-LISP|::|DECLARE|
    (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
     |FORTRAN-TO-LISP|::|ALNORM| |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|Y|)
    (|COMMON-LISP|::|TYPE| |F2CL-LIB|::|LOGICAL| |FORTRAN-TO-LISP|::|UP|))
   (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UP| |FORTRAN-TO-LISP|::|UPPER|)
   (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|X|)
   (|COMMON-LISP|::|IF|
    (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|ZERO|)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL10|))
   (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UP|
    (|COMMON-LISP|::|NOT| |FORTRAN-TO-LISP|::|UP|))
   (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|Z|
    (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|Z|))
   |FORTRAN-TO-LISP|::|LABEL10|
   (|COMMON-LISP|::|IF|
    (|COMMON-LISP|::|OR|
     (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|LTONE|)
     (|COMMON-LISP|::|AND| |FORTRAN-TO-LISP|::|UP|
      (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|Z|
       |FORTRAN-TO-LISP|::|UTZERO|)))
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL20|))
   (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALNORM|
    |FORTRAN-TO-LISP|::|ZERO|)
   (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL40|)
   |FORTRAN-TO-LISP|::|LABEL20|
   (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|Y|
    (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF| |FORTRAN-TO-LISP|::|Z|
     |FORTRAN-TO-LISP|::|Z|))
   (|COMMON-LISP|::|IF|
    (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|CON|)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL30|))
   (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALNORM|
    (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|HALF|
     (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|Z|
      (|COMMON-LISP|::|+| 0.398942280444d0
       (|COMMON-LISP|::|/|
        (|COMMON-LISP|::|*| -0.399903438504d0 |FORTRAN-TO-LISP|::|Y|)
        (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|Y| 5.75885480458d0
         (|COMMON-LISP|::|/| -29.8213557808d0
          (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|Y| 2.62433121679d0
           (|COMMON-LISP|::|/| 48.6959930692d0
            (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|Y|
             5.92885724438d0))))))))))
   (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL40|)
   |FORTRAN-TO-LISP|::|LABEL30|
   (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALNORM|
    (|COMMON-LISP|::|/|
     (|COMMON-LISP|::|*| 0.398942280385d0
      (|COMMON-LISP|::|EXP| (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|Y|)))
     (|COMMON-LISP|::|+| (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|Z| 3.8052d-8)
      (|COMMON-LISP|::|/| 1.00000615302d0
       (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|Z| 3.98064794d-4
        (|COMMON-LISP|::|/| 1.98615381364d0
         (|COMMON-LISP|::|+|
          (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|Z| 0.151679116635d0)
          (|COMMON-LISP|::|/| 5.29330324926d0
           (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|Z| 4.8385912808d0
            (|COMMON-LISP|::|/| -15.1508972451d0
             (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|Z| 0.742380924027d0
              (|COMMON-LISP|::|/| 30.789933034d0
               (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|Z|
                3.99019417011d0)))))))))))))
   |FORTRAN-TO-LISP|::|LABEL40|
   (|COMMON-LISP|::|IF| (|COMMON-LISP|::|NOT| |FORTRAN-TO-LISP|::|UP|)
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALNORM|
     (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|ONE|
      |FORTRAN-TO-LISP|::|ALNORM|)))
   |FORTRAN-TO-LISP|::|END_LABEL|
   (|COMMON-LISP|::|RETURN|
    (|COMMON-LISP|::|VALUES| |FORTRAN-TO-LISP|::|ALNORM| |COMMON-LISP|::|NIL|
     |COMMON-LISP|::|NIL|)))))

