;;; Compiled by f2cl version 2.0 beta Date: 2006/05/05 20:28:21 
;;; Using Lisp CLISP 2.38 (2006-01-24) (built on guru.build.karan.org)
;;; Options: ((:prune-labels nil) (:auto-save t) (:relaxed-array-decls t)
;;;  (:coerce-assigns :as-needed) (:array-type ':array) (:array-slicing t)
;;;  (:declare-common nil) (:float-format single-float))

(in-package :common-lisp-user)


(|COMMON-LISP|::|LET*|
 ((|FORTRAN-TO-LISP|::|BS| 85.) (|FORTRAN-TO-LISP|::|BSSTR| 86.)
  (|FORTRAN-TO-LISP|::|COVREQ| 15.) (|FORTRAN-TO-LISP|::|FDH| 74.)
  (|FORTRAN-TO-LISP|::|FLO| 88.) (|FORTRAN-TO-LISP|::|FLOSTR| 89.)
  (|FORTRAN-TO-LISP|::|LOO| 84.) (|FORTRAN-TO-LISP|::|NB| 87.)
  (|FORTRAN-TO-LISP|::|NFIX| 83.) (|FORTRAN-TO-LISP|::|RDREQ| 57.)
  (|FORTRAN-TO-LISP|::|REGD| 67.) (|FORTRAN-TO-LISP|::|XNOTI| 90.)
  (|FORTRAN-TO-LISP|::|HALF| #1=0.5d0)
  (|FORTRAN-TO-LISP|::|NEGONE| (|COMMON-LISP|::|-| 1.0d0))
  (|FORTRAN-TO-LISP|::|ONE| #2=1.0d0) (|FORTRAN-TO-LISP|::|ZERO| #3=0.0d0))
 (|COMMON-LISP|::|DECLARE|
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 85. 85.)
   |FORTRAN-TO-LISP|::|BS|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 86. 86.)
   |FORTRAN-TO-LISP|::|BSSTR|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 15. 15.)
   |FORTRAN-TO-LISP|::|COVREQ|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 74. 74.)
   |FORTRAN-TO-LISP|::|FDH|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 88. 88.)
   |FORTRAN-TO-LISP|::|FLO|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 89. 89.)
   |FORTRAN-TO-LISP|::|FLOSTR|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 84. 84.)
   |FORTRAN-TO-LISP|::|LOO|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 87. 87.)
   |FORTRAN-TO-LISP|::|NB|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 83. 83.)
   |FORTRAN-TO-LISP|::|NFIX|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 57. 57.)
   |FORTRAN-TO-LISP|::|RDREQ|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 67. 67.)
   |FORTRAN-TO-LISP|::|REGD|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 90. 90.)
   |FORTRAN-TO-LISP|::|XNOTI|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #1# #1#)
   |FORTRAN-TO-LISP|::|HALF|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
   |FORTRAN-TO-LISP|::|NEGONE|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #2# #2#)
   |FORTRAN-TO-LISP|::|ONE|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #3# #3#)
   |FORTRAN-TO-LISP|::|ZERO|))
 (|COMMON-LISP|::|DEFUN| |FORTRAN-TO-LISP|::|DG2LRD|
  (|FORTRAN-TO-LISP|::|DR| |FORTRAN-TO-LISP|::|IV| |FORTRAN-TO-LISP|::|L|
   |FORTRAN-TO-LISP|::|LH| |FORTRAN-TO-LISP|::|LIV| |FORTRAN-TO-LISP|::|LV|
   |FORTRAN-TO-LISP|::|ND| |FORTRAN-TO-LISP|::|N| |FORTRAN-TO-LISP|::|P|
   |FORTRAN-TO-LISP|::|PS| |FORTRAN-TO-LISP|::|R| |FORTRAN-TO-LISP|::|RD|
   |FORTRAN-TO-LISP|::|RHOI| |FORTRAN-TO-LISP|::|RHOR| |FORTRAN-TO-LISP|::|V|
   |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|X| |FORTRAN-TO-LISP|::|Z|)
  (|COMMON-LISP|::|DECLARE|
   (|COMMON-LISP|::|TYPE|
    (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT| (|COMMON-LISP|::|*|))
    |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|X| |FORTRAN-TO-LISP|::|W|
    |FORTRAN-TO-LISP|::|V| |FORTRAN-TO-LISP|::|RHOR| |FORTRAN-TO-LISP|::|RD|
    |FORTRAN-TO-LISP|::|R| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|DR|)
   (|COMMON-LISP|::|TYPE|
    (|COMMON-LISP|::|ARRAY| |F2CL-LIB|::|INTEGER4| (|COMMON-LISP|::|*|))
    |FORTRAN-TO-LISP|::|RHOI| |FORTRAN-TO-LISP|::|IV|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|PS|
    |FORTRAN-TO-LISP|::|P| |FORTRAN-TO-LISP|::|N| |FORTRAN-TO-LISP|::|ND|
    |FORTRAN-TO-LISP|::|LV| |FORTRAN-TO-LISP|::|LIV| |FORTRAN-TO-LISP|::|LH|))
  (|F2CL-LIB|::|WITH-MULTI-ARRAY-DATA|
   ((|FORTRAN-TO-LISP|::|IV| |F2CL-LIB|::|INTEGER4|
     |FORTRAN-TO-LISP|::|IV-%DATA%| |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|RHOI| |F2CL-LIB|::|INTEGER4|
     |FORTRAN-TO-LISP|::|RHOI-%DATA%| |FORTRAN-TO-LISP|::|RHOI-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|DR| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|DR-%DATA%| |FORTRAN-TO-LISP|::|DR-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|L| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|L-%DATA%| |FORTRAN-TO-LISP|::|L-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|R| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|R-%DATA%| |FORTRAN-TO-LISP|::|R-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|RD| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|RD-%DATA%| |FORTRAN-TO-LISP|::|RD-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|RHOR| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|RHOR-%DATA%| |FORTRAN-TO-LISP|::|RHOR-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|V| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|V-%DATA%| |FORTRAN-TO-LISP|::|V-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|W| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|W-%DATA%| |FORTRAN-TO-LISP|::|W-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|X| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|X-%DATA%| |FORTRAN-TO-LISP|::|X-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|Z| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|Z-%DATA%| |FORTRAN-TO-LISP|::|Z-%OFFSET%|))
   (|COMMON-LISP|::|PROG|
    ((|FORTRAN-TO-LISP|::|FRAC| #3#) (|FORTRAN-TO-LISP|::|HI| #3#)
     (|FORTRAN-TO-LISP|::|RI| #3#) (|FORTRAN-TO-LISP|::|S| #3#)
     (|FORTRAN-TO-LISP|::|T1| #3#) (|FORTRAN-TO-LISP|::|BS1| 0.)
     (|FORTRAN-TO-LISP|::|BSINC| 0.) (|FORTRAN-TO-LISP|::|FLO1| 0.)
     (|FORTRAN-TO-LISP|::|FLOINC| 0.) (|FORTRAN-TO-LISP|::|H1| 0.)
     (|FORTRAN-TO-LISP|::|HPS1| 0.) (|FORTRAN-TO-LISP|::|I| 0.)
     (|FORTRAN-TO-LISP|::|J| 0.) (|FORTRAN-TO-LISP|::|J1| 0.)
     (|FORTRAN-TO-LISP|::|K| 0.) (|FORTRAN-TO-LISP|::|KI| 0.)
     (|FORTRAN-TO-LISP|::|KI1| 0.) (|FORTRAN-TO-LISP|::|KID| 0.)
     (|FORTRAN-TO-LISP|::|L1| 0.) (|F2CL-LIB|::|LE| 0.)
     (|FORTRAN-TO-LISP|::|LL| 0.) (|FORTRAN-TO-LISP|::|LOO1| 0.)
     (|FORTRAN-TO-LISP|::|N1| 0.) (|FORTRAN-TO-LISP|::|PMPS| 0.)
     (|FORTRAN-TO-LISP|::|PP1O2| 0.) (|FORTRAN-TO-LISP|::|PS1| 0.)
     (|FORTRAN-TO-LISP|::|PX| 0.) (|FORTRAN-TO-LISP|::|RDR| 0.)
     (|FORTRAN-TO-LISP|::|XNI| 0.) (|FORTRAN-TO-LISP|::|ZAP1| 0.)
     (|FORTRAN-TO-LISP|::|ZAPLEN| 0.)
     (|FORTRAN-TO-LISP|::|USEFLO| |COMMON-LISP|::|NIL|)
     (|FORTRAN-TO-LISP|::|T$| #3#))
    (|COMMON-LISP|::|DECLARE|
     (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
      |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|T1| |FORTRAN-TO-LISP|::|S|
      |FORTRAN-TO-LISP|::|RI| |FORTRAN-TO-LISP|::|HI|
      |FORTRAN-TO-LISP|::|FRAC|)
     (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|)
      |FORTRAN-TO-LISP|::|ZAPLEN| |FORTRAN-TO-LISP|::|ZAP1|
      |FORTRAN-TO-LISP|::|XNI| |FORTRAN-TO-LISP|::|RDR| |FORTRAN-TO-LISP|::|PX|
      |FORTRAN-TO-LISP|::|PS1| |FORTRAN-TO-LISP|::|PP1O2|
      |FORTRAN-TO-LISP|::|PMPS| |FORTRAN-TO-LISP|::|N1|
      |FORTRAN-TO-LISP|::|LOO1| |FORTRAN-TO-LISP|::|LL| |F2CL-LIB|::|LE|
      |FORTRAN-TO-LISP|::|L1| |FORTRAN-TO-LISP|::|KID| |FORTRAN-TO-LISP|::|KI1|
      |FORTRAN-TO-LISP|::|KI| |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|J1|
      |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|HPS1|
      |FORTRAN-TO-LISP|::|H1| |FORTRAN-TO-LISP|::|FLOINC|
      |FORTRAN-TO-LISP|::|FLO1| |FORTRAN-TO-LISP|::|BSINC|
      |FORTRAN-TO-LISP|::|BS1|)
     (|COMMON-LISP|::|TYPE| |F2CL-LIB|::|LOGICAL| |FORTRAN-TO-LISP|::|USEFLO|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|I|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RDREQ|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|RDR|
     (|COMMON-LISP|::|MOD|
      (|COMMON-LISP|::|THE| |F2CL-LIB|::|INTEGER4|
       (|COMMON-LISP|::|TRUNCATE| |FORTRAN-TO-LISP|::|I| 2.))
      3.))
    (|COMMON-LISP|::|IF| (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|RDR| 0.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|H1|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|FDH|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|USEFLO| |F2CL-LIB|::|%FALSE%|)
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PX| |FORTRAN-TO-LISP|::|P|)
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|N1| |FORTRAN-TO-LISP|::|N|)
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|FRAC| |FORTRAN-TO-LISP|::|ONE|)
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|XNI| 0.)
    (|COMMON-LISP|::|IF| (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|RDR| 1.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL120|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LOO1|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|LOO|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|COND|
     ((|COMMON-LISP|::|OR| (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|LOO1| 0.)
       (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|LOO1| 6.))
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
        (|FORTRAN-TO-LISP|::|REGD|) ((1. |FORTRAN-TO-LISP|::|LIV|))
        |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
       -1.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|)))
    (|COMMON-LISP|::|COND|
     ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|LOO1| 3.)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|USEFLO| |F2CL-LIB|::|%TRUE%|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|FLO1|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
        (|FORTRAN-TO-LISP|::|FLO|) ((1. |FORTRAN-TO-LISP|::|LIV|))
        |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|FLOINC|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
        (|FORTRAN-TO-LISP|::|FLOSTR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
        |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LOO1|
       (|F2CL-LIB|::|INT-SUB| |FORTRAN-TO-LISP|::|LOO1| 3.))))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|XNI|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|XNOTI|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PX|
     (|F2CL-LIB|::|INT-SUB| |FORTRAN-TO-LISP|::|P|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|NFIX|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)))
    (|COMMON-LISP|::|COND|
     ((|COMMON-LISP|::|OR|
       (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|PX| |FORTRAN-TO-LISP|::|PS|)
       (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|PX| |FORTRAN-TO-LISP|::|P|))
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
        (|FORTRAN-TO-LISP|::|REGD|) ((1. |FORTRAN-TO-LISP|::|LIV|))
        |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
       -2.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|)))
    (|COMMON-LISP|::|IF| (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|LOO1| 1.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL120|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|N1|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|NB|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|COND|
     ((|COMMON-LISP|::|OR| (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|N1| 0.)
       (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|N1| |FORTRAN-TO-LISP|::|N|))
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
        (|FORTRAN-TO-LISP|::|REGD|) ((1. |FORTRAN-TO-LISP|::|LIV|))
        |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
       -3.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|)))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|BS1|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|BS|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|BSINC|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|BSSTR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|IF| (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|H1| 0.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL190|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>=|
      (|F2CL-LIB|::|IABS|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
        (|FORTRAN-TO-LISP|::|COVREQ|) ((1. |FORTRAN-TO-LISP|::|LIV|))
        |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
      3.)
     (|FORTRAN-TO-LISP|::|DL7SQR| |FORTRAN-TO-LISP|::|P|
      (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|V|
       |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|H1|)
       ((1. |FORTRAN-TO-LISP|::|LV|)))
      |FORTRAN-TO-LISP|::|L|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PP1O2|
     (|COMMON-LISP|::|THE| |F2CL-LIB|::|INTEGER4|
      (|COMMON-LISP|::|TRUNCATE|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|PX|
        (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|PX| 1.))
       2.)))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PS1|
     (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|PS| 1.))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ZAP1|
     (|COMMON-LISP|::|+|
      (|COMMON-LISP|::|THE| |F2CL-LIB|::|INTEGER4|
       (|COMMON-LISP|::|TRUNCATE|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|PS| |FORTRAN-TO-LISP|::|PS1|)
        2.))
      1.))
    (|COMMON-LISP|::|SETF| |F2CL-LIB|::|LE| 0.)
    (|F2CL-LIB|::|FDO|
     (|FORTRAN-TO-LISP|::|I| 1.
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
     ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|N1|)
      |COMMON-LISP|::|NIL|)
     (|COMMON-LISP|::|TAGBODY|
      (|COMMON-LISP|::|COND|
       (|FORTRAN-TO-LISP|::|USEFLO|
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|FRAC|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RHOR-%DATA%|
          (|FORTRAN-TO-LISP|::|FLO1|) ((1. |COMMON-LISP|::|*|))
          |FORTRAN-TO-LISP|::|RHOR-%OFFSET%|))
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|FLO1|
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|FLO1|
          |FORTRAN-TO-LISP|::|FLOINC|))))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|L1|
       (|F2CL-LIB|::|INT-ADD| |F2CL-LIB|::|LE| 1.))
      (|COMMON-LISP|::|IF|
       (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|L1| |FORTRAN-TO-LISP|::|N|)
       (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL110|))
      (|COMMON-LISP|::|SETF| |F2CL-LIB|::|LE|
       (|F2CL-LIB|::|INT-ADD| |F2CL-LIB|::|LE|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RHOI-%DATA%|
         (|FORTRAN-TO-LISP|::|BS1|) ((1. |COMMON-LISP|::|*|))
         |FORTRAN-TO-LISP|::|RHOI-%OFFSET%|)))
      (|COMMON-LISP|::|IF|
       (|COMMON-LISP|::|>| |F2CL-LIB|::|LE| |FORTRAN-TO-LISP|::|N|)
       (|COMMON-LISP|::|SETF| |F2CL-LIB|::|LE| |FORTRAN-TO-LISP|::|N|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|BS1|
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|BS1|
        |FORTRAN-TO-LISP|::|BSINC|))
      (|FORTRAN-TO-LISP|::|DV7CPY| |FORTRAN-TO-LISP|::|PP1O2|
       |FORTRAN-TO-LISP|::|L|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|V|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|H1|)
        ((1. |FORTRAN-TO-LISP|::|LV|))))
      (|COMMON-LISP|::|IF|
       (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|PS| |FORTRAN-TO-LISP|::|PX|)
       (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL50|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|ZAP1|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KI| |FORTRAN-TO-LISP|::|L1|)
      (|F2CL-LIB|::|FDO|
       (|FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|PS1|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J| 1.))
       ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|P|)
        |COMMON-LISP|::|NIL|)
       (|COMMON-LISP|::|TAGBODY|
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KI|
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|KI|
          |FORTRAN-TO-LISP|::|N|))
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KI1|
         |FORTRAN-TO-LISP|::|KI|)
        (|F2CL-LIB|::|FDO|
         (|FORTRAN-TO-LISP|::|LL| |FORTRAN-TO-LISP|::|L1|
          (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|LL| 1.))
         ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|LL| |F2CL-LIB|::|LE|)
          |COMMON-LISP|::|NIL|)
         (|COMMON-LISP|::|TAGBODY|
          (|FORTRAN-TO-LISP|::|DV2AXY| |FORTRAN-TO-LISP|::|PS|
           (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|L|
            |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|K|)
            ((1. |FORTRAN-TO-LISP|::|LH|)))
           (|COMMON-LISP|::|*| (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|FRAC|)
            (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
             (|FORTRAN-TO-LISP|::|KI1|) ((1. |FORTRAN-TO-LISP|::|N|))
             |FORTRAN-TO-LISP|::|RD-%OFFSET%|))
           (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|DR|
            |COMMON-LISP|::|DOUBLE-FLOAT| (1. |FORTRAN-TO-LISP|::|LL|)
            ((1. |FORTRAN-TO-LISP|::|ND|) (1. |FORTRAN-TO-LISP|::|P|)))
           (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|L|
            |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|K|)
            ((1. |FORTRAN-TO-LISP|::|LH|))))
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KI1|
           (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|KI1| 1.))
          |FORTRAN-TO-LISP|::|LABEL10|))
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K|
          |FORTRAN-TO-LISP|::|PS|))
        (|F2CL-LIB|::|FDO|
         (|FORTRAN-TO-LISP|::|J1| |FORTRAN-TO-LISP|::|PS1|
          (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J1| 1.))
         ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|J1| |FORTRAN-TO-LISP|::|J|)
          |COMMON-LISP|::|NIL|)
         (|COMMON-LISP|::|TAGBODY|
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KI|
           (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|KI|
            |FORTRAN-TO-LISP|::|N|))
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KI1|
           |FORTRAN-TO-LISP|::|KI|)
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
           |FORTRAN-TO-LISP|::|ZERO|)
          (|F2CL-LIB|::|FDO|
           (|FORTRAN-TO-LISP|::|LL| |FORTRAN-TO-LISP|::|L1|
            (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|LL| 1.))
           ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|LL| |F2CL-LIB|::|LE|)
            |COMMON-LISP|::|NIL|)
           (|COMMON-LISP|::|TAGBODY|
            (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
             (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|T$|
              (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
               (|FORTRAN-TO-LISP|::|KI1|) ((1. |FORTRAN-TO-LISP|::|N|))
               |FORTRAN-TO-LISP|::|RD-%OFFSET%|)))
            (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KI1|
             (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|KI1| 1.))
            |FORTRAN-TO-LISP|::|LABEL20|))
          (|COMMON-LISP|::|SETF|
           (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|L-%DATA%|
            (|FORTRAN-TO-LISP|::|K|) ((1. |FORTRAN-TO-LISP|::|LH|))
            |FORTRAN-TO-LISP|::|L-%OFFSET%|)
           (|COMMON-LISP|::|-|
            (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|L-%DATA%|
             (|FORTRAN-TO-LISP|::|K|) ((1. |FORTRAN-TO-LISP|::|LH|))
             |FORTRAN-TO-LISP|::|L-%OFFSET%|)
            (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|FRAC|
             |FORTRAN-TO-LISP|::|T$|)))
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
           (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K| 1.))
          |FORTRAN-TO-LISP|::|LABEL30|))
        |FORTRAN-TO-LISP|::|LABEL40|))
      |FORTRAN-TO-LISP|::|LABEL50|
      (|F2CL-LIB|::|FDO|
       (|FORTRAN-TO-LISP|::|LL| |FORTRAN-TO-LISP|::|L1|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|LL| 1.))
       ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|LL| |F2CL-LIB|::|LE|)
        |COMMON-LISP|::|NIL|)
       (|COMMON-LISP|::|TAGBODY|
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
         (|COMMON-LISP|::|*| (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|FRAC|)
          (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
           (|FORTRAN-TO-LISP|::|LL|) ((1. |FORTRAN-TO-LISP|::|N|))
           |FORTRAN-TO-LISP|::|RD-%OFFSET%|)))
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| 1.)
        (|F2CL-LIB|::|FDO|
         (|FORTRAN-TO-LISP|::|J| 1.
          (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J| 1.))
         ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|PS|)
          |COMMON-LISP|::|NIL|)
         (|COMMON-LISP|::|TAGBODY|
          (|FORTRAN-TO-LISP|::|DV2AXY| |FORTRAN-TO-LISP|::|J|
           (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|L|
            |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|K|)
            ((1. |FORTRAN-TO-LISP|::|LH|)))
           (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T$|
            (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|DR-%DATA%|
             (|FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|LL|)
             ((1. |FORTRAN-TO-LISP|::|ND|) (1. |FORTRAN-TO-LISP|::|P|))
             |FORTRAN-TO-LISP|::|DR-%OFFSET%|))
           (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|DR|
            |COMMON-LISP|::|DOUBLE-FLOAT| (1. |FORTRAN-TO-LISP|::|LL|)
            ((1. |FORTRAN-TO-LISP|::|ND|) (1. |FORTRAN-TO-LISP|::|P|)))
           (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|L|
            |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|K|)
            ((1. |FORTRAN-TO-LISP|::|LH|))))
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
           (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K|
            |FORTRAN-TO-LISP|::|J|))
          |FORTRAN-TO-LISP|::|LABEL60|))
        |FORTRAN-TO-LISP|::|LABEL70|))
      (|COMMON-LISP|::|MULTIPLE-VALUE-BIND|
       (|FORTRAN-TO-LISP|::|VAR-0| |FORTRAN-TO-LISP|::|VAR-1|
        |FORTRAN-TO-LISP|::|VAR-2| |FORTRAN-TO-LISP|::|VAR-3|
        |FORTRAN-TO-LISP|::|VAR-4|)
       (|FORTRAN-TO-LISP|::|DL7SRT| 1. |FORTRAN-TO-LISP|::|PX|
        |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|J|)
       (|COMMON-LISP|::|DECLARE|
        (|COMMON-LISP|::|IGNORE| |FORTRAN-TO-LISP|::|VAR-0|
         |FORTRAN-TO-LISP|::|VAR-1| |FORTRAN-TO-LISP|::|VAR-2|
         |FORTRAN-TO-LISP|::|VAR-3|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
        |FORTRAN-TO-LISP|::|VAR-4|))
      (|COMMON-LISP|::|COND|
       ((|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|J| 0.)
        (|FORTRAN-TO-LISP|::|DV7SCP| |FORTRAN-TO-LISP|::|PX|
         |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|ZERO|)
        (|F2CL-LIB|::|FDO|
         (|FORTRAN-TO-LISP|::|LL| |FORTRAN-TO-LISP|::|L1|
          (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|LL| 1.))
         ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|LL| |F2CL-LIB|::|LE|)
          |COMMON-LISP|::|NIL|)
         (|COMMON-LISP|::|TAGBODY|
          (|FORTRAN-TO-LISP|::|DV2AXY| |FORTRAN-TO-LISP|::|PS|
           |FORTRAN-TO-LISP|::|W|
           (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|R-%DATA%|
            (|FORTRAN-TO-LISP|::|LL|) ((1. |FORTRAN-TO-LISP|::|N|))
            |FORTRAN-TO-LISP|::|R-%OFFSET%|)
           (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|DR|
            |COMMON-LISP|::|DOUBLE-FLOAT| (1. |FORTRAN-TO-LISP|::|LL|)
            ((1. |FORTRAN-TO-LISP|::|ND|) (1. |FORTRAN-TO-LISP|::|P|)))
           |FORTRAN-TO-LISP|::|W|)
          (|COMMON-LISP|::|IF|
           (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|PS1|
            |FORTRAN-TO-LISP|::|PX|)
           (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL90|))
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
           |FORTRAN-TO-LISP|::|L1|)
          (|F2CL-LIB|::|FDO|
           (|FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|PS1|
            (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J| 1.))
           ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|P|)
            |COMMON-LISP|::|NIL|)
           (|COMMON-LISP|::|TAGBODY|
            (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
             (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K|
              |FORTRAN-TO-LISP|::|N|))
            (|COMMON-LISP|::|SETF|
             (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
              (|FORTRAN-TO-LISP|::|J|) ((1. |FORTRAN-TO-LISP|::|P|))
              |FORTRAN-TO-LISP|::|W-%OFFSET%|)
             (|COMMON-LISP|::|+|
              (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
               (|FORTRAN-TO-LISP|::|J|) ((1. |FORTRAN-TO-LISP|::|P|))
               |FORTRAN-TO-LISP|::|W-%OFFSET%|)
              (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|R-%DATA%|
               (|FORTRAN-TO-LISP|::|K|) ((1. |FORTRAN-TO-LISP|::|N|))
               |FORTRAN-TO-LISP|::|R-%OFFSET%|)))
            |FORTRAN-TO-LISP|::|LABEL80|))
          |FORTRAN-TO-LISP|::|LABEL90|))
        (|FORTRAN-TO-LISP|::|DL7IVM| |FORTRAN-TO-LISP|::|PX|
         |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|W|)
        (|FORTRAN-TO-LISP|::|DL7ITV| |FORTRAN-TO-LISP|::|PX|
         |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|W|)
        (|FORTRAN-TO-LISP|::|DS7LVM| |FORTRAN-TO-LISP|::|PX|
         |FORTRAN-TO-LISP|::|Z|
         (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|V|
          |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|H1|)
          ((1. |FORTRAN-TO-LISP|::|LV|)))
         |FORTRAN-TO-LISP|::|W|)
        (|COMMON-LISP|::|SETF|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
          |FORTRAN-TO-LISP|::|RD-%OFFSET%|)
         (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
          |FORTRAN-TO-LISP|::|FRAC|
          (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|PX|
           |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|Z|)))
        (|COMMON-LISP|::|COND|
         ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|XNI| 0.)
          (|FORTRAN-TO-LISP|::|DV2AXY| |FORTRAN-TO-LISP|::|PX|
           (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|RHOR|
            |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|XNI|)
            ((1. |COMMON-LISP|::|*|)))
           |FORTRAN-TO-LISP|::|FRAC| |FORTRAN-TO-LISP|::|W|
           |FORTRAN-TO-LISP|::|X|)
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|XNI|
           (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|XNI|
            |FORTRAN-TO-LISP|::|PX|)))))
       (|COMMON-LISP|::|T|
        (|COMMON-LISP|::|SETF|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
          |FORTRAN-TO-LISP|::|RD-%OFFSET%|)
         |FORTRAN-TO-LISP|::|NEGONE|)
        (|COMMON-LISP|::|COND|
         ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|XNI| 0.)
          (|FORTRAN-TO-LISP|::|DV7CPY| |FORTRAN-TO-LISP|::|PX|
           (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|RHOR|
            |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|XNI|)
            ((1. |COMMON-LISP|::|*|)))
           |FORTRAN-TO-LISP|::|X|)
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|XNI|
           (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|XNI|
            |FORTRAN-TO-LISP|::|PX|))))))
      |FORTRAN-TO-LISP|::|LABEL100|))
    |FORTRAN-TO-LISP|::|LABEL110|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|REGD|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     1.)
    (|COMMON-LISP|::|MULTIPLE-VALUE-BIND|
     (|FORTRAN-TO-LISP|::|VAR-0| |FORTRAN-TO-LISP|::|VAR-1|
      |FORTRAN-TO-LISP|::|VAR-2| |FORTRAN-TO-LISP|::|VAR-3|
      |FORTRAN-TO-LISP|::|VAR-4|)
     (|FORTRAN-TO-LISP|::|DL7SRT| 1. |FORTRAN-TO-LISP|::|P|
      |FORTRAN-TO-LISP|::|L|
      (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|V|
       |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|H1|)
       ((1. |FORTRAN-TO-LISP|::|LV|)))
      |FORTRAN-TO-LISP|::|J|)
     (|COMMON-LISP|::|DECLARE|
      (|COMMON-LISP|::|IGNORE| |FORTRAN-TO-LISP|::|VAR-0|
       |FORTRAN-TO-LISP|::|VAR-1| |FORTRAN-TO-LISP|::|VAR-2|
       |FORTRAN-TO-LISP|::|VAR-3|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|VAR-4|))
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|)
    |FORTRAN-TO-LISP|::|LABEL120|
    (|COMMON-LISP|::|IF| (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|H1| 0.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL190|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>=|
      (|F2CL-LIB|::|IABS|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
        (|FORTRAN-TO-LISP|::|COVREQ|) ((1. |FORTRAN-TO-LISP|::|LIV|))
        |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
      3.)
     (|FORTRAN-TO-LISP|::|DL7SQR| |FORTRAN-TO-LISP|::|P|
      (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|V|
       |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|H1|)
       ((1. |FORTRAN-TO-LISP|::|LV|)))
      |FORTRAN-TO-LISP|::|L|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|PS| |FORTRAN-TO-LISP|::|PX|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL170|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PS1|
     (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|PS| 1.))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PMPS|
     (|F2CL-LIB|::|INT-SUB| |FORTRAN-TO-LISP|::|PX| |FORTRAN-TO-LISP|::|PS|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ZAP1|
     (|COMMON-LISP|::|THE| |F2CL-LIB|::|INTEGER4|
      (|COMMON-LISP|::|TRUNCATE|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|PS| |FORTRAN-TO-LISP|::|PS1|)
       2.)))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ZAPLEN|
     (|COMMON-LISP|::|-|
      (|COMMON-LISP|::|THE| |F2CL-LIB|::|INTEGER4|
       (|COMMON-LISP|::|TRUNCATE|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|PX|
         (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|PX| 1.))
        2.))
      |FORTRAN-TO-LISP|::|ZAP1|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|HPS1|
     (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|H1| |FORTRAN-TO-LISP|::|ZAP1|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ZAP1|
     (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|ZAP1| 1.))
    (|F2CL-LIB|::|FDO|
     (|FORTRAN-TO-LISP|::|I| 1.
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
     ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|N|)
      |COMMON-LISP|::|NIL|)
     (|COMMON-LISP|::|TAGBODY|
      (|COMMON-LISP|::|COND|
       (|FORTRAN-TO-LISP|::|USEFLO|
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|FRAC|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RHOR-%DATA%|
          (|FORTRAN-TO-LISP|::|FLO1|) ((1. |COMMON-LISP|::|*|))
          |FORTRAN-TO-LISP|::|RHOR-%OFFSET%|))
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|FLO1|
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|FLO1|
          |FORTRAN-TO-LISP|::|FLOINC|))))
      (|FORTRAN-TO-LISP|::|DV7CPY| |FORTRAN-TO-LISP|::|ZAPLEN|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|L|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|ZAP1|)
        ((1. |FORTRAN-TO-LISP|::|LH|)))
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|V|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|HPS1|)
        ((1. |FORTRAN-TO-LISP|::|LV|))))
      (|FORTRAN-TO-LISP|::|DV7SCP| |FORTRAN-TO-LISP|::|PS|
       |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|ZAP1|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KI| |FORTRAN-TO-LISP|::|I|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KID| |FORTRAN-TO-LISP|::|KI|)
      (|F2CL-LIB|::|FDO|
       (|FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|PS1|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J| 1.))
       ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|PX|)
        |COMMON-LISP|::|NIL|)
       (|COMMON-LISP|::|TAGBODY|
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KI|
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|KI|
          |FORTRAN-TO-LISP|::|N|))
        (|FORTRAN-TO-LISP|::|DV2AXY| |FORTRAN-TO-LISP|::|PS|
         (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|L|
          |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|K|)
          ((1. |FORTRAN-TO-LISP|::|LH|)))
         (|COMMON-LISP|::|*| (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|FRAC|)
          (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
           (|FORTRAN-TO-LISP|::|KI|) ((1. |FORTRAN-TO-LISP|::|N|))
           |FORTRAN-TO-LISP|::|RD-%OFFSET%|))
         (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|DR|
          |COMMON-LISP|::|DOUBLE-FLOAT| (1. |FORTRAN-TO-LISP|::|I|)
          ((1. |FORTRAN-TO-LISP|::|ND|) (1. |FORTRAN-TO-LISP|::|P|)))
         (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|L|
          |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|K|)
          ((1. |FORTRAN-TO-LISP|::|LH|))))
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K|
          |FORTRAN-TO-LISP|::|PS|))
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KID|
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|KID|
          |FORTRAN-TO-LISP|::|N|))
        (|COMMON-LISP|::|SETF|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
          (|FORTRAN-TO-LISP|::|J|) ((1. |FORTRAN-TO-LISP|::|P|))
          |FORTRAN-TO-LISP|::|W-%OFFSET%|)
         (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|FRAC|
          (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|R-%DATA%|
           (|FORTRAN-TO-LISP|::|KID|) ((1. |FORTRAN-TO-LISP|::|N|))
           |FORTRAN-TO-LISP|::|R-%OFFSET%|)))
        (|F2CL-LIB|::|FDO|
         (|FORTRAN-TO-LISP|::|J1| |FORTRAN-TO-LISP|::|PS1|
          (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J1| 1.))
         ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|J1| |FORTRAN-TO-LISP|::|J|)
          |COMMON-LISP|::|NIL|)
         (|COMMON-LISP|::|TAGBODY|
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KI|
           (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|KI|
            |FORTRAN-TO-LISP|::|N|))
          (|COMMON-LISP|::|SETF|
           (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|L-%DATA%|
            (|FORTRAN-TO-LISP|::|K|) ((1. |FORTRAN-TO-LISP|::|LH|))
            |FORTRAN-TO-LISP|::|L-%OFFSET%|)
           (|COMMON-LISP|::|-|
            (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|L-%DATA%|
             (|FORTRAN-TO-LISP|::|K|) ((1. |FORTRAN-TO-LISP|::|LH|))
             |FORTRAN-TO-LISP|::|L-%OFFSET%|)
            (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|FRAC|
             (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
              (|FORTRAN-TO-LISP|::|KI|) ((1. |FORTRAN-TO-LISP|::|N|))
              |FORTRAN-TO-LISP|::|RD-%OFFSET%|))))
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
           (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K| 1.))
          |FORTRAN-TO-LISP|::|LABEL130|))
        |FORTRAN-TO-LISP|::|LABEL140|))
      (|COMMON-LISP|::|MULTIPLE-VALUE-BIND|
       (|FORTRAN-TO-LISP|::|VAR-0| |FORTRAN-TO-LISP|::|VAR-1|
        |FORTRAN-TO-LISP|::|VAR-2| |FORTRAN-TO-LISP|::|VAR-3|
        |FORTRAN-TO-LISP|::|VAR-4|)
       (|FORTRAN-TO-LISP|::|DL7SRT| |FORTRAN-TO-LISP|::|PS1|
        |FORTRAN-TO-LISP|::|PX| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|L|
        |FORTRAN-TO-LISP|::|J|)
       (|COMMON-LISP|::|DECLARE|
        (|COMMON-LISP|::|IGNORE| |FORTRAN-TO-LISP|::|VAR-0|
         |FORTRAN-TO-LISP|::|VAR-1| |FORTRAN-TO-LISP|::|VAR-2|
         |FORTRAN-TO-LISP|::|VAR-3|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
        |FORTRAN-TO-LISP|::|VAR-4|))
      (|COMMON-LISP|::|IF| (|COMMON-LISP|::|/=| |FORTRAN-TO-LISP|::|J| 0.)
       (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL150|))
      (|FORTRAN-TO-LISP|::|DV7CPY| |FORTRAN-TO-LISP|::|PS|
       |FORTRAN-TO-LISP|::|Z|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|DR|
        |COMMON-LISP|::|DOUBLE-FLOAT| (1. |FORTRAN-TO-LISP|::|I|)
        ((1. |FORTRAN-TO-LISP|::|ND|) (1. |FORTRAN-TO-LISP|::|P|))))
      (|FORTRAN-TO-LISP|::|DV7SCP| |FORTRAN-TO-LISP|::|PMPS|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|Z|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|PS1|)
        ((1. |FORTRAN-TO-LISP|::|P|)))
       |FORTRAN-TO-LISP|::|ZERO|)
      (|FORTRAN-TO-LISP|::|DL7IVM| |FORTRAN-TO-LISP|::|PX|
       |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|Z|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|HI|
       (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|PX|
        |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|Z|))
      (|FORTRAN-TO-LISP|::|DL7IVM| |FORTRAN-TO-LISP|::|PX|
       |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|W|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|RI|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|FRAC|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|R-%DATA%|
         (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
         |FORTRAN-TO-LISP|::|R-%OFFSET%|)))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
       (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|PMPS|
        (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
         |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|PS1|)
         ((1. |FORTRAN-TO-LISP|::|P|)))
        (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|Z|
         |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|PS1|)
         ((1. |FORTRAN-TO-LISP|::|P|)))))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|S|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|FRAC|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
         (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
         |FORTRAN-TO-LISP|::|RD-%OFFSET%|)))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
       (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|ONE|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|S| |FORTRAN-TO-LISP|::|HI|)))
      (|COMMON-LISP|::|IF|
       (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|T1| |FORTRAN-TO-LISP|::|ZERO|)
       (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL150|))
      (|FORTRAN-TO-LISP|::|DV2AXY| |FORTRAN-TO-LISP|::|PX|
       |FORTRAN-TO-LISP|::|W|
       (|COMMON-LISP|::|/|
        (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|RI|
         (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|S| |FORTRAN-TO-LISP|::|T$|))
        |FORTRAN-TO-LISP|::|T1|)
       |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|W|)
      (|FORTRAN-TO-LISP|::|DL7ITV| |FORTRAN-TO-LISP|::|PX|
       |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|W|)
      (|FORTRAN-TO-LISP|::|DS7LVM| |FORTRAN-TO-LISP|::|PX|
       |FORTRAN-TO-LISP|::|Z|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|V|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|H1|)
        ((1. |FORTRAN-TO-LISP|::|LV|)))
       |FORTRAN-TO-LISP|::|W|)
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
        (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
        |FORTRAN-TO-LISP|::|RD-%OFFSET%|)
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
        (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|PX|
         |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|Z|)))
      (|COMMON-LISP|::|COND|
       ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|XNI| 0.)
        (|FORTRAN-TO-LISP|::|DV2AXY| |FORTRAN-TO-LISP|::|PX|
         (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|RHOR|
          |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|XNI|)
          ((1. |COMMON-LISP|::|*|)))
         |FORTRAN-TO-LISP|::|ONE| |FORTRAN-TO-LISP|::|W|
         |FORTRAN-TO-LISP|::|X|)
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|XNI|
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|XNI|
          |FORTRAN-TO-LISP|::|PX|))))
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL160|)
      |FORTRAN-TO-LISP|::|LABEL150|
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
        (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
        |FORTRAN-TO-LISP|::|RD-%OFFSET%|)
       |FORTRAN-TO-LISP|::|NEGONE|)
      (|COMMON-LISP|::|COND|
       ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|XNI| 0.)
        (|FORTRAN-TO-LISP|::|DV7CPY| |FORTRAN-TO-LISP|::|PX|
         (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|RHOR|
          |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|XNI|)
          ((1. |COMMON-LISP|::|*|)))
         |FORTRAN-TO-LISP|::|X|)
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|XNI|
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|XNI|
          |FORTRAN-TO-LISP|::|PX|))))
      |FORTRAN-TO-LISP|::|LABEL160|))
    (|FORTRAN-TO-LISP|::|DV7CPY| |FORTRAN-TO-LISP|::|ZAPLEN|
     (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|L|
      |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|ZAP1|)
      ((1. |FORTRAN-TO-LISP|::|LH|)))
     (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|V|
      |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|HPS1|)
      ((1. |FORTRAN-TO-LISP|::|LV|))))
    (|COMMON-LISP|::|MULTIPLE-VALUE-BIND|
     (|FORTRAN-TO-LISP|::|VAR-0| |FORTRAN-TO-LISP|::|VAR-1|
      |FORTRAN-TO-LISP|::|VAR-2| |FORTRAN-TO-LISP|::|VAR-3|
      |FORTRAN-TO-LISP|::|VAR-4|)
     (|FORTRAN-TO-LISP|::|DL7SRT| |FORTRAN-TO-LISP|::|PS1|
      |FORTRAN-TO-LISP|::|PX| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|L|
      |FORTRAN-TO-LISP|::|J|)
     (|COMMON-LISP|::|DECLARE|
      (|COMMON-LISP|::|IGNORE| |FORTRAN-TO-LISP|::|VAR-0|
       |FORTRAN-TO-LISP|::|VAR-1| |FORTRAN-TO-LISP|::|VAR-2|
       |FORTRAN-TO-LISP|::|VAR-3|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|VAR-4|))
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL200|)
    |FORTRAN-TO-LISP|::|LABEL170|
    (|F2CL-LIB|::|FDO|
     (|FORTRAN-TO-LISP|::|I| 1.
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
     ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|N|)
      |COMMON-LISP|::|NIL|)
     (|COMMON-LISP|::|TAGBODY|
      (|COMMON-LISP|::|COND|
       (|FORTRAN-TO-LISP|::|USEFLO|
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|FRAC|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RHOR-%DATA%|
          (|FORTRAN-TO-LISP|::|FLO1|) ((1. |COMMON-LISP|::|*|))
          |FORTRAN-TO-LISP|::|RHOR-%OFFSET%|))
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|FLO1|
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|FLO1|
          |FORTRAN-TO-LISP|::|FLOINC|))))
      (|FORTRAN-TO-LISP|::|DL7IVM| |FORTRAN-TO-LISP|::|PX|
       |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|L|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|DR|
        |COMMON-LISP|::|DOUBLE-FLOAT| (1. |FORTRAN-TO-LISP|::|I|)
        ((1. |FORTRAN-TO-LISP|::|ND|) (1. |FORTRAN-TO-LISP|::|P|))))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|S|
       (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|PX|
        |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|Z|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
       (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|ONE|
        (|COMMON-LISP|::|*| (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|FRAC|)
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
          |FORTRAN-TO-LISP|::|RD-%OFFSET%|)
         |FORTRAN-TO-LISP|::|S|)))
      (|COMMON-LISP|::|COND|
       ((|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|ZERO|)
        (|COMMON-LISP|::|SETF|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
          |FORTRAN-TO-LISP|::|RD-%OFFSET%|)
         |FORTRAN-TO-LISP|::|NEGONE|)
        (|COMMON-LISP|::|COND|
         ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|XNI| 0.)
          (|FORTRAN-TO-LISP|::|DV7CPY| |FORTRAN-TO-LISP|::|PX|
           (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|RHOR|
            |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|XNI|)
            ((1. |COMMON-LISP|::|*|)))
           |FORTRAN-TO-LISP|::|X|)
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|XNI|
           (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|XNI|
            |FORTRAN-TO-LISP|::|PX|)))))
       (|COMMON-LISP|::|T|
        (|COMMON-LISP|::|SETF|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RD-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
          |FORTRAN-TO-LISP|::|RD-%OFFSET%|)
         (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
          |FORTRAN-TO-LISP|::|FRAC|
          (|COMMON-LISP|::|EXPT|
           (|COMMON-LISP|::|/|
            (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|R-%DATA%|
             (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
             |FORTRAN-TO-LISP|::|R-%OFFSET%|)
            |FORTRAN-TO-LISP|::|T$|)
           2.)
          |FORTRAN-TO-LISP|::|S|))
        (|COMMON-LISP|::|COND|
         ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|XNI| 0.)
          (|FORTRAN-TO-LISP|::|DL7ITV| |FORTRAN-TO-LISP|::|PX|
           |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|L|
           |FORTRAN-TO-LISP|::|Z|)
          (|FORTRAN-TO-LISP|::|DV2AXY| |FORTRAN-TO-LISP|::|PX|
           (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|RHOR|
            |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|XNI|)
            ((1. |COMMON-LISP|::|*|)))
           (|COMMON-LISP|::|/|
            (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|FRAC|
             (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|R-%DATA%|
              (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
              |FORTRAN-TO-LISP|::|R-%OFFSET%|))
            |FORTRAN-TO-LISP|::|T$|)
           |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|X|)
          (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|XNI|
           (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|XNI|
            |FORTRAN-TO-LISP|::|PX|))))))
      |FORTRAN-TO-LISP|::|LABEL180|))
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL200|)
    |FORTRAN-TO-LISP|::|LABEL190|
    (|FORTRAN-TO-LISP|::|DV7SCP| |FORTRAN-TO-LISP|::|N1|
     |FORTRAN-TO-LISP|::|RD| |FORTRAN-TO-LISP|::|NEGONE|)
    |FORTRAN-TO-LISP|::|LABEL200|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|REGD|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     1.)
    |FORTRAN-TO-LISP|::|LABEL999|
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|END_LABEL|)
    |FORTRAN-TO-LISP|::|END_LABEL|
    (|COMMON-LISP|::|RETURN|
     (|COMMON-LISP|::|VALUES| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL|))))))

