;;; Compiled by f2cl version 2.0 beta Date: 2006/05/05 20:28:21 
;;; Using Lisp CLISP 2.38 (2006-01-24) (built on guru.build.karan.org)
;;; Options: ((:prune-labels nil) (:auto-save t) (:relaxed-array-decls t)
;;;  (:coerce-assigns :as-needed) (:array-type ':array) (:array-slicing t)
;;;  (:declare-common nil) (:float-format single-float))

(in-package :common-lisp-user)


(|COMMON-LISP|::|LET*|
 ((|FORTRAN-TO-LISP|::|COVPRT| 14.) (|FORTRAN-TO-LISP|::|COVREQ| 15.)
  (|FORTRAN-TO-LISP|::|LASTIV| 44.) (|FORTRAN-TO-LISP|::|LASTV| 45.)
  (|FORTRAN-TO-LISP|::|LMAX0| 35.) (|FORTRAN-TO-LISP|::|RDREQ| 57.))
 (|COMMON-LISP|::|DECLARE|
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 14. 14.)
   |FORTRAN-TO-LISP|::|COVPRT|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 15. 15.)
   |FORTRAN-TO-LISP|::|COVREQ|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 44. 44.)
   |FORTRAN-TO-LISP|::|LASTIV|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 45. 45.)
   |FORTRAN-TO-LISP|::|LASTV|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 35. 35.)
   |FORTRAN-TO-LISP|::|LMAX0|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 57. 57.)
   |FORTRAN-TO-LISP|::|RDREQ|))
 (|COMMON-LISP|::|DEFUN| |FORTRAN-TO-LISP|::|MADSEN| |COMMON-LISP|::|NIL|
  (|COMMON-LISP|::|PROG|
   ((|FORTRAN-TO-LISP|::|V|
     (|COMMON-LISP|::|MAKE-ARRAY| 200. :|ELEMENT-TYPE|
      '|COMMON-LISP|::|DOUBLE-FLOAT|))
    (|FORTRAN-TO-LISP|::|X|
     (|COMMON-LISP|::|MAKE-ARRAY| 2. :|ELEMENT-TYPE|
      '|COMMON-LISP|::|DOUBLE-FLOAT|))
    (|FORTRAN-TO-LISP|::|UR|
     (|COMMON-LISP|::|MAKE-ARRAY| 1. :|ELEMENT-TYPE|
      '|COMMON-LISP|::|DOUBLE-FLOAT|))
    (|FORTRAN-TO-LISP|::|IV|
     (|COMMON-LISP|::|MAKE-ARRAY| 92. :|ELEMENT-TYPE| '|F2CL-LIB|::|INTEGER4|))
    (|FORTRAN-TO-LISP|::|LIV| 0.) (|FORTRAN-TO-LISP|::|LV| 0.)
    (|FORTRAN-TO-LISP|::|NOUT| 0.)
    (|FORTRAN-TO-LISP|::|UI|
     (|COMMON-LISP|::|MAKE-ARRAY| 1. :|ELEMENT-TYPE| '|F2CL-LIB|::|INTEGER4|)))
   (|COMMON-LISP|::|DECLARE|
    (|COMMON-LISP|::|TYPE|
     (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT| (200.))
     |FORTRAN-TO-LISP|::|V|)
    (|COMMON-LISP|::|TYPE|
     (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT| (2.))
     |FORTRAN-TO-LISP|::|X|)
    (|COMMON-LISP|::|TYPE|
     (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT| (1.))
     |FORTRAN-TO-LISP|::|UR|)
    (|COMMON-LISP|::|TYPE|
     (|COMMON-LISP|::|ARRAY| |F2CL-LIB|::|INTEGER4| (92.))
     |FORTRAN-TO-LISP|::|IV|)
    (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|NOUT|
     |FORTRAN-TO-LISP|::|LV| |FORTRAN-TO-LISP|::|LIV|)
    (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|ARRAY| |F2CL-LIB|::|INTEGER4| (1.))
     |FORTRAN-TO-LISP|::|UI|))
   (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|NOUT|
    (|FORTRAN-TO-LISP|::|I7MDCN| 1.))
   (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LV| 200.)
   (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LIV| 92.)
   (|COMMON-LISP|::|SETF|
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|X| (1.) ((1. 2.))) 3.0d0)
   (|COMMON-LISP|::|SETF|
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|X| (2.) ((1. 2.))) 1.0d0)
   (|COMMON-LISP|::|SETF|
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV| (1.) ((1. 92.))) 0.)
   (|F2CL-LIB|::|FFORMAT| |FORTRAN-TO-LISP|::|NOUT|
    (" DGLG ON PROBLEM MADSEN..." #1="~%") |COMMON-LISP|::|NIL|)
   (|FORTRAN-TO-LISP|::|DGLG| 3. 2. 2. |FORTRAN-TO-LISP|::|X|
    #'|FORTRAN-TO-LISP|::|RHOLS| |FORTRAN-TO-LISP|::|UI|
    |FORTRAN-TO-LISP|::|UR| |FORTRAN-TO-LISP|::|IV| |FORTRAN-TO-LISP|::|LIV|
    |FORTRAN-TO-LISP|::|LV| |FORTRAN-TO-LISP|::|V| #'|FORTRAN-TO-LISP|::|MADRJ|
    |FORTRAN-TO-LISP|::|UI| |FORTRAN-TO-LISP|::|UR|
    #'|FORTRAN-TO-LISP|::|MADRJ|)
   (|F2CL-LIB|::|FFORMAT| |FORTRAN-TO-LISP|::|NOUT|
    (" DGLG NEEDED LIV .GE. " 1. (("~3D")) " AND LV .GE." 1. (("~4D")) #1#)
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV| (|FORTRAN-TO-LISP|::|LASTIV|)
     ((1. 92.)))
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV| (|FORTRAN-TO-LISP|::|LASTV|)
     ((1. 92.))))
   (|F2CL-LIB|::|FFORMAT| |FORTRAN-TO-LISP|::|NOUT|
    (#2="~%" " DGLF ON PROBLEM MADSEN..." #1#) |COMMON-LISP|::|NIL|)
   (|COMMON-LISP|::|SETF|
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|X| (1.) ((1. 2.))) 3.0d0)
   (|COMMON-LISP|::|SETF|
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|X| (2.) ((1. 2.))) 1.0d0)
   (|COMMON-LISP|::|SETF|
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV| (1.) ((1. 92.))) 0.)
   (|FORTRAN-TO-LISP|::|DGLF| 3. 2. 2. |FORTRAN-TO-LISP|::|X|
    #'|FORTRAN-TO-LISP|::|RHOLS| |FORTRAN-TO-LISP|::|UI|
    |FORTRAN-TO-LISP|::|UR| |FORTRAN-TO-LISP|::|IV| |FORTRAN-TO-LISP|::|LIV|
    |FORTRAN-TO-LISP|::|LV| |FORTRAN-TO-LISP|::|V| #'|FORTRAN-TO-LISP|::|MADRJ|
    |FORTRAN-TO-LISP|::|UI| |FORTRAN-TO-LISP|::|UR|
    #'|FORTRAN-TO-LISP|::|MADRJ|)
   (|FORTRAN-TO-LISP|::|DIVSET| 1. |FORTRAN-TO-LISP|::|IV|
    |FORTRAN-TO-LISP|::|LIV| |FORTRAN-TO-LISP|::|LV| |FORTRAN-TO-LISP|::|V|)
   (|COMMON-LISP|::|SETF|
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV| (|FORTRAN-TO-LISP|::|COVPRT|)
     ((1. 92.)))
    0.)
   (|COMMON-LISP|::|SETF|
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV| (|FORTRAN-TO-LISP|::|COVREQ|)
     ((1. 92.)))
    0.)
   (|COMMON-LISP|::|SETF|
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV| (|FORTRAN-TO-LISP|::|RDREQ|)
     ((1. 92.)))
    0.)
   (|COMMON-LISP|::|SETF|
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V| (|FORTRAN-TO-LISP|::|LMAX0|)
     ((1. 200.)))
    0.1d0)
   (|COMMON-LISP|::|SETF|
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|X| (1.) ((1. 2.))) 3.0d0)
   (|COMMON-LISP|::|SETF|
    (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|X| (2.) ((1. 2.))) 1.0d0)
   (|F2CL-LIB|::|FFORMAT| |FORTRAN-TO-LISP|::|NOUT|
    (#2# " DGLF ON PROBLEM MADSEN AGAIN..." #1#) |COMMON-LISP|::|NIL|)
   (|FORTRAN-TO-LISP|::|DGLF| 3. 2. 2. |FORTRAN-TO-LISP|::|X|
    #'|FORTRAN-TO-LISP|::|RHOLS| |FORTRAN-TO-LISP|::|UI|
    |FORTRAN-TO-LISP|::|UR| |FORTRAN-TO-LISP|::|IV| |FORTRAN-TO-LISP|::|LIV|
    |FORTRAN-TO-LISP|::|LV| |FORTRAN-TO-LISP|::|V| #'|FORTRAN-TO-LISP|::|MADRJ|
    |FORTRAN-TO-LISP|::|UI| |FORTRAN-TO-LISP|::|UR|
    #'|FORTRAN-TO-LISP|::|MADRJ|)
   |FORTRAN-TO-LISP|::|END_LABEL|
   (|COMMON-LISP|::|RETURN| |COMMON-LISP|::|NIL|))))

