;;; Compiled by f2cl version 2.0 beta Date: 2006/05/05 20:28:21 
;;; Using Lisp CLISP 2.38 (2006-01-24) (built on guru.build.karan.org)
;;; Options: ((:prune-labels nil) (:auto-save t) (:relaxed-array-decls t)
;;;  (:coerce-assigns :as-needed) (:array-type ':array) (:array-slicing t)
;;;  (:declare-common nil) (:float-format single-float))

(in-package :common-lisp-user)


(|COMMON-LISP|::|LET|
 ((|FORTRAN-TO-LISP|::|HALF| 0.5d0) (|FORTRAN-TO-LISP|::|ONE| 1.0d0)
  (|FORTRAN-TO-LISP|::|RLIMIT| #1=0.0d0) (|FORTRAN-TO-LISP|::|ZERO| #1#))
 (|COMMON-LISP|::|DECLARE|
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
   |FORTRAN-TO-LISP|::|ZERO| |FORTRAN-TO-LISP|::|RLIMIT|
   |FORTRAN-TO-LISP|::|ONE| |FORTRAN-TO-LISP|::|HALF|))
 (|COMMON-LISP|::|DEFUN| |FORTRAN-TO-LISP|::|RHOLS|
  (|FORTRAN-TO-LISP|::|NEED| |FORTRAN-TO-LISP|::|F| |FORTRAN-TO-LISP|::|N|
   |FORTRAN-TO-LISP|::|NF| |FORTRAN-TO-LISP|::|XN| |FORTRAN-TO-LISP|::|R|
   |FORTRAN-TO-LISP|::|RP| |FORTRAN-TO-LISP|::|UI| |FORTRAN-TO-LISP|::|UR|
   |FORTRAN-TO-LISP|::|W|)
  (|COMMON-LISP|::|DECLARE|
   (|COMMON-LISP|::|TYPE|
    (|COMMON-LISP|::|ARRAY| |F2CL-LIB|::|INTEGER4| (|COMMON-LISP|::|*|))
    |FORTRAN-TO-LISP|::|NEED|)
   (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
    |FORTRAN-TO-LISP|::|F|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|NF|
    |FORTRAN-TO-LISP|::|N|)
   (|COMMON-LISP|::|TYPE|
    (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT| (|COMMON-LISP|::|*|))
    |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|RP| |FORTRAN-TO-LISP|::|R|
    |FORTRAN-TO-LISP|::|XN|)
   (|COMMON-LISP|::|TYPE|
    (|COMMON-LISP|::|ARRAY| |F2CL-LIB|::|INTEGER4| (|COMMON-LISP|::|*|))
    |FORTRAN-TO-LISP|::|UI|)
   (|COMMON-LISP|::|TYPE|
    (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT| (|COMMON-LISP|::|*|))
    |FORTRAN-TO-LISP|::|UR|))
  (|F2CL-LIB|::|WITH-MULTI-ARRAY-DATA|
   ((|FORTRAN-TO-LISP|::|UR| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|UR-%DATA%| |FORTRAN-TO-LISP|::|UR-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|UI| |F2CL-LIB|::|INTEGER4|
     |FORTRAN-TO-LISP|::|UI-%DATA%| |FORTRAN-TO-LISP|::|UI-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|XN| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|XN-%DATA%| |FORTRAN-TO-LISP|::|XN-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|R| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|R-%DATA%| |FORTRAN-TO-LISP|::|R-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|RP| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|RP-%DATA%| |FORTRAN-TO-LISP|::|RP-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|W| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|W-%DATA%| |FORTRAN-TO-LISP|::|W-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|NEED| |F2CL-LIB|::|INTEGER4|
     |FORTRAN-TO-LISP|::|NEED-%DATA%| |FORTRAN-TO-LISP|::|NEED-%OFFSET%|))
   (|COMMON-LISP|::|PROG| ((|FORTRAN-TO-LISP|::|I| 0.))
    (|COMMON-LISP|::|DECLARE|
     (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|I|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|NEED-%DATA%| (1.) ((1. 2.))
       |FORTRAN-TO-LISP|::|NEED-%OFFSET%|)
      2.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL20|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|RLIMIT|
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|RLIMIT|
      (|FORTRAN-TO-LISP|::|DR7MDC| 5.)))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|F|
     (|FORTRAN-TO-LISP|::|DV2NRM| |FORTRAN-TO-LISP|::|N|
      |FORTRAN-TO-LISP|::|R|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|F| |FORTRAN-TO-LISP|::|RLIMIT|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL10|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|F|
     (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
      (|COMMON-LISP|::|EXPT| |FORTRAN-TO-LISP|::|F| 2.)))
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|)
    |FORTRAN-TO-LISP|::|LABEL10|
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|NF| 0.)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|)
    |FORTRAN-TO-LISP|::|LABEL20|
    (|F2CL-LIB|::|FDO|
     (|FORTRAN-TO-LISP|::|I| 1.
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
     ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|N|)
      |COMMON-LISP|::|NIL|)
     (|COMMON-LISP|::|TAGBODY|
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|RP-%DATA%|
        (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
        |FORTRAN-TO-LISP|::|RP-%OFFSET%|)
       |FORTRAN-TO-LISP|::|ONE|)
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
        (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|N|))
        |FORTRAN-TO-LISP|::|W-%OFFSET%|)
       |FORTRAN-TO-LISP|::|ONE|)
      |FORTRAN-TO-LISP|::|LABEL30|))
    |FORTRAN-TO-LISP|::|LABEL999|
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|END_LABEL|)
    |FORTRAN-TO-LISP|::|END_LABEL|
    (|COMMON-LISP|::|RETURN|
     (|COMMON-LISP|::|VALUES| |COMMON-LISP|::|NIL| |FORTRAN-TO-LISP|::|F|
      |COMMON-LISP|::|NIL| |FORTRAN-TO-LISP|::|NF| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|))))))

