#+clisp (setf CUSTOM:*floating-point-contagion-ansi* t)
#+clisp (setf CUSTOM:*default-float-format* 'double-float)

;; first compile all the files, then load, this should be commented
;; out during normal execution, but is useful for development
;(compile-file "sc-ipmc.lisp")

;;;;;;;;;;;;;;;;
;;; load-717
;;;
;;; this function will load the relevant code for running algorithm
;;; 717.  if a file is part of the 717 package but is not needed for
;;; estimation in HIPM, i have commented it out.
(defun load-717 () 
  (compile-file "toms/717/da7sst.lisp")
  (compile-file "toms/717/dd7tpr.lisp")
  (compile-file "toms/717/dd7up5.lisp")
#-allegro  (compile-file "toms/717/dg7itb.lisp")
  (compile-file "toms/717/dg7qsb.lisp")
  (compile-file "toms/717/dg7qts.lisp")
  (compile-file "toms/717/dglfb.lisp")
  (compile-file "toms/717/dh2rfa.lisp")
  (compile-file "toms/717/dh2rfg.lisp")
#-allegro  (compile-file "toms/717/ditsum.lisp")
  (compile-file "toms/717/divset.lisp")
  (compile-file "toms/717/dl7itv.lisp")
  (compile-file "toms/717/dl7ivm.lisp")
  (compile-file "toms/717/dl7sqr.lisp")
  (compile-file "toms/717/dl7srt.lisp")
  (compile-file "toms/717/dl7svn.lisp")
  (compile-file "toms/717/dl7svx.lisp")
  (compile-file "toms/717/dl7tvm.lisp")
  (compile-file "toms/717/dl7vml.lisp")
  (compile-file "toms/717/dmdc.lisp")
#-allegro  (compile-file "toms/717/dparck.lisp")
  (compile-file "toms/717/dq7adr.lisp")
  (compile-file "toms/717/dq7rsh.lisp")
  (compile-file "toms/717/drglgb.lisp")
  (compile-file "toms/717/drldst.lisp")
  (compile-file "toms/717/ds7bqn.lisp")
  (compile-file "toms/717/ds7dmp.lisp")
  (compile-file "toms/717/ds7ipr.lisp")
  (compile-file "toms/717/ds7lup.lisp")
  (compile-file "toms/717/ds7lvm.lisp")
  (compile-file "toms/717/dv2axy.lisp")
  (compile-file "toms/717/dv2nrm.lisp")
  (compile-file "toms/717/dv7cpy.lisp")
  (compile-file "toms/717/dv7dfl.lisp")
  (compile-file "toms/717/dv7ipr.lisp")
  (compile-file "toms/717/dv7scl.lisp")
  (compile-file "toms/717/dv7scp.lisp")
  (compile-file "toms/717/dv7shf.lisp")
  (compile-file "toms/717/dv7vmp.lisp")
  (compile-file "toms/717/i7copy.lisp")
  (compile-file "toms/717/i7pnvr.lisp")
  (compile-file "toms/717/i7shft.lisp")
  (compile-file "toms/717/stopx.lisp")
)
(defun load-CVODE ()
(compile-file "build_equations.lisp")
(compile-file "combine_equations.lisp")
(compile-file "general_make_sys.lisp")
(compile-file "cvode_make_sys.lisp")

#+(and clisp (not macos)) (compile-file "cvode_ffi_clisp.lisp")
#+allegro (compile-file "cvode_ffi_allegro.lisp")
#+cmu (compile-file "cvode_ffi_cmucl.lisp")

(compile-file "cvode.lisp")
(compile-file "pe_general.lisp")
(compile-file "pe_obj_funcs.lisp")
(compile-file "f2cl/f2cl0.l")
(compile-file "f2cl/macros.l")
)
(defun load-SCIPM ()
(compile-file "global.lisp")
(compile-file "general.lisp")
(compile-file "utils.lisp")
(compile-file "data.lisp")
(compile-file "gp.lisp")
(compile-file "model.lisp")
(compile-file "walksat.lisp")
(compile-file "symbols.lisp")
(compile-file "cnf.lisp")
(compile-file "library.lisp")
(compile-file "structure-generator.lisp")
(compile-file "constraint.lisp")
(compile-file "logic-generator.lisp")
(compile-file "file-list.lisp")
(compile-file "interface.lisp")
(compile-file "model-output-search.lisp")
)

(defun load-misc ()
(compile-file "rk.lisp")
(compile-file "pe_random.lisp")
(compile-file "pe_717.lisp")
)
#+(and allegro dlfcn) (load "./cvode_interface.so")
#+(and allegro dlmac) (load "./cvode_c_interface.dylib")
#+cmu (extensions:load-foreign "./cvode_interface.so")

(load-SCIPM)
(load-CVODE)
#-allegro (load-717)
(load-misc)
