#+clisp (setf CUSTOM:*floating-point-contagion-ansi* t)
#+clisp (setf CUSTOM:*default-float-format* 'double-float)

;; first compile all the files, then load, this should be commented
;; out during normal execution, but is useful for development
;(load "sc-ipmc")

;;;;;;;;;;;;;;;;
;;; load-717
;;;
;;; this function will load the relevant code for running algorithm
;;; 717.  if a file is part of the 717 package but is not needed for
;;; estimation in HIPM, i have commented it out.
(defun load-717 () 
  ;;  (load "toms/717/alnorm")
  (load "toms/717/da7sst")
  ;;  (load "toms/717/dd7mlp")
  (load "toms/717/dd7tpr")
  (load "toms/717/dd7up5")
  ;;  (load "toms/717/df7dhb")
  ;;  (load "toms/717/df7hes")
  ;;  (load "toms/717/dg2lrd")
  (load "toms/717/dg7itb")
  ;;  (load "toms/717/dg7lit")
  (load "toms/717/dg7qsb")
  (load "toms/717/dg7qts")
  (load "toms/717/dglfb")
  ;;  (load "toms/717/dglf")
  ;;  (load "toms/717/dglgb")
  ;;  (load "toms/717/dglg")
  (load "toms/717/dh2rfa")
  (load "toms/717/dh2rfg")
  (load "toms/717/ditsum")
  (load "toms/717/divset")
  (load "toms/717/dl7itv")
  (load "toms/717/dl7ivm")
  ;;  (load "toms/717/dl7msb")
  ;;  (load "toms/717/dl7mst")
  ;;  (load "toms/717/dl7nvr")
  (load "toms/717/dl7sqr")
  (load "toms/717/dl7srt")
  (load "toms/717/dl7svn")
  (load "toms/717/dl7svx")
  ;;  (load "toms/717/dl7tsq")
  (load "toms/717/dl7tvm")
  (load "toms/717/dl7vml")
  (load "toms/717/dmdc")
  ;;  (load "toms/717/dn3rdp")
  ;;  (load "toms/717/do7prd")
  (load "toms/717/dparck")
  (load "toms/717/dq7adr")
  (load "toms/717/dq7rsh")
  (load "toms/717/drglgb")
  ;;  (load "toms/717/drglg")
  (load "toms/717/drldst")
  (load "toms/717/ds7bqn")
  (load "toms/717/ds7dmp")
  (load "toms/717/ds7ipr")
  (load "toms/717/ds7lup")
  (load "toms/717/ds7lvm")
  (load "toms/717/dv2axy")
  (load "toms/717/dv2nrm")
  (load "toms/717/dv7cpy")
  (load "toms/717/dv7dfl")
  (load "toms/717/dv7ipr")
  (load "toms/717/dv7scl")
  (load "toms/717/dv7scp")
  (load "toms/717/dv7shf")
  (load "toms/717/dv7vmp")
  ;;  (load "toms/717/dvsum")
  (load "toms/717/i7copy")
  (load "toms/717/i7pnvr")
  (load "toms/717/i7shft")
  ;;  (load "toms/717/madrj")
  ;;  (load "toms/717/madsenb")
  ;;  (load "toms/717/madsen")
  ;;  (load "toms/717/mecdf")
  ;;  (load "toms/717/phi")
  ;;  (load "toms/717/rhols")
  (load "toms/717/stopx")
)
(defun load-CVODE ()
(load "build_equations")
(load "combine_equations")
(load "general_make_sys")
(load "cvode_make_sys")

#+(and clisp (not macos)) (load "cvode_ffi_clisp.lisp")
#+allegro (load "cvode_ffi_allegro")
#+cmu (load "cvode_ffi_cmucl")

(load "cvode")
(load "pe_general")
(load "pe_obj_funcs")
(load "f2cl/f2cl0.l")
(load "f2cl/macros.l")
)
(defun load-SCIPM ()
(load "global")
(load "general")
(load "utils")
(load "data")
(load "gp")
(load "model")
;;(load "item")
(load "walksat")
(load "symbols")
(load "cnf")
(load "library")
;;(load "solution-generator")
(load "structure-generator")
;;(load "process-set")
(load "constraint")
;;(load "logic")
(load "logic-generator")
;;(load "search")
(load "file-list")
(load "model-output-search")
)

(defun load-misc ()
(load "rk")
(load "pe_random")
(load "pe_717")
)
#+(and allegro dlfcn) (load "./cvode_interface.so")
#+(and allegro dlmac) (load "./cvode_c_interface.dylib")
#+cmu (extensions:load-foreign "./cvode_interface.so")

(load-SCIPM)
(load-CVODE)
(load-717)
(load-misc)
