#+clisp (setf CUSTOM:*floating-point-contagion-ansi* t)
#+clisp (setf CUSTOM:*default-float-format* 'double-float)

;;;;;;;;;;;;;;;;
;;; load-717
;;;
;;; this function will load the relevant code for running algorithm
;;; 717.  if a file is part of the 717 package but is not needed for
;;; estimation in HIPM, i have commented it out.
(defun load-717 () 
  ;;  (load "lite/toms/717/alnorm")
  (load "lite/toms/717/da7sst")
  ;;  (load "lite/toms/717/dd7mlp")
  (load "lite/toms/717/dd7tpr")
  (load "lite/toms/717/dd7up5")
  ;;  (load "lite/toms/717/df7dhb")
  ;;  (load "lite/toms/717/df7hes")
  ;;  (load "lite/toms/717/dg2lrd")
  (load "lite/toms/717/dg7itb")
  ;;  (load "lite/toms/717/dg7lit")
  (load "lite/toms/717/dg7qsb")
  (load "lite/toms/717/dg7qts")
  (load "lite/toms/717/dglfb")
  ;;  (load "lite/toms/717/dglf")
  ;;  (load "lite/toms/717/dglgb")
  ;;  (load "lite/toms/717/dglg")
  (load "lite/toms/717/dh2rfa")
  (load "lite/toms/717/dh2rfg")
  (load "lite/toms/717/ditsum")
  (load "lite/toms/717/divset")
  (load "lite/toms/717/dl7itv")
  (load "lite/toms/717/dl7ivm")
  ;;  (load "lite/toms/717/dl7msb")
  ;;  (load "lite/toms/717/dl7mst")
  ;;  (load "lite/toms/717/dl7nvr")
  (load "lite/toms/717/dl7sqr")
  (load "lite/toms/717/dl7srt")
  (load "lite/toms/717/dl7svn")
  (load "lite/toms/717/dl7svx")
  ;;  (load "lite/toms/717/dl7tsq")
  (load "lite/toms/717/dl7tvm")
  (load "lite/toms/717/dl7vml")
  (load "lite/toms/717/dmdc")
  ;;  (load "lite/toms/717/dn3rdp")
  ;;  (load "lite/toms/717/do7prd")
  (load "lite/toms/717/dparck")
  (load "lite/toms/717/dq7adr")
  (load "lite/toms/717/dq7rsh")
  (load "lite/toms/717/drglgb")
  ;;  (load "lite/toms/717/drglg")
  (load "lite/toms/717/drldst")
  (load "lite/toms/717/ds7bqn")
  (load "lite/toms/717/ds7dmp")
  (load "lite/toms/717/ds7ipr")
  (load "lite/toms/717/ds7lup")
  (load "lite/toms/717/ds7lvm")
  (load "lite/toms/717/dv2axy")
  (load "lite/toms/717/dv2nrm")
  (load "lite/toms/717/dv7cpy")
  (load "lite/toms/717/dv7dfl")
  (load "lite/toms/717/dv7ipr")
  (load "lite/toms/717/dv7scl")
  (load "lite/toms/717/dv7scp")
  (load "lite/toms/717/dv7shf")
  (load "lite/toms/717/dv7vmp")
  ;;  (load "lite/toms/717/dvsum")
  (load "lite/toms/717/i7copy")
  (load "lite/toms/717/i7pnvr")
  (load "lite/toms/717/i7shft")
  ;;  (load "lite/toms/717/madrj")
  ;;  (load "lite/toms/717/madsenb")
  ;;  (load "lite/toms/717/madsen")
  ;;  (load "lite/toms/717/mecdf")
  ;;  (load "lite/toms/717/phi")
  ;;  (load "lite/toms/717/rhols")
  (load "lite/toms/717/stopx")
)
(defun load-CVODE ()
(load "lite/build_equations")
(load "lite/combine_equations")
(load "lite/general_make_sys")
(load "lite/cvode_make_sys")

#+clisp (load "lite/cvode_ffi_clisp")
#+allegro (load "lite/cvode_ffi_allegro")
#+cmu (load "lite/cvode_ffi_cmucl")

(load "lite/cvode")
(load "lite/pe_general")
(load "lite/pe_obj_funcs")
(load "lite/f2cl/f2cl0.l")
(load "lite/f2cl/macros.l")
)
(defun load-SCIPM ()
(load "lite/global")
(load "lite/general")
(load "lite/utils")
(load "lite/data")
(load "lite/gp")
(load "lite/model")
(load "lite/item")
(load "lite/walksat")
(load "lite/symbols")
(load "lite/cnf")
(load "lite/library")
(load "lite/solution-generator")
(load "lite/process-set")
(load "lite/logic")
(load "lite/search")
(load "lite/model-output-search")
)

(defun load-misc ()
(load "lite/rk")
(load "lite/pe_random")
(load "lite/pe_717")
)
#+allegro (load "lite/cvode_interface.so")
#+cmu (extensions:load-foreign "lite/cvode_interface.so")

(load-SCIPM)
(load-CVODE)
(load-717)
(load-misc)
