#+clisp (setf CUSTOM:*floating-point-contagion-ansi* t)
#+clisp (setf CUSTOM:*default-float-format* 'double-float)

;; first compile all the files, then load, this should be commented
;; out during normal execution, but is useful for development
;(load "sc-ipmc.lisp")

;;;;;;;;;;;;;;;;
;;; load-717
;;;
;;; this function will load the relevant code for running algorithm
;;; 717.  if a file is part of the 717 package but is not needed for
;;; estimation in HIPM, i have commented it out.
(defun load-717 () 
  ;;  (load "toms/717/alnorm")
  (load "toms/717/da7sst.lisp")
  ;;  (load "toms/717/dd7mlp.lisp")
  (load "toms/717/dd7tpr.lisp")
  (load "toms/717/dd7up5.lisp")
  ;;  (load "toms/717/df7dhb.lisp")
  ;;  (load "toms/717/df7hes.lisp")
  ;;  (load "toms/717/dg2lrd.lisp")
  (load "toms/717/dg7itb.lisp")
  ;;  (load "toms/717/dg7lit.lisp")
  (load "toms/717/dg7qsb.lisp")
  (load "toms/717/dg7qts.lisp")
  (load "toms/717/dglfb.lisp")
  ;;  (load "toms/717/dglf.lisp")
  ;;  (load "toms/717/dglgb.lisp")
  ;;  (load "toms/717/dglg.lisp")
  (load "toms/717/dh2rfa.lisp")
  (load "toms/717/dh2rfg.lisp")
  (load "toms/717/ditsum.lisp")
  (load "toms/717/divset.lisp")
  (load "toms/717/dl7itv.lisp")
  (load "toms/717/dl7ivm.lisp")
  ;;  (load "toms/717/dl7msb.lisp")
  ;;  (load "toms/717/dl7mst.lisp")
  ;;  (load "toms/717/dl7nvr.lisp")
  (load "toms/717/dl7sqr.lisp")
  (load "toms/717/dl7srt.lisp")
  (load "toms/717/dl7svn.lisp")
  (load "toms/717/dl7svx.lisp")
  ;;  (load "toms/717/dl7tsq.lisp")
  (load "toms/717/dl7tvm.lisp")
  (load "toms/717/dl7vml.lisp")
  (load "toms/717/dmdc.lisp")
  ;;  (load "toms/717/dn3rdp.lisp")
  ;;  (load "toms/717/do7prd.lisp")
  (load "toms/717/dparck.lisp")
  (load "toms/717/dq7adr.lisp")
  (load "toms/717/dq7rsh.lisp")
  (load "toms/717/drglgb.lisp")
  ;;  (load "toms/717/drglg.lisp")
  (load "toms/717/drldst.lisp")
  (load "toms/717/ds7bqn.lisp")
  (load "toms/717/ds7dmp.lisp")
  (load "toms/717/ds7ipr.lisp")
  (load "toms/717/ds7lup.lisp")
  (load "toms/717/ds7lvm.lisp")
  (load "toms/717/dv2axy.lisp")
  (load "toms/717/dv2nrm.lisp")
  (load "toms/717/dv7cpy.lisp")
  (load "toms/717/dv7dfl.lisp")
  (load "toms/717/dv7ipr.lisp")
  (load "toms/717/dv7scl.lisp")
  (load "toms/717/dv7scp.lisp")
  (load "toms/717/dv7shf.lisp")
  (load "toms/717/dv7vmp.lisp")
  ;;  (load "toms/717/dvsum.lisp")
  (load "toms/717/i7copy.lisp")
  (load "toms/717/i7pnvr.lisp")
  (load "toms/717/i7shft.lisp")
  ;;  (load "toms/717/madrj.lisp")
  ;;  (load "toms/717/madsenb.lisp")
  ;;  (load "toms/717/madsen.lisp")
  ;;  (load "toms/717/mecdf.lisp")
  ;;  (load "toms/717/phi.lisp")
  ;;  (load "toms/717/rhols.lisp")
  (load "toms/717/stopx.lisp")
)
(defun load-CVODE ()
(load "build_equations.lisp")
(load "combine_equations.lisp")
(load "general_make_sys.lisp")
(load "cvode_make_sys.lisp")

#+(and clisp (not macos)) (load "cvode_ffi_clisp.lisp")
#+allegro (load "cvode_ffi_allegro.lisp")
#+cmu (load "cvode_ffi_cmucl.lisp")

(load "cvode.lisp")
(load "pe_general.lisp")
(load "pe_obj_funcs.lisp")
(load "f2cl/f2cl0.l")
(load "f2cl/macros.l")
)
(defun load-SCIPM ()
(load "global.lisp")
(load "general.lisp")
(load "utils.lisp")
(load "data.lisp")
(load "gp.lisp")
(load "model.lisp")
;;(load "item.lisp")
(load "walksat.lisp")
(load "symbols.lisp")
(load "cnf.lisp")
(load "library.lisp")
;;(load "solution-generator.lisp")
(load "structure-generator.lisp")
;;(load "process-set.lisp")
(load "constraint.lisp")
;;(load "logic.lisp")
(load "logic-generator.lisp")
;;(load "search.lisp")
(load "file-list.lisp")
(load "interface.lisp")
(load "model-output-search.lisp")
)

(defun load-misc ()
(load "rk.lisp")
(load "pe_random.lisp")
(load "pe_717.lisp")
)
#+(and allegro dlfcn) (load "./cvode_interface.so")
#+(and allegro dlmac) (load "./cvode_c_interface.dylib")
#+cmu (extensions:load-foreign "./cvode_interface.so")

(load-SCIPM)
(load-CVODE)
(load-717)
(load-misc)
