(in-package :scipm)

(defun test-run (instance-library-name)
  (let* ((current-instances (instance-library instance-library-name))
	 (current-library (instance-library-generic-library current-instances))
	 (data-filenames (instance-library-data-files current-instances))
	 (entities (instance-library-entities current-instances)))
    (format t "Setting variables...~%")
    (setf *test-data-sets* (mapcar #'read-data-from-file data-filenames))
    (setf *test-instances* current-instances)
    (setf *test-library* current-library)
    (setf *test-filenames* data-filenames)
    (setf *test-entities* entities)
    (format t "Calculating dispersions...~%")
    (calculate-dispersions *test-data-sets*)
    (format t "Generating...~%")
    (let ((generator (get-generator entities current-library :cnf? 1)))
      (setf *test-generator* generator)
      (format t "Generated...~%")
      (flet ((get-model (nth)
	       (setf model (walksat-structure generator :idx nth))
	       