;;; Compiled by f2cl version 2.0 beta Date: 2006/05/05 20:28:21 
;;; Using Lisp CLISP 2.38 (2006-01-24) (built on guru.build.karan.org)
;;; Options: ((:prune-labels nil) (:auto-save t) (:relaxed-array-decls t)
;;;  (:coerce-assigns :as-needed) (:array-type ':array) (:array-slicing t)
;;;  (:declare-common nil) (:float-format single-float))

(in-package :common-lisp-user)


 (|COMMON-LISP|::|DEFUN| |FORTRAN-TO-LISP|::|DA7SST|
  (|FORTRAN-TO-LISP|::|IV| |FORTRAN-TO-LISP|::|LIV| |FORTRAN-TO-LISP|::|LV|
   |FORTRAN-TO-LISP|::|V|)
  (|COMMON-LISP|::|DECLARE|
   (|COMMON-LISP|::|TYPE|
    (|COMMON-LISP|::|ARRAY| |F2CL-LIB|::|INTEGER4| (|COMMON-LISP|::|*|))
    |FORTRAN-TO-LISP|::|IV|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|LV|
    |FORTRAN-TO-LISP|::|LIV|)
   (|COMMON-LISP|::|TYPE|
    (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT| (|COMMON-LISP|::|*|))
    |FORTRAN-TO-LISP|::|V|)
   (|COMMON-LISP|::|IGNORABLE| |FORTRAN-TO-LISP|::|LV| |FORTRAN-TO-LISP|::|LIV|))
(|COMMON-LISP|::|LET*|
 ((|FORTRAN-TO-LISP|::|HALF| #1=0.5d0) (|FORTRAN-TO-LISP|::|ONE| #2=1.0d0)
  (|FORTRAN-TO-LISP|::|ONEP2| #3=1.2d0) (|FORTRAN-TO-LISP|::|TWO| #4=2.0d0)
  (|FORTRAN-TO-LISP|::|ZERO| #5=0.0d0) (|FORTRAN-TO-LISP|::|IRC| 29.)
  (|FORTRAN-TO-LISP|::|MLSTGD| 32.) (|FORTRAN-TO-LISP|::|MODEL| 5.)
  (|FORTRAN-TO-LISP|::|NFCALL| 6.) (|FORTRAN-TO-LISP|::|NFGCAL| 7.)
  (|FORTRAN-TO-LISP|::|RADINC| 8.) (|FORTRAN-TO-LISP|::|RESTOR| 9.)
  (|FORTRAN-TO-LISP|::|STAGE| 10.) (|FORTRAN-TO-LISP|::|STGLIM| 11.)
  (|FORTRAN-TO-LISP|::|SWITCH| 12.) (|FORTRAN-TO-LISP|::|TOOBIG| 2.)
  (|FORTRAN-TO-LISP|::|XIRC| 13.) (|FORTRAN-TO-LISP|::|AFCTOL| 31.)
  (|FORTRAN-TO-LISP|::|DECFAC| 22.) (|FORTRAN-TO-LISP|::|DSTNRM| 2.)
  (|FORTRAN-TO-LISP|::|DST0| 3.) (|FORTRAN-TO-LISP|::|DSTSAV| 18.)
  (|FORTRAN-TO-LISP|::|F| 10.) (|FORTRAN-TO-LISP|::|FDIF| 11.)
  (|FORTRAN-TO-LISP|::|FLSTGD| 12.) (|FORTRAN-TO-LISP|::|F0| 13.)
  (|FORTRAN-TO-LISP|::|GTSLST| 14.) (|FORTRAN-TO-LISP|::|GTSTEP| 4.)
  (|FORTRAN-TO-LISP|::|INCFAC| 23.) (|FORTRAN-TO-LISP|::|LMAXS| 36.)
  (|FORTRAN-TO-LISP|::|NREDUC| 6.) (|FORTRAN-TO-LISP|::|PLSTGD| 15.)
  (|FORTRAN-TO-LISP|::|PREDUC| 7.) (|FORTRAN-TO-LISP|::|RADFAC| 16.)
  (|FORTRAN-TO-LISP|::|RDFCMN| 24.) (|FORTRAN-TO-LISP|::|RDFCMX| 25.)
  (|FORTRAN-TO-LISP|::|RELDX| 17.) (|FORTRAN-TO-LISP|::|RFCTOL| 32.)
  (|FORTRAN-TO-LISP|::|SCTOL| 37.) (|FORTRAN-TO-LISP|::|STPPAR| 5.)
  (|FORTRAN-TO-LISP|::|TUNER1| 26.) (|FORTRAN-TO-LISP|::|TUNER2| 27.)
  (|FORTRAN-TO-LISP|::|TUNER3| 28.) (|FORTRAN-TO-LISP|::|XCTOL| 33.)
  (|FORTRAN-TO-LISP|::|XFTOL| 34.))
 (|COMMON-LISP|::|DECLARE|
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #1# #1#)
   |FORTRAN-TO-LISP|::|HALF|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #2# #2#)
   |FORTRAN-TO-LISP|::|ONE|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #3# #3#)
   |FORTRAN-TO-LISP|::|ONEP2|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #4# #4#)
   |FORTRAN-TO-LISP|::|TWO|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #5# #5#)
   |FORTRAN-TO-LISP|::|ZERO|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 29. 29.)
   |FORTRAN-TO-LISP|::|IRC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 32. 32.)
   |FORTRAN-TO-LISP|::|MLSTGD|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 5. 5.)
   |FORTRAN-TO-LISP|::|MODEL|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 6. 6.)
   |FORTRAN-TO-LISP|::|NFCALL|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 7. 7.)
   |FORTRAN-TO-LISP|::|NFGCAL|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 8. 8.)
   |FORTRAN-TO-LISP|::|RADINC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 9. 9.)
   |FORTRAN-TO-LISP|::|RESTOR|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 10. 10.)
   |FORTRAN-TO-LISP|::|STAGE|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 11. 11.)
   |FORTRAN-TO-LISP|::|STGLIM|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 12. 12.)
   |FORTRAN-TO-LISP|::|SWITCH|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 2. 2.)
   |FORTRAN-TO-LISP|::|TOOBIG|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 13. 13.)
   |FORTRAN-TO-LISP|::|XIRC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 31. 31.)
   |FORTRAN-TO-LISP|::|AFCTOL|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 22. 22.)
   |FORTRAN-TO-LISP|::|DECFAC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 2. 2.)
   |FORTRAN-TO-LISP|::|DSTNRM|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 3. 3.)
   |FORTRAN-TO-LISP|::|DST0|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 18. 18.)
   |FORTRAN-TO-LISP|::|DSTSAV|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 10. 10.)
   |FORTRAN-TO-LISP|::|F|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 11. 11.)
   |FORTRAN-TO-LISP|::|FDIF|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 12. 12.)
   |FORTRAN-TO-LISP|::|FLSTGD|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 13. 13.)
   |FORTRAN-TO-LISP|::|F0|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 14. 14.)
   |FORTRAN-TO-LISP|::|GTSLST|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 4. 4.)
   |FORTRAN-TO-LISP|::|GTSTEP|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 23. 23.)
   |FORTRAN-TO-LISP|::|INCFAC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 36. 36.)
   |FORTRAN-TO-LISP|::|LMAXS|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 6. 6.)
   |FORTRAN-TO-LISP|::|NREDUC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 15. 15.)
   |FORTRAN-TO-LISP|::|PLSTGD|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 7. 7.)
   |FORTRAN-TO-LISP|::|PREDUC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 16. 16.)
   |FORTRAN-TO-LISP|::|RADFAC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 24. 24.)
   |FORTRAN-TO-LISP|::|RDFCMN|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 25. 25.)
   |FORTRAN-TO-LISP|::|RDFCMX|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 17. 17.)
   |FORTRAN-TO-LISP|::|RELDX|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 32. 32.)
   |FORTRAN-TO-LISP|::|RFCTOL|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 37. 37.)
   |FORTRAN-TO-LISP|::|SCTOL|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 5. 5.)
   |FORTRAN-TO-LISP|::|STPPAR|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 26. 26.)
   |FORTRAN-TO-LISP|::|TUNER1|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 27. 27.)
   |FORTRAN-TO-LISP|::|TUNER2|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 28. 28.)
   |FORTRAN-TO-LISP|::|TUNER3|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 33. 33.)
   |FORTRAN-TO-LISP|::|XCTOL|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 34. 34.)
   |FORTRAN-TO-LISP|::|XFTOL|))

;(incf *da7sst*)

  (|F2CL-LIB|::|WITH-MULTI-ARRAY-DATA|
   ((|FORTRAN-TO-LISP|::|V| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|V-%DATA%| |FORTRAN-TO-LISP|::|V-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|IV| |F2CL-LIB|::|INTEGER4|
     |FORTRAN-TO-LISP|::|IV-%DATA%| |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
   (|COMMON-LISP|::|PROG|
    ((|FORTRAN-TO-LISP|::|EMAX| #5#) (|FORTRAN-TO-LISP|::|EMAXS| #5#)
     (|FORTRAN-TO-LISP|::|GTS| #5#) (|FORTRAN-TO-LISP|::|RFAC1| #5#)
     (|FORTRAN-TO-LISP|::|XMAX| #5#) (|FORTRAN-TO-LISP|::|I| 0.)
     (|FORTRAN-TO-LISP|::|NFC| 0.)
     (|FORTRAN-TO-LISP|::|GOODX| |COMMON-LISP|::|NIL|))
    (|COMMON-LISP|::|DECLARE|
     (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
      |FORTRAN-TO-LISP|::|XMAX| |FORTRAN-TO-LISP|::|RFAC1|
      |FORTRAN-TO-LISP|::|GTS| |FORTRAN-TO-LISP|::|EMAXS|
      |FORTRAN-TO-LISP|::|EMAX|)
     (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|NFC|
      |FORTRAN-TO-LISP|::|I|)
     (|COMMON-LISP|::|TYPE| |F2CL-LIB|::|LOGICAL| |FORTRAN-TO-LISP|::|GOODX|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|NFC|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|NFCALL|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|SWITCH|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     0.)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     0.)
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|RFAC1| |FORTRAN-TO-LISP|::|ONE|)
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|GOODX| |F2CL-LIB|::|%TRUE%|)
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|I|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|AND| (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|I| 1.)
      (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|I| 12.))
     (|F2CL-LIB|::|COMPUTED-GOTO|
      (|FORTRAN-TO-LISP|::|LABEL20| |FORTRAN-TO-LISP|::|LABEL30|
       |FORTRAN-TO-LISP|::|LABEL10| |FORTRAN-TO-LISP|::|LABEL10|
       |FORTRAN-TO-LISP|::|LABEL40| |FORTRAN-TO-LISP|::|LABEL280|
       |FORTRAN-TO-LISP|::|LABEL220| |FORTRAN-TO-LISP|::|LABEL220|
       |FORTRAN-TO-LISP|::|LABEL220| |FORTRAN-TO-LISP|::|LABEL220|
       |FORTRAN-TO-LISP|::|LABEL220| |FORTRAN-TO-LISP|::|LABEL170|)
      |FORTRAN-TO-LISP|::|I|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     13.)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|)
    |FORTRAN-TO-LISP|::|LABEL10|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|STAGE|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     1.)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RADINC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     0.)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|FLSTGD|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|F0|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|TOOBIG|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      0.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL110|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|STAGE|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     -1.)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|XIRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     |FORTRAN-TO-LISP|::|I|)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL60|)
    |FORTRAN-TO-LISP|::|LABEL20|
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|/=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|MODEL|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|MLSTGD|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL30|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|STAGE|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|STGLIM|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RADINC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     -1.)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL110|)
    |FORTRAN-TO-LISP|::|LABEL30|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|STAGE|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|INT-ADD|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|STAGE|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      1.))
    |FORTRAN-TO-LISP|::|LABEL40|
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|STAGE|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      0.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL50|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|/=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|TOOBIG|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      0.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL60|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|STAGE|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|INT-SUB|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|STAGE|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|I|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|XIRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|F2CL-LIB|::|COMPUTED-GOTO|
     (|FORTRAN-TO-LISP|::|LABEL20| |FORTRAN-TO-LISP|::|LABEL30|
      |FORTRAN-TO-LISP|::|LABEL110| |FORTRAN-TO-LISP|::|LABEL110|
      |FORTRAN-TO-LISP|::|LABEL70|)
     |FORTRAN-TO-LISP|::|I|)
    |FORTRAN-TO-LISP|::|LABEL50|
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|TOOBIG|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      0.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL70|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|RADINC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      0.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL80|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|STAGE|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|INT-SUB|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|STAGE|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|XIRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    |FORTRAN-TO-LISP|::|LABEL60|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|RADFAC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DECFAC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RADINC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|INT-SUB|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|RADINC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      1.))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     5.)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     1.)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|)
    |FORTRAN-TO-LISP|::|LABEL70|
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|F|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|FLSTGD|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL110|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|MODEL|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|MLSTGD|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL80|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|MODEL|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|MLSTGD|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|SWITCH|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     1.)
    |FORTRAN-TO-LISP|::|LABEL80|
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|FLSTGD|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|F0|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL110|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     1.)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%| (|FORTRAN-TO-LISP|::|F|)
      ((1. |FORTRAN-TO-LISP|::|LV|)) |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|FLSTGD|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|PLSTGD|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|GTSTEP|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|GTSLST|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|SWITCH|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      0.)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|RFAC1|
      (|COMMON-LISP|::|/|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DSTSAV|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|))))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DSTSAV|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|NFC|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|NFGCAL|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|GOODX| |F2CL-LIB|::|%FALSE%|)
    |FORTRAN-TO-LISP|::|LABEL110|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|FDIF|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|COMMON-LISP|::|-|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|F0|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|F|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|FDIF|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|*|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|TUNER2|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL140|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|RADINC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      0.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL140|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|F|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|F0|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL120|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|MLSTGD|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|MODEL|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|FLSTGD|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%| (|FORTRAN-TO-LISP|::|F|)
      ((1. |FORTRAN-TO-LISP|::|LV|)) |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%| (|FORTRAN-TO-LISP|::|F|)
      ((1. |FORTRAN-TO-LISP|::|LV|)) |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|F0|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     1.)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL130|)
    |FORTRAN-TO-LISP|::|LABEL120|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|NFGCAL|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     |FORTRAN-TO-LISP|::|NFC|)
    |FORTRAN-TO-LISP|::|LABEL130|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     1.)
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|STAGE|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|STGLIM|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL160|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     5.)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RADINC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|INT-SUB|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|RADINC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      1.))
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL160|)
    |FORTRAN-TO-LISP|::|LABEL140|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|NFGCAL|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     |FORTRAN-TO-LISP|::|NFC|)
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|RFAC1| |FORTRAN-TO-LISP|::|ONE|)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DSTSAV|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|FDIF|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|*|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|TUNER1|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL190|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|STAGE|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|STGLIM|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL150|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     2.)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL160|)
    |FORTRAN-TO-LISP|::|LABEL150|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     4.)
    |FORTRAN-TO-LISP|::|LABEL160|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|XIRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|EMAX|
     (|COMMON-LISP|::|+|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|GTSTEP|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|FDIF|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|RADFAC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF| |FORTRAN-TO-LISP|::|RFAC1|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|EMAX|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|GTSTEP|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|RADFAC|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|RFAC1|
       (|COMMON-LISP|::|MAX|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|RDFCMN|) ((1. |FORTRAN-TO-LISP|::|LV|))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|)
        (|COMMON-LISP|::|/|
         (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
          (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
           (|FORTRAN-TO-LISP|::|GTSTEP|) ((1. |FORTRAN-TO-LISP|::|LV|))
           |FORTRAN-TO-LISP|::|V-%OFFSET%|))
         |FORTRAN-TO-LISP|::|EMAX|)))))
    |FORTRAN-TO-LISP|::|LABEL170|
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|RELDX|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|XFTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL180|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|XIRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|F|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|F0|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL200|))
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL230|)
    |FORTRAN-TO-LISP|::|LABEL180|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     12.)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL240|)
    |FORTRAN-TO-LISP|::|LABEL190|
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|FDIF|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|*|
       (|COMMON-LISP|::|-|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|TUNER3|) ((1. |FORTRAN-TO-LISP|::|LV|))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|))
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|GTSTEP|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL210|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|RADINC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      0.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL210|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      1.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL210|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|RADFAC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|RDFCMX|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|GTS|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|GTSTEP|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|FDIF|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|*|
       (|COMMON-LISP|::|-|
        (|COMMON-LISP|::|/| |FORTRAN-TO-LISP|::|HALF|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
          (|FORTRAN-TO-LISP|::|RADFAC|) ((1. |FORTRAN-TO-LISP|::|LV|))
          |FORTRAN-TO-LISP|::|V-%OFFSET%|))
        |FORTRAN-TO-LISP|::|ONE|)
       |FORTRAN-TO-LISP|::|GTS|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|RADFAC|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|MAX|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|INCFAC|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       (|COMMON-LISP|::|/|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF| |FORTRAN-TO-LISP|::|GTS|)
        (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|GTS|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
          (|FORTRAN-TO-LISP|::|FDIF|) ((1. |FORTRAN-TO-LISP|::|LV|))
          |FORTRAN-TO-LISP|::|V-%OFFSET%|))))))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     4.)
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|STPPAR|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL230|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|AND|
      (|COMMON-LISP|::|>=|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DST0|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|OR|
       (|COMMON-LISP|::|<|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|DST0|) ((1. |FORTRAN-TO-LISP|::|LV|))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|)
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|TWO|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
          (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
          |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
       (|COMMON-LISP|::|<|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|NREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|)
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|ONEP2|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
          (|FORTRAN-TO-LISP|::|FDIF|) ((1. |FORTRAN-TO-LISP|::|LV|))
          |FORTRAN-TO-LISP|::|V-%OFFSET%|)))))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL230|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     5.)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RADINC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|INT-ADD|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|RADINC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      1.))
    |FORTRAN-TO-LISP|::|LABEL200|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|FLSTGD|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%| (|FORTRAN-TO-LISP|::|F|)
      ((1. |FORTRAN-TO-LISP|::|LV|)) |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|MLSTGD|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|MODEL|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|/=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      1.)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      2.))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DSTSAV|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|NFGCAL|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     |FORTRAN-TO-LISP|::|NFC|)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|PLSTGD|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|GTSLST|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|GTSTEP|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL230|)
    |FORTRAN-TO-LISP|::|LABEL210|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|RADFAC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     |FORTRAN-TO-LISP|::|ONE|)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     3.)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL230|)
    |FORTRAN-TO-LISP|::|LABEL220|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|XIRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DSTSAV|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL240|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     12.)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL240|)
    |FORTRAN-TO-LISP|::|LABEL230|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|XIRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    |FORTRAN-TO-LISP|::|LABEL240|
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|AND|
      (|COMMON-LISP|::|=|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
        (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
        |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
       1.)
      (|COMMON-LISP|::|<|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|FLSTGD|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|F0|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      3.))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<|
      (|COMMON-LISP|::|ABS|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|F|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|))
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|AFCTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      10.))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>|
      (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|FDIF|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|))
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|EMAX|
     (|COMMON-LISP|::|*|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|RFCTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|ABS|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|F0|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|))))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|EMAXS|
     (|COMMON-LISP|::|*|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|SCTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|ABS|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|F0|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|))))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|AND|
      (|COMMON-LISP|::|<=|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|EMAXS|)
      (|COMMON-LISP|::|OR|
       (|COMMON-LISP|::|>|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|)
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|LMAXS|) ((1. |FORTRAN-TO-LISP|::|LV|))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|))
       (|COMMON-LISP|::|=|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|STPPAR|) ((1. |FORTRAN-TO-LISP|::|LV|))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|)
        |FORTRAN-TO-LISP|::|ZERO|)))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      11.))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DST0|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL250|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|I| 0.)
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|OR|
      (|COMMON-LISP|::|AND|
       (|COMMON-LISP|::|>|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|NREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|)
        |FORTRAN-TO-LISP|::|ZERO|)
       (|COMMON-LISP|::|<=|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|NREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|)
        |FORTRAN-TO-LISP|::|EMAX|))
      (|COMMON-LISP|::|AND|
       (|COMMON-LISP|::|=|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|NREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|)
        |FORTRAN-TO-LISP|::|ZERO|)
       (|COMMON-LISP|::|=|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|)
        |FORTRAN-TO-LISP|::|ZERO|)))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|I| 2.))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|AND|
      (|COMMON-LISP|::|=|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|STPPAR|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|<=|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|RELDX|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|XCTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|))
      |FORTRAN-TO-LISP|::|GOODX|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|I|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.)))
    (|COMMON-LISP|::|IF| (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| 0.)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 6.)))
    |FORTRAN-TO-LISP|::|LABEL250|
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|AND|
      (|COMMON-LISP|::|>|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
        (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
        |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
       5.)
      (|COMMON-LISP|::|/=|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
        (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
        |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
       12.))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|STPPAR|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|LMAXS|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL260|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|EMAXS|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DST0|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL270|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<=|
      (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DST0|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|))
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|LMAXS|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|))
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL270|)
    |FORTRAN-TO-LISP|::|LABEL260|
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<=|
      (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|))
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|LMAXS|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|XMAX|
     (|COMMON-LISP|::|/|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|LMAXS|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>=|
      (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|XMAX|
       (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|TWO| |FORTRAN-TO-LISP|::|XMAX|)
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|))
      |FORTRAN-TO-LISP|::|EMAXS|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|))
    |FORTRAN-TO-LISP|::|LABEL270|
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|NREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL290|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|GTSLST|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|GTSTEP|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DSTSAV|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      12.)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DSTSAV|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|-|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DSTSAV|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|))))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|PLSTGD|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|I|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     2.)
    (|COMMON-LISP|::|IF| (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|I| 3.)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      0.))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     6.)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|)
    |FORTRAN-TO-LISP|::|LABEL280|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|GTSTEP|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|GTSLST|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|COMMON-LISP|::|ABS|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DSTSAV|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|XIRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<=|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DSTSAV|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      12.))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|NREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|COMMON-LISP|::|-|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|PLSTGD|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
      (|FORTRAN-TO-LISP|::|RESTOR|) ((1. |FORTRAN-TO-LISP|::|LIV|))
      |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
     3.)
    |FORTRAN-TO-LISP|::|LABEL290|
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|<=|
      (|COMMON-LISP|::|-|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|NREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|))
      (|COMMON-LISP|::|*|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|SCTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       (|COMMON-LISP|::|ABS|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|F0|) ((1. |FORTRAN-TO-LISP|::|LV|))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|))))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|IV-%DATA%|
       (|FORTRAN-TO-LISP|::|IRC|) ((1. |FORTRAN-TO-LISP|::|LIV|))
       |FORTRAN-TO-LISP|::|IV-%OFFSET%|)
      11.))
    |FORTRAN-TO-LISP|::|LABEL999|
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|END_LABEL|)
    |FORTRAN-TO-LISP|::|END_LABEL|
    (|COMMON-LISP|::|RETURN|
     (|COMMON-LISP|::|VALUES| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|))))))

