;;; Compiled by f2cl version 2.0 beta Date: 2006/05/05 20:28:21 
;;; Using Lisp CLISP 2.38 (2006-01-24) (built on guru.build.karan.org)
;;; Options: ((:prune-labels nil) (:auto-save t) (:relaxed-array-decls t)
;;;  (:coerce-assigns :as-needed) (:array-type ':array) (:array-slicing t)
;;;  (:declare-common nil) (:float-format single-float))

(in-package :common-lisp-user)


(|COMMON-LISP|::|DEFUN| |FORTRAN-TO-LISP|::|DG7QTS|
   (|FORTRAN-TO-LISP|::|D| |FORTRAN-TO-LISP|::|DIG| |FORTRAN-TO-LISP|::|DIHDI|
    |FORTRAN-TO-LISP|::|KA| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|P|
    |FORTRAN-TO-LISP|::|STEP$| |FORTRAN-TO-LISP|::|V| |FORTRAN-TO-LISP|::|W|)
   (|COMMON-LISP|::|DECLARE|
    (|COMMON-LISP|::|TYPE|
     (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT|
      (|COMMON-LISP|::|*|))
     |FORTRAN-TO-LISP|::|STEP$| |FORTRAN-TO-LISP|::|DIG|
     |FORTRAN-TO-LISP|::|D|)
    (|COMMON-LISP|::|TYPE|
     (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT|
      (|COMMON-LISP|::|*|))
     |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|DIHDI|)
    (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|P|
     |FORTRAN-TO-LISP|::|KA|)
    (|COMMON-LISP|::|TYPE|
     (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT|
      (|COMMON-LISP|::|*|))
     |FORTRAN-TO-LISP|::|V|))
(|COMMON-LISP|::|LET*|
 ((|FORTRAN-TO-LISP|::|DGNORM| 1.) (|FORTRAN-TO-LISP|::|DSTNRM| 2.)
  (|FORTRAN-TO-LISP|::|DST0| 3.) (|FORTRAN-TO-LISP|::|EPSLON| 19.)
  (|FORTRAN-TO-LISP|::|GTSTEP| 4.) (|FORTRAN-TO-LISP|::|NREDUC| 6.)
  (|FORTRAN-TO-LISP|::|PHMNFC| 20.) (|FORTRAN-TO-LISP|::|PHMXFC| 21.)
  (|FORTRAN-TO-LISP|::|PREDUC| 7.) (|FORTRAN-TO-LISP|::|RADIUS| 8.)
  (|FORTRAN-TO-LISP|::|RAD0| 9.) (|FORTRAN-TO-LISP|::|STPPAR| 5.)
  (|FORTRAN-TO-LISP|::|EPSFAC| #1=50.0d0) (|FORTRAN-TO-LISP|::|FOUR| #2=4.0d0)
  (|FORTRAN-TO-LISP|::|HALF| #3=0.5d0) (|FORTRAN-TO-LISP|::|KAPPA| #4=2.0d0)
  (|FORTRAN-TO-LISP|::|NEGONE| (|COMMON-LISP|::|-| 1.0d0))
  (|FORTRAN-TO-LISP|::|ONE| #5=1.0d0) (|FORTRAN-TO-LISP|::|P001| #6=0.001d0)
  (|FORTRAN-TO-LISP|::|SIX| #7=6.0d0) (|FORTRAN-TO-LISP|::|THREE| #8=3.0d0)
  (|FORTRAN-TO-LISP|::|TWO| #9=2.0d0) (|FORTRAN-TO-LISP|::|ZERO| #10=0.0d0))
 (|COMMON-LISP|::|DECLARE|
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 1. 1.)
   |FORTRAN-TO-LISP|::|DGNORM|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 2. 2.)
   |FORTRAN-TO-LISP|::|DSTNRM|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 3. 3.)
   |FORTRAN-TO-LISP|::|DST0|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 19. 19.)
   |FORTRAN-TO-LISP|::|EPSLON|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 4. 4.)
   |FORTRAN-TO-LISP|::|GTSTEP|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 6. 6.)
   |FORTRAN-TO-LISP|::|NREDUC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 20. 20.)
   |FORTRAN-TO-LISP|::|PHMNFC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 21. 21.)
   |FORTRAN-TO-LISP|::|PHMXFC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 7. 7.)
   |FORTRAN-TO-LISP|::|PREDUC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 8. 8.)
   |FORTRAN-TO-LISP|::|RADIUS|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 9. 9.)
   |FORTRAN-TO-LISP|::|RAD0|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 5. 5.)
   |FORTRAN-TO-LISP|::|STPPAR|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #1# #1#)
   |FORTRAN-TO-LISP|::|EPSFAC|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #2# #2#)
   |FORTRAN-TO-LISP|::|FOUR|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #3# #3#)
   |FORTRAN-TO-LISP|::|HALF|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #4# #4#)
   |FORTRAN-TO-LISP|::|KAPPA|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
   |FORTRAN-TO-LISP|::|NEGONE|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #5# #5#)
   |FORTRAN-TO-LISP|::|ONE|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #6# #6#)
   |FORTRAN-TO-LISP|::|P001|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #7# #7#)
   |FORTRAN-TO-LISP|::|SIX|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #8# #8#)
   |FORTRAN-TO-LISP|::|THREE|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #9# #9#)
   |FORTRAN-TO-LISP|::|TWO|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #10# #10#)
   |FORTRAN-TO-LISP|::|ZERO|))
 (|COMMON-LISP|::|LET|
  ((|FORTRAN-TO-LISP|::|BIG| #10#) (|FORTRAN-TO-LISP|::|DGXFAC| #10#))
  (|COMMON-LISP|::|DECLARE|
   (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
    |FORTRAN-TO-LISP|::|DGXFAC| |FORTRAN-TO-LISP|::|BIG|))
  
;(incf *dg7qts*)

   (|F2CL-LIB|::|WITH-MULTI-ARRAY-DATA|
    ((|FORTRAN-TO-LISP|::|V| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|V-%DATA%| |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|DIHDI| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|DIHDI-%DATA%| |FORTRAN-TO-LISP|::|DIHDI-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|L| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|L-%DATA%| |FORTRAN-TO-LISP|::|L-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|W| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|W-%DATA%| |FORTRAN-TO-LISP|::|W-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|D| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|D-%DATA%| |FORTRAN-TO-LISP|::|D-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|DIG| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|DIG-%DATA%| |FORTRAN-TO-LISP|::|DIG-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|STEP$| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|STEP$-%DATA%| |FORTRAN-TO-LISP|::|STEP$-%OFFSET%|))
    (|COMMON-LISP|::|PROG|
     ((|FORTRAN-TO-LISP|::|ALPHAK| #10#) (|FORTRAN-TO-LISP|::|AKI| #10#)
      (|FORTRAN-TO-LISP|::|AKK| #10#) (|FORTRAN-TO-LISP|::|DELTA| #10#)
      (|FORTRAN-TO-LISP|::|DST| #10#) (|FORTRAN-TO-LISP|::|EPS| #10#)
      (|FORTRAN-TO-LISP|::|GTSTA| #10#) (|FORTRAN-TO-LISP|::|LK| #10#)
      (|FORTRAN-TO-LISP|::|OLDPHI| #10#) (|FORTRAN-TO-LISP|::|PHI| #10#)
      (|FORTRAN-TO-LISP|::|PHIMAX| #10#) (|FORTRAN-TO-LISP|::|PHIMIN| #10#)
      (|FORTRAN-TO-LISP|::|PSIFAC| #10#) (|FORTRAN-TO-LISP|::|RAD| #10#)
      (|FORTRAN-TO-LISP|::|RADSQ| #10#) (|FORTRAN-TO-LISP|::|ROOT| #10#)
      (|FORTRAN-TO-LISP|::|SI| #10#) (|FORTRAN-TO-LISP|::|SK| #10#)
      (|FORTRAN-TO-LISP|::|SW| #10#) (|FORTRAN-TO-LISP|::|TWOPSI| #10#)
      (|FORTRAN-TO-LISP|::|T1| #10#) (|FORTRAN-TO-LISP|::|T2| #10#)
      (|FORTRAN-TO-LISP|::|UK| #10#) (|FORTRAN-TO-LISP|::|WI| #10#)
      (|FORTRAN-TO-LISP|::|DGGDMX| 0.) (|FORTRAN-TO-LISP|::|DIAG| 0.)
      (|FORTRAN-TO-LISP|::|DIAG0| 0.) (|FORTRAN-TO-LISP|::|DSTSAV| 0.)
      (|FORTRAN-TO-LISP|::|EMAX| 0.) (|FORTRAN-TO-LISP|::|EMIN| 0.)
      (|FORTRAN-TO-LISP|::|I| 0.) (|FORTRAN-TO-LISP|::|IM1| 0.)
      (|FORTRAN-TO-LISP|::|INC| 0.) (|FORTRAN-TO-LISP|::|IRC| 0.)
      (|FORTRAN-TO-LISP|::|J| 0.) (|FORTRAN-TO-LISP|::|K| 0.)
      (|FORTRAN-TO-LISP|::|KALIM| 0.) (|FORTRAN-TO-LISP|::|KAMIN| 0.)
      (|FORTRAN-TO-LISP|::|K1| 0.) (|FORTRAN-TO-LISP|::|LK0| 0.)
      (|FORTRAN-TO-LISP|::|PHIPIN| 0.) (|FORTRAN-TO-LISP|::|Q| 0.)
      (|FORTRAN-TO-LISP|::|Q0| 0.) (|FORTRAN-TO-LISP|::|UK0| 0.)
      (|FORTRAN-TO-LISP|::|X| 0.)
      (|FORTRAN-TO-LISP|::|RESTRT| |COMMON-LISP|::|NIL|)
      (|FORTRAN-TO-LISP|::|T$| #10#))
     (|COMMON-LISP|::|DECLARE|
      (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
       |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|WI| |FORTRAN-TO-LISP|::|UK|
       |FORTRAN-TO-LISP|::|T2| |FORTRAN-TO-LISP|::|T1|
       |FORTRAN-TO-LISP|::|TWOPSI| |FORTRAN-TO-LISP|::|SW|
       |FORTRAN-TO-LISP|::|SK| |FORTRAN-TO-LISP|::|SI|
       |FORTRAN-TO-LISP|::|ROOT| |FORTRAN-TO-LISP|::|RADSQ|
       |FORTRAN-TO-LISP|::|RAD| |FORTRAN-TO-LISP|::|PSIFAC|
       |FORTRAN-TO-LISP|::|PHIMIN| |FORTRAN-TO-LISP|::|PHIMAX|
       |FORTRAN-TO-LISP|::|PHI| |FORTRAN-TO-LISP|::|OLDPHI|
       |FORTRAN-TO-LISP|::|LK| |FORTRAN-TO-LISP|::|GTSTA|
       |FORTRAN-TO-LISP|::|EPS| |FORTRAN-TO-LISP|::|DST|
       |FORTRAN-TO-LISP|::|DELTA| |FORTRAN-TO-LISP|::|AKK|
       |FORTRAN-TO-LISP|::|AKI| |FORTRAN-TO-LISP|::|ALPHAK|)
      (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|X|
       |FORTRAN-TO-LISP|::|UK0| |FORTRAN-TO-LISP|::|Q0| |FORTRAN-TO-LISP|::|Q|
       |FORTRAN-TO-LISP|::|PHIPIN| |FORTRAN-TO-LISP|::|LK0|
       |FORTRAN-TO-LISP|::|K1| |FORTRAN-TO-LISP|::|KAMIN|
       |FORTRAN-TO-LISP|::|KALIM| |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|J|
       |FORTRAN-TO-LISP|::|IRC| |FORTRAN-TO-LISP|::|INC|
       |FORTRAN-TO-LISP|::|IM1| |FORTRAN-TO-LISP|::|I|
       |FORTRAN-TO-LISP|::|EMIN| |FORTRAN-TO-LISP|::|EMAX|
       |FORTRAN-TO-LISP|::|DSTSAV| |FORTRAN-TO-LISP|::|DIAG0|
       |FORTRAN-TO-LISP|::|DIAG| |FORTRAN-TO-LISP|::|DGGDMX|)
      (|COMMON-LISP|::|TYPE| |F2CL-LIB|::|LOGICAL| |FORTRAN-TO-LISP|::|RESTRT|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|BIG| |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|BIG|
       (|FORTRAN-TO-LISP|::|DR7MDC| 6.)))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DGGDMX|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|P| 1.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|EMAX|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DGGDMX| 1.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|EMIN|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|EMAX| 1.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK0|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|EMIN| 1.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PHIPIN|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|LK0| 1.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK0|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|PHIPIN| 1.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DSTSAV|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|UK0| 1.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DIAG0|
      |FORTRAN-TO-LISP|::|DSTSAV|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DIAG|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DIAG0| 1.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|Q0|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DIAG0|
       |FORTRAN-TO-LISP|::|P|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|Q|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|Q0| 1.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|X|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|Q| |FORTRAN-TO-LISP|::|P|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|RAD|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|RADIUS|) ((1. 21.))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|RADSQ|
      (|COMMON-LISP|::|EXPT| |FORTRAN-TO-LISP|::|RAD| 2.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PHIMAX|
      (|COMMON-LISP|::|*|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|PHMXFC|) ((1. 21.))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|RAD|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PHIMIN|
      (|COMMON-LISP|::|*|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|PHMNFC|) ((1. 21.))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|RAD|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PSIFAC|
      |FORTRAN-TO-LISP|::|BIG|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
      (|COMMON-LISP|::|/|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|TWO|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|EPSLON|) ((1. 21.))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|))
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|THREE|
        (|COMMON-LISP|::|+|
         (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|FOUR|
          (|COMMON-LISP|::|+|
           (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
            (|FORTRAN-TO-LISP|::|PHMNFC|) ((1. 21.))
            |FORTRAN-TO-LISP|::|V-%OFFSET%|)
           |FORTRAN-TO-LISP|::|ONE|)
          (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|KAPPA|
           |FORTRAN-TO-LISP|::|ONE|))
         |FORTRAN-TO-LISP|::|KAPPA| |FORTRAN-TO-LISP|::|TWO|)
        |FORTRAN-TO-LISP|::|RAD|)))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|T1|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|BIG|
        (|COMMON-LISP|::|MIN| |FORTRAN-TO-LISP|::|RAD|
         |FORTRAN-TO-LISP|::|ONE|)))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PSIFAC|
       (|COMMON-LISP|::|/| |FORTRAN-TO-LISP|::|T1| |FORTRAN-TO-LISP|::|RAD|)))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|OLDPHI|
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|EPS|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|EPSLON|) ((1. 21.))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|IRC| 0.)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|RESTRT| |F2CL-LIB|::|%FALSE%|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KALIM|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|KA| 50.))
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|KA| 0.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL290|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| 0.)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK|
      |FORTRAN-TO-LISP|::|NEGONE|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KA| 0.)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KALIM| 50.)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DGNORM|) ((1. 21.))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|FORTRAN-TO-LISP|::|DV2NRM| |FORTRAN-TO-LISP|::|P|
       |FORTRAN-TO-LISP|::|DIG|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|NREDUC|) ((1. 21.))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.)) |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KAMIN| 3.)
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|=|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DGNORM|) ((1. 21.))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KAMIN| 0.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J| 0.)
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K1|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DIAG0|
         |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|K1|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|DIHDI-%DATA%|
         (|FORTRAN-TO-LISP|::|J|) ((1. 1.))
         |FORTRAN-TO-LISP|::|DIHDI-%OFFSET%|))
       |FORTRAN-TO-LISP|::|LABEL10|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1| |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
      (|COMMON-LISP|::|THE| |F2CL-LIB|::|INTEGER4|
       (|COMMON-LISP|::|TRUNCATE|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|P|
         (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|P| 1.))
        2.)))
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|J|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
        (|COMMON-LISP|::|ABS|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|DIHDI-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. 1.))
          |FORTRAN-TO-LISP|::|DIHDI-%OFFSET%|)))
       (|COMMON-LISP|::|IF|
        (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|T1| |FORTRAN-TO-LISP|::|T$|)
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
         |FORTRAN-TO-LISP|::|T$|))
       |FORTRAN-TO-LISP|::|LABEL20|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|DGGDMX|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
      |FORTRAN-TO-LISP|::|T1|)
     |FORTRAN-TO-LISP|::|LABEL30|
     (|COMMON-LISP|::|MULTIPLE-VALUE-BIND|
      (|FORTRAN-TO-LISP|::|VAR-0| |FORTRAN-TO-LISP|::|VAR-1|
       |FORTRAN-TO-LISP|::|VAR-2| |FORTRAN-TO-LISP|::|VAR-3|
       |FORTRAN-TO-LISP|::|VAR-4|)
      (|FORTRAN-TO-LISP|::|DL7SRT| 1. |FORTRAN-TO-LISP|::|P|
       |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|DIHDI|
       |FORTRAN-TO-LISP|::|IRC|)
      (|COMMON-LISP|::|DECLARE|
       (|COMMON-LISP|::|IGNORE| |FORTRAN-TO-LISP|::|VAR-0|
        |FORTRAN-TO-LISP|::|VAR-1| |FORTRAN-TO-LISP|::|VAR-2|
        |FORTRAN-TO-LISP|::|VAR-3|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|IRC|
       |FORTRAN-TO-LISP|::|VAR-4|))
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|IRC| 0.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL50|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
      (|COMMON-LISP|::|THE| |F2CL-LIB|::|INTEGER4|
       (|COMMON-LISP|::|TRUNCATE|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|IRC|
         (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|IRC| 1.))
        2.)))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|L-%DATA%|
       (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|L-%OFFSET%|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|L-%DATA%|
       (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|L-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ONE|)
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|IRC|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY| |FORTRAN-TO-LISP|::|LABEL40|
       (|COMMON-LISP|::|SETF|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|I|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
        |FORTRAN-TO-LISP|::|ZERO|)))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|IRC|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ONE|)
     (|FORTRAN-TO-LISP|::|DL7ITV| |FORTRAN-TO-LISP|::|IRC|
      |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|W|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
      (|FORTRAN-TO-LISP|::|DV2NRM| |FORTRAN-TO-LISP|::|IRC|
       |FORTRAN-TO-LISP|::|W|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK|
      (|COMMON-LISP|::|/|
       (|COMMON-LISP|::|/| (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|T$|)
        |FORTRAN-TO-LISP|::|T1|)
       |FORTRAN-TO-LISP|::|T1|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.)) |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|LK|))
     (|COMMON-LISP|::|IF| |FORTRAN-TO-LISP|::|RESTRT|
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL210|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL70|)
     |FORTRAN-TO-LISP|::|LABEL50|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK| |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
      (|FORTRAN-TO-LISP|::|DL7SVN| |FORTRAN-TO-LISP|::|P|
       |FORTRAN-TO-LISP|::|L|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|ONE|)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL60|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|>=|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DGNORM|) ((1. 21.))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|T$|
        |FORTRAN-TO-LISP|::|BIG|))
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL70|))
     |FORTRAN-TO-LISP|::|LABEL60|
     (|FORTRAN-TO-LISP|::|DL7IVM| |FORTRAN-TO-LISP|::|P|
      (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
       |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))
      |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|DIG|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|GTSTA|
      (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|P|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|NREDUC|) ((1. 21.))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
       |FORTRAN-TO-LISP|::|GTSTA|))
     (|FORTRAN-TO-LISP|::|DL7ITV| |FORTRAN-TO-LISP|::|P|
      (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
       |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))
      |FORTRAN-TO-LISP|::|L|
      (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
       |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.))))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DST|
      (|FORTRAN-TO-LISP|::|DV2NRM| |FORTRAN-TO-LISP|::|P|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.)) |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|DST|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PHI|
      (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|DST| |FORTRAN-TO-LISP|::|RAD|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|PHI|
       |FORTRAN-TO-LISP|::|PHIMAX|)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL260|))
     (|COMMON-LISP|::|IF| |FORTRAN-TO-LISP|::|RESTRT|
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL210|))
     |FORTRAN-TO-LISP|::|LABEL70|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| 0.)
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|WI|
        |FORTRAN-TO-LISP|::|ZERO|)
       (|COMMON-LISP|::|IF| (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|I| 1.)
        (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL90|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|IM1|
        (|F2CL-LIB|::|INT-SUB| |FORTRAN-TO-LISP|::|I| 1.))
       (|F2CL-LIB|::|FDO|
        (|FORTRAN-TO-LISP|::|J| 1.
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J| 1.))
        ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|IM1|)
         |COMMON-LISP|::|NIL|)
        (|COMMON-LISP|::|TAGBODY|
         (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
          (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K| 1.))
         (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
          (|COMMON-LISP|::|ABS|
           (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|DIHDI-%DATA%|
            (|FORTRAN-TO-LISP|::|K|) ((1. 1.))
            |FORTRAN-TO-LISP|::|DIHDI-%OFFSET%|)))
         (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|WI|
          (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|WI| |FORTRAN-TO-LISP|::|T$|))
         (|COMMON-LISP|::|SETF|
          (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
           (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
          (|COMMON-LISP|::|+|
           (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
            (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
           |FORTRAN-TO-LISP|::|T$|))
         |FORTRAN-TO-LISP|::|LABEL80|))
       |FORTRAN-TO-LISP|::|LABEL90|
       (|COMMON-LISP|::|SETF|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|I|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
        |FORTRAN-TO-LISP|::|WI|)
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K| 1.))
       |FORTRAN-TO-LISP|::|LABEL100|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| 1.)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
      (|COMMON-LISP|::|-|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
        (|FORTRAN-TO-LISP|::|DIAG|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%| (1.) ((1. 1.))
        |FORTRAN-TO-LISP|::|W-%OFFSET%|)))
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|P| 1.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL120|))
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 2.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DIAG0|
         |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
        (|COMMON-LISP|::|-|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
          (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)))
       (|COMMON-LISP|::|IF|
        (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|T1|)
        (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL110|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1| |FORTRAN-TO-LISP|::|T$|)
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|I|)
       |FORTRAN-TO-LISP|::|LABEL110|))
     |FORTRAN-TO-LISP|::|LABEL120|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|SK|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|K|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DIAG0|
       |FORTRAN-TO-LISP|::|K|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|AKK|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K1|
      (|COMMON-LISP|::|+|
       (|COMMON-LISP|::|THE| |F2CL-LIB|::|INTEGER4|
        (|COMMON-LISP|::|TRUNCATE|
         (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|K|
          (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|K| 1.))
         2.))
       1.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|INC| 1.)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|ZERO|)
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY|
       (|COMMON-LISP|::|IF|
        (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|K|)
        (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL130|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|AKI|
        (|COMMON-LISP|::|ABS|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|DIHDI-%DATA%|
          (|FORTRAN-TO-LISP|::|K1|) ((1. 1.))
          |FORTRAN-TO-LISP|::|DIHDI-%OFFSET%|)))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|SI|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|I|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DIAG0|
         |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
         (|COMMON-LISP|::|-|
          (|COMMON-LISP|::|+|
           (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|AKK|
            (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
             (|FORTRAN-TO-LISP|::|J|) ((1. 1.))
             |FORTRAN-TO-LISP|::|W-%OFFSET%|))
           |FORTRAN-TO-LISP|::|SI|)
          |FORTRAN-TO-LISP|::|AKI|)))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
        (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|T1|
         (|F2CL-LIB|::|FSQRT|
          (|COMMON-LISP|::|+|
           (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T1| |FORTRAN-TO-LISP|::|T1|)
           (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|SK|
            |FORTRAN-TO-LISP|::|AKI|)))))
       (|COMMON-LISP|::|IF|
        (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|T1|)
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
         |FORTRAN-TO-LISP|::|T1|))
       (|COMMON-LISP|::|IF|
        (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|K|)
        (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL140|))
       |FORTRAN-TO-LISP|::|LABEL130|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|INC| |FORTRAN-TO-LISP|::|I|)
       |FORTRAN-TO-LISP|::|LABEL140|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K1|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K1|
         |FORTRAN-TO-LISP|::|INC|))
       |FORTRAN-TO-LISP|::|LABEL150|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|EMIN|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
      (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|AKK| |FORTRAN-TO-LISP|::|T$|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK|
      (|COMMON-LISP|::|-|
       (|COMMON-LISP|::|/|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|DGNORM|) ((1. 21.))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|)
        |FORTRAN-TO-LISP|::|RAD|)
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
        (|FORTRAN-TO-LISP|::|EMIN|) ((1. 1.))
        |FORTRAN-TO-LISP|::|W-%OFFSET%|)))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|=|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DGNORM|) ((1. 21.))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK|
       (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|UK| |FORTRAN-TO-LISP|::|P001|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|P001|
         |FORTRAN-TO-LISP|::|UK|))))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|UK| |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK|
       |FORTRAN-TO-LISP|::|P001|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| 1.)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
      (|COMMON-LISP|::|+|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
        (|FORTRAN-TO-LISP|::|DIAG|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%| (1.) ((1. 1.))
        |FORTRAN-TO-LISP|::|W-%OFFSET%|)))
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|P| 1.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL170|))
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 2.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DIAG0|
         |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
        (|COMMON-LISP|::|+|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
          (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)))
       (|COMMON-LISP|::|IF|
        (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|T1|)
        (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL160|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1| |FORTRAN-TO-LISP|::|T$|)
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|I|)
       |FORTRAN-TO-LISP|::|LABEL160|))
     |FORTRAN-TO-LISP|::|LABEL170|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|SK|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|K|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DIAG0|
       |FORTRAN-TO-LISP|::|K|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|AKK|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K1|
      (|COMMON-LISP|::|+|
       (|COMMON-LISP|::|THE| |F2CL-LIB|::|INTEGER4|
        (|COMMON-LISP|::|TRUNCATE|
         (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|K|
          (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|K| 1.))
         2.))
       1.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|INC| 1.)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|ZERO|)
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY|
       (|COMMON-LISP|::|IF|
        (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|K|)
        (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL180|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|AKI|
        (|COMMON-LISP|::|ABS|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|DIHDI-%DATA%|
          (|FORTRAN-TO-LISP|::|K1|) ((1. 1.))
          |FORTRAN-TO-LISP|::|DIHDI-%OFFSET%|)))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|SI|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|I|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DIAG0|
         |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
         (|COMMON-LISP|::|-|
          (|COMMON-LISP|::|+|
           (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
            (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
           |FORTRAN-TO-LISP|::|SI|)
          |FORTRAN-TO-LISP|::|AKI| |FORTRAN-TO-LISP|::|AKK|)))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
        (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|T1|
         (|F2CL-LIB|::|FSQRT|
          (|COMMON-LISP|::|+|
           (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T1| |FORTRAN-TO-LISP|::|T1|)
           (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|SK|
            |FORTRAN-TO-LISP|::|AKI|)))))
       (|COMMON-LISP|::|IF|
        (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|T1|)
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
         |FORTRAN-TO-LISP|::|T1|))
       (|COMMON-LISP|::|IF|
        (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|K|)
        (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL190|))
       |FORTRAN-TO-LISP|::|LABEL180|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|INC| |FORTRAN-TO-LISP|::|I|)
       |FORTRAN-TO-LISP|::|LABEL190|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K1|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K1|
         |FORTRAN-TO-LISP|::|INC|))
       |FORTRAN-TO-LISP|::|LABEL200|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|EMAX|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
      (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|AKK| |FORTRAN-TO-LISP|::|T$|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK|
      (|COMMON-LISP|::|MAX| |FORTRAN-TO-LISP|::|LK|
       (|COMMON-LISP|::|-|
        (|COMMON-LISP|::|/|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
          (|FORTRAN-TO-LISP|::|DGNORM|) ((1. 21.))
          |FORTRAN-TO-LISP|::|V-%OFFSET%|)
         |FORTRAN-TO-LISP|::|RAD|)
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|EMAX|) ((1. 1.))
         |FORTRAN-TO-LISP|::|W-%OFFSET%|))))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALPHAK|
      (|COMMON-LISP|::|/|
       (|COMMON-LISP|::|*|
        (|COMMON-LISP|::|ABS|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
          (|FORTRAN-TO-LISP|::|STPPAR|) ((1. 21.))
          |FORTRAN-TO-LISP|::|V-%OFFSET%|))
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|RAD0|) ((1. 21.))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|))
       |FORTRAN-TO-LISP|::|RAD|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALPHAK|
      (|COMMON-LISP|::|MIN| |FORTRAN-TO-LISP|::|UK|
       (|COMMON-LISP|::|MAX| |FORTRAN-TO-LISP|::|ALPHAK|
        |FORTRAN-TO-LISP|::|LK|)))
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|/=| |FORTRAN-TO-LISP|::|IRC| 0.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL210|))
     (|FORTRAN-TO-LISP|::|DL7IVM| |FORTRAN-TO-LISP|::|P| |FORTRAN-TO-LISP|::|W|
      |FORTRAN-TO-LISP|::|L|
      (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
       |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.))))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
      (|FORTRAN-TO-LISP|::|DV2NRM| |FORTRAN-TO-LISP|::|P|
       |FORTRAN-TO-LISP|::|W|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|PHIPIN|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
      (|COMMON-LISP|::|/|
       (|COMMON-LISP|::|/| |FORTRAN-TO-LISP|::|RAD| |FORTRAN-TO-LISP|::|T$|)
       |FORTRAN-TO-LISP|::|T$|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK|
      (|COMMON-LISP|::|MAX| |FORTRAN-TO-LISP|::|LK|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|PHI|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|PHIPIN|) ((1. 1.))
         |FORTRAN-TO-LISP|::|W-%OFFSET%|))))
     |FORTRAN-TO-LISP|::|LABEL210|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KA|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|KA| 1.))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|OR|
       (|COMMON-LISP|::|>=|
        (|COMMON-LISP|::|-|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
          (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.))
          |FORTRAN-TO-LISP|::|V-%OFFSET%|))
        |FORTRAN-TO-LISP|::|ALPHAK|)
       (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|ALPHAK| |FORTRAN-TO-LISP|::|LK|)
       (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|ALPHAK|
        |FORTRAN-TO-LISP|::|UK|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALPHAK|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|UK|
        (|COMMON-LISP|::|MAX| |FORTRAN-TO-LISP|::|P001|
         (|F2CL-LIB|::|FSQRT|
          (|COMMON-LISP|::|/| |FORTRAN-TO-LISP|::|LK|
           |FORTRAN-TO-LISP|::|UK|))))))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|ALPHAK|
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALPHAK|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF| |FORTRAN-TO-LISP|::|UK|)))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|ALPHAK|
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALPHAK|
       |FORTRAN-TO-LISP|::|UK|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| 0.)
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DIAG0|
         |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|DIHDI-%DATA%|
         (|FORTRAN-TO-LISP|::|K|) ((1. 1.))
         |FORTRAN-TO-LISP|::|DIHDI-%OFFSET%|)
        (|COMMON-LISP|::|+|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
          (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
         |FORTRAN-TO-LISP|::|ALPHAK|))
       |FORTRAN-TO-LISP|::|LABEL220|))
     (|COMMON-LISP|::|MULTIPLE-VALUE-BIND|
      (|FORTRAN-TO-LISP|::|VAR-0| |FORTRAN-TO-LISP|::|VAR-1|
       |FORTRAN-TO-LISP|::|VAR-2| |FORTRAN-TO-LISP|::|VAR-3|
       |FORTRAN-TO-LISP|::|VAR-4|)
      (|FORTRAN-TO-LISP|::|DL7SRT| 1. |FORTRAN-TO-LISP|::|P|
       |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|DIHDI|
       |FORTRAN-TO-LISP|::|IRC|)
      (|COMMON-LISP|::|DECLARE|
       (|COMMON-LISP|::|IGNORE| |FORTRAN-TO-LISP|::|VAR-0|
        |FORTRAN-TO-LISP|::|VAR-1| |FORTRAN-TO-LISP|::|VAR-2|
        |FORTRAN-TO-LISP|::|VAR-3|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|IRC|
       |FORTRAN-TO-LISP|::|VAR-4|))
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|IRC| 0.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL240|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
      (|COMMON-LISP|::|THE| |F2CL-LIB|::|INTEGER4|
       (|COMMON-LISP|::|TRUNCATE|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|IRC|
         (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|IRC| 1.))
        2.)))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|L-%DATA%|
       (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|L-%OFFSET%|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|L-%DATA%|
       (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|L-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ONE|)
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|IRC|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY| |FORTRAN-TO-LISP|::|LABEL230|
       (|COMMON-LISP|::|SETF|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|I|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
        |FORTRAN-TO-LISP|::|ZERO|)))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|IRC|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ONE|)
     (|FORTRAN-TO-LISP|::|DL7ITV| |FORTRAN-TO-LISP|::|IRC|
      |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|W|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
      (|FORTRAN-TO-LISP|::|DV2NRM| |FORTRAN-TO-LISP|::|IRC|
       |FORTRAN-TO-LISP|::|W|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK|
      (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|ALPHAK|
       (|COMMON-LISP|::|/|
        (|COMMON-LISP|::|/| (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|T$|)
         |FORTRAN-TO-LISP|::|T1|)
        |FORTRAN-TO-LISP|::|T1|)))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.)) |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|LK|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|UK| |FORTRAN-TO-LISP|::|LK|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK| |FORTRAN-TO-LISP|::|LK|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|ALPHAK| |FORTRAN-TO-LISP|::|LK|)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL210|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
      (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|P001|
       |FORTRAN-TO-LISP|::|ALPHAK|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
       |FORTRAN-TO-LISP|::|P001|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK|
      (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|ALPHAK| |FORTRAN-TO-LISP|::|T$|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|UK| |FORTRAN-TO-LISP|::|LK|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK|
       (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|LK| |FORTRAN-TO-LISP|::|T$|)))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL210|)
     |FORTRAN-TO-LISP|::|LABEL240|
     (|FORTRAN-TO-LISP|::|DL7IVM| |FORTRAN-TO-LISP|::|P|
      (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
       |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))
      |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|DIG|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|GTSTA|
      (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|P|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))))
     (|FORTRAN-TO-LISP|::|DL7ITV| |FORTRAN-TO-LISP|::|P|
      (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
       |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))
      |FORTRAN-TO-LISP|::|L|
      (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
       |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.))))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DST|
      (|FORTRAN-TO-LISP|::|DV2NRM| |FORTRAN-TO-LISP|::|P|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PHI|
      (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|DST| |FORTRAN-TO-LISP|::|RAD|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|AND|
       (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|PHI|
        |FORTRAN-TO-LISP|::|PHIMAX|)
       (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|PHI|
        |FORTRAN-TO-LISP|::|PHIMIN|))
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL270|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|PHI| |FORTRAN-TO-LISP|::|OLDPHI|)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL270|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|OLDPHI|
      |FORTRAN-TO-LISP|::|PHI|)
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|PHI| |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL330|))
     |FORTRAN-TO-LISP|::|LABEL250|
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|KA| |FORTRAN-TO-LISP|::|KALIM|)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL270|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|PHI| |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK|
       (|COMMON-LISP|::|MIN| |FORTRAN-TO-LISP|::|UK|
        |FORTRAN-TO-LISP|::|ALPHAK|)))
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|KAMIN| 0.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL210|))
     (|FORTRAN-TO-LISP|::|DL7IVM| |FORTRAN-TO-LISP|::|P| |FORTRAN-TO-LISP|::|W|
      |FORTRAN-TO-LISP|::|L|
      (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
       |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.))))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
      (|FORTRAN-TO-LISP|::|DV2NRM| |FORTRAN-TO-LISP|::|P|
       |FORTRAN-TO-LISP|::|W|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALPHAK|
      (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|ALPHAK|
       (|COMMON-LISP|::|*|
        (|COMMON-LISP|::|/| |FORTRAN-TO-LISP|::|PHI| |FORTRAN-TO-LISP|::|T1|)
        (|COMMON-LISP|::|/| |FORTRAN-TO-LISP|::|DST| |FORTRAN-TO-LISP|::|T1|)
        (|COMMON-LISP|::|/| |FORTRAN-TO-LISP|::|DST|
         |FORTRAN-TO-LISP|::|RAD|))))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK|
      (|COMMON-LISP|::|MAX| |FORTRAN-TO-LISP|::|LK|
       |FORTRAN-TO-LISP|::|ALPHAK|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALPHAK|
      |FORTRAN-TO-LISP|::|LK|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL210|)
     |FORTRAN-TO-LISP|::|LABEL260|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALPHAK|
      |FORTRAN-TO-LISP|::|ZERO|)
     |FORTRAN-TO-LISP|::|LABEL270|
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|Q0| |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|STEP$-%DATA%|
         (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|P|))
         |FORTRAN-TO-LISP|::|STEP$-%OFFSET%|)
        (|COMMON-LISP|::|/|
         (|COMMON-LISP|::|-|
          (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
           (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|))
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|D-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|P|))
          |FORTRAN-TO-LISP|::|D-%OFFSET%|)))
       |FORTRAN-TO-LISP|::|LABEL280|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|GTSTEP|) ((1. 21.))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|GTSTA|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|PREDUC|) ((1. 21.))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
       (|COMMON-LISP|::|+|
        (|COMMON-LISP|::|*| (|COMMON-LISP|::|ABS| |FORTRAN-TO-LISP|::|ALPHAK|)
         |FORTRAN-TO-LISP|::|DST| |FORTRAN-TO-LISP|::|DST|)
        |FORTRAN-TO-LISP|::|GTSTA|)))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL410|)
     |FORTRAN-TO-LISP|::|LABEL290|
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|OR|
       (|COMMON-LISP|::|<=|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|)
        |FORTRAN-TO-LISP|::|ZERO|)
       (|COMMON-LISP|::|>|
        (|COMMON-LISP|::|-|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
          (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.))
          |FORTRAN-TO-LISP|::|V-%OFFSET%|)
         |FORTRAN-TO-LISP|::|RAD|)
        |FORTRAN-TO-LISP|::|PHIMAX|))
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL310|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|RESTRT| |F2CL-LIB|::|%TRUE%|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KA|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|KA| 1.))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| 0.)
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DIAG0|
         |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|DIHDI-%DATA%|
         (|FORTRAN-TO-LISP|::|K|) ((1. 1.))
         |FORTRAN-TO-LISP|::|DIHDI-%OFFSET%|)
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|))
       |FORTRAN-TO-LISP|::|LABEL300|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK|
      |FORTRAN-TO-LISP|::|NEGONE|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL30|)
     |FORTRAN-TO-LISP|::|LABEL310|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KAMIN|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|KA| 3.))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|=|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DGNORM|) ((1. 21.))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KAMIN| 0.))
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|KA| 0.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL50|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DST|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|DSTSAV|) ((1. 1.))
       |FORTRAN-TO-LISP|::|W-%OFFSET%|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALPHAK|
      (|COMMON-LISP|::|ABS|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|STPPAR|) ((1. 21.))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PHI|
      (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|DST| |FORTRAN-TO-LISP|::|RAD|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
      (|COMMON-LISP|::|/|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DGNORM|) ((1. 21.))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|RAD|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK|
      (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|T$|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
        (|FORTRAN-TO-LISP|::|EMIN|) ((1. 1.))
        |FORTRAN-TO-LISP|::|W-%OFFSET%|)))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|=|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DGNORM|) ((1. 21.))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK|
       (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|UK| |FORTRAN-TO-LISP|::|P001|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|P001|
         |FORTRAN-TO-LISP|::|UK|))))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|UK| |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK|
       |FORTRAN-TO-LISP|::|P001|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|RAD|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|RAD0|) ((1. 21.))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|))
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL320|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK| |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|ALPHAK|
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
        (|FORTRAN-TO-LISP|::|LK0|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK|
      (|COMMON-LISP|::|MAX| |FORTRAN-TO-LISP|::|LK|
       (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|T$|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|EMAX|) ((1. 1.))
         |FORTRAN-TO-LISP|::|W-%OFFSET%|))))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|>|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.)) |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK|
       (|COMMON-LISP|::|MAX| |FORTRAN-TO-LISP|::|LK|
        (|COMMON-LISP|::|*|
         (|COMMON-LISP|::|-|
          (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
           (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.))
           |FORTRAN-TO-LISP|::|V-%OFFSET%|)
          |FORTRAN-TO-LISP|::|RAD|)
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
          (|FORTRAN-TO-LISP|::|PHIPIN|) ((1. 1.))
          |FORTRAN-TO-LISP|::|W-%OFFSET%|)))))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL250|)
     |FORTRAN-TO-LISP|::|LABEL320|
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|ALPHAK|
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UK|
       (|COMMON-LISP|::|MIN| |FORTRAN-TO-LISP|::|UK|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|UK0|) ((1. 1.))
         |FORTRAN-TO-LISP|::|W-%OFFSET%|))))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK|
      (|COMMON-LISP|::|MAX| |FORTRAN-TO-LISP|::|ZERO|
       (|COMMON-LISP|::|-|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|))
       (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|T$|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|EMAX|) ((1. 1.))
         |FORTRAN-TO-LISP|::|W-%OFFSET%|))))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|>|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.)) |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK|
       (|COMMON-LISP|::|MAX| |FORTRAN-TO-LISP|::|LK|
        (|COMMON-LISP|::|*|
         (|COMMON-LISP|::|-|
          (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
           (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.))
           |FORTRAN-TO-LISP|::|V-%OFFSET%|)
          |FORTRAN-TO-LISP|::|RAD|)
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
          (|FORTRAN-TO-LISP|::|PHIPIN|) ((1. 1.))
          |FORTRAN-TO-LISP|::|W-%OFFSET%|)))))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL250|)
     |FORTRAN-TO-LISP|::|LABEL330|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DELTA|
      (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|ALPHAK|
       (|COMMON-LISP|::|MIN| |FORTRAN-TO-LISP|::|ZERO|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|))))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|TWOPSI|
      (|COMMON-LISP|::|+|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|ALPHAK| |FORTRAN-TO-LISP|::|DST|
        |FORTRAN-TO-LISP|::|DST|)
       |FORTRAN-TO-LISP|::|GTSTA|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|KA| |FORTRAN-TO-LISP|::|KAMIN|)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL340|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|PSIFAC|
       |FORTRAN-TO-LISP|::|BIG|)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL340|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|DELTA|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|PSIFAC|
        |FORTRAN-TO-LISP|::|TWOPSI|))
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL370|))
     |FORTRAN-TO-LISP|::|LABEL340|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
      (|FORTRAN-TO-LISP|::|DL7SVN| |FORTRAN-TO-LISP|::|P|
       |FORTRAN-TO-LISP|::|L|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|X|) ((1. 1.)))
       |FORTRAN-TO-LISP|::|W|))
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY| |FORTRAN-TO-LISP|::|LABEL350|
       (|COMMON-LISP|::|SETF|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|I|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T$|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. 1.))
          |FORTRAN-TO-LISP|::|W-%OFFSET%|)))))
     (|FORTRAN-TO-LISP|::|DL7ITV| |FORTRAN-TO-LISP|::|P| |FORTRAN-TO-LISP|::|W|
      |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|W|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T2|
      (|COMMON-LISP|::|/| |FORTRAN-TO-LISP|::|ONE|
       (|FORTRAN-TO-LISP|::|DV2NRM| |FORTRAN-TO-LISP|::|P|
        |FORTRAN-TO-LISP|::|W|)))
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY| |FORTRAN-TO-LISP|::|LABEL360|
       (|COMMON-LISP|::|SETF|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|I|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T2|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. 1.))
          |FORTRAN-TO-LISP|::|W-%OFFSET%|)))))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
      (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T2| |FORTRAN-TO-LISP|::|T$|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|SW|
      (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|P|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))
       |FORTRAN-TO-LISP|::|W|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
      (|COMMON-LISP|::|*|
       (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|RAD| |FORTRAN-TO-LISP|::|DST|)
       (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|RAD| |FORTRAN-TO-LISP|::|DST|)))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ROOT|
      (|F2CL-LIB|::|FSQRT|
       (|COMMON-LISP|::|+|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|SW| |FORTRAN-TO-LISP|::|SW|)
        |FORTRAN-TO-LISP|::|T1|)))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|SW| |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ROOT|
       (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|ROOT|)))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|SI|
      (|COMMON-LISP|::|/| |FORTRAN-TO-LISP|::|T1|
       (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|SW| |FORTRAN-TO-LISP|::|ROOT|)))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<=|
       (|COMMON-LISP|::|EXPT|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T2| |FORTRAN-TO-LISP|::|SI|)
        2.)
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|EPS|
        (|COMMON-LISP|::|+| (|COMMON-LISP|::|EXPT| |FORTRAN-TO-LISP|::|DST| 2.)
         (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|ALPHAK|
          |FORTRAN-TO-LISP|::|RADSQ|))))
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL380|))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<=|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.)) |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.)) |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       (|COMMON-LISP|::|MIN|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|)
        (|COMMON-LISP|::|-| (|COMMON-LISP|::|EXPT| |FORTRAN-TO-LISP|::|T2| 2.)
         |FORTRAN-TO-LISP|::|ALPHAK|))))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|LK|
      (|COMMON-LISP|::|MAX| |FORTRAN-TO-LISP|::|LK|
       (|COMMON-LISP|::|-|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
         (|FORTRAN-TO-LISP|::|DST0|) ((1. 21.))
         |FORTRAN-TO-LISP|::|V-%OFFSET%|))))
     |FORTRAN-TO-LISP|::|LABEL370|
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|DGXFAC|
       |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DGXFAC|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|EPSFAC|
        (|FORTRAN-TO-LISP|::|DR7MDC| 3.))))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|DELTA|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|DGXFAC|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|DGGDMX|) ((1. 1.))
         |FORTRAN-TO-LISP|::|W-%OFFSET%|)))
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL250|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL270|)
     |FORTRAN-TO-LISP|::|LABEL380|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|ALPHAK|
      (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|ALPHAK|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|PREDUC|) ((1. 21.))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
       |FORTRAN-TO-LISP|::|TWOPSI|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1| |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
      (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|SI|
       (|COMMON-LISP|::|+|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|ALPHAK|
         |FORTRAN-TO-LISP|::|SW|)
        (|COMMON-LISP|::|*| (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|HALF|)
         |FORTRAN-TO-LISP|::|SI|
         (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|ALPHAK|
          (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T$|
           (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|P|
            (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
             |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|X|) ((1. 1.)))
            |FORTRAN-TO-LISP|::|W|)))))))
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|T$|
       (|COMMON-LISP|::|/|
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|EPS|
         |FORTRAN-TO-LISP|::|TWOPSI|)
        |FORTRAN-TO-LISP|::|SIX|))
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL390|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|PREDUC|) ((1. 21.))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|+|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|PREDUC|) ((1. 21.))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)
       |FORTRAN-TO-LISP|::|T$|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DST| |FORTRAN-TO-LISP|::|RAD|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T1|
      (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|SI|))
     |FORTRAN-TO-LISP|::|LABEL390|
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|Q0| |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
        (|COMMON-LISP|::|-|
         (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T1|
          (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
           (|FORTRAN-TO-LISP|::|I|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|))
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
          (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)))
       (|COMMON-LISP|::|SETF|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|STEP$-%DATA%|
         (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|P|))
         |FORTRAN-TO-LISP|::|STEP$-%OFFSET%|)
        (|COMMON-LISP|::|/|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
          (|FORTRAN-TO-LISP|::|J|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|D-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|P|))
          |FORTRAN-TO-LISP|::|D-%OFFSET%|)))
       |FORTRAN-TO-LISP|::|LABEL400|))
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|GTSTEP|) ((1. 21.))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|P|
       |FORTRAN-TO-LISP|::|DIG|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|W|
        |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|Q|) ((1. 1.)))))
     |FORTRAN-TO-LISP|::|LABEL410|
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. 21.))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|DST|)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|STPPAR|) ((1. 21.))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ALPHAK|)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|LK0|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
      |FORTRAN-TO-LISP|::|LK|)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|UK0|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
      |FORTRAN-TO-LISP|::|UK|)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|RAD0|) ((1. 21.)) |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|RAD|)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
       (|FORTRAN-TO-LISP|::|DSTSAV|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
      |FORTRAN-TO-LISP|::|DST|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J| 0.)
     (|F2CL-LIB|::|FDO|
      (|FORTRAN-TO-LISP|::|I| 1.
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
      ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
       |COMMON-LISP|::|NIL|)
      (|COMMON-LISP|::|TAGBODY|
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|DIAG0|
         |FORTRAN-TO-LISP|::|I|))
       (|COMMON-LISP|::|SETF|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|DIHDI-%DATA%|
         (|FORTRAN-TO-LISP|::|J|) ((1. 1.))
         |FORTRAN-TO-LISP|::|DIHDI-%OFFSET%|)
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
         (|FORTRAN-TO-LISP|::|K|) ((1. 1.)) |FORTRAN-TO-LISP|::|W-%OFFSET%|))
       |FORTRAN-TO-LISP|::|LABEL420|))
     |FORTRAN-TO-LISP|::|LABEL999|
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|END_LABEL|)
     |FORTRAN-TO-LISP|::|END_LABEL|
     (|COMMON-LISP|::|RETURN|
      (|COMMON-LISP|::|VALUES| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
       |COMMON-LISP|::|NIL| |FORTRAN-TO-LISP|::|KA| |COMMON-LISP|::|NIL|
       |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
       |COMMON-LISP|::|NIL|)))))))

