;;; Compiled by f2cl version 2.0 beta Date: 2006/05/05 20:28:21 
;;; Using Lisp CLISP 2.38 (2006-01-24) (built on guru.build.karan.org)
;;; Options: ((:prune-labels nil) (:auto-save t) (:relaxed-array-decls t)
;;;  (:coerce-assigns :as-needed) (:array-type ':array) (:array-slicing t)
;;;  (:declare-common nil) (:float-format single-float))

(in-package :common-lisp-user)


(|COMMON-LISP|::|DEFUN| |FORTRAN-TO-LISP|::|DG7QSB|
   (|FORTRAN-TO-LISP|::|B| |FORTRAN-TO-LISP|::|D| |FORTRAN-TO-LISP|::|DIHDI|
    |FORTRAN-TO-LISP|::|G| |FORTRAN-TO-LISP|::|IPIV| |FORTRAN-TO-LISP|::|IPIV1|
    |FORTRAN-TO-LISP|::|IPIV2| |FORTRAN-TO-LISP|::|KA| |FORTRAN-TO-LISP|::|L|
    |FORTRAN-TO-LISP|::|LV| |FORTRAN-TO-LISP|::|P| |FORTRAN-TO-LISP|::|P0|
    |FORTRAN-TO-LISP|::|PC| |FORTRAN-TO-LISP|::|STEP$| |FORTRAN-TO-LISP|::|TD|
    |FORTRAN-TO-LISP|::|TG| |FORTRAN-TO-LISP|::|V| |FORTRAN-TO-LISP|::|W|
    |FORTRAN-TO-LISP|::|X| |FORTRAN-TO-LISP|::|X0|)
   (|COMMON-LISP|::|DECLARE|
    (|COMMON-LISP|::|TYPE|
     (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT|
      (|COMMON-LISP|::|*|))
     |FORTRAN-TO-LISP|::|X0| |FORTRAN-TO-LISP|::|X| |FORTRAN-TO-LISP|::|W|
     |FORTRAN-TO-LISP|::|V| |FORTRAN-TO-LISP|::|TG| |FORTRAN-TO-LISP|::|TD|
     |FORTRAN-TO-LISP|::|STEP$| |FORTRAN-TO-LISP|::|G| |FORTRAN-TO-LISP|::|D|
     |FORTRAN-TO-LISP|::|B|)
    (|COMMON-LISP|::|TYPE|
     (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT|
      (|COMMON-LISP|::|*|))
     |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|DIHDI|)
    (|COMMON-LISP|::|TYPE|
     (|COMMON-LISP|::|ARRAY| |F2CL-LIB|::|INTEGER4| (|COMMON-LISP|::|*|))
     |FORTRAN-TO-LISP|::|IPIV2| |FORTRAN-TO-LISP|::|IPIV1|
     |FORTRAN-TO-LISP|::|IPIV|)
    (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|PC|
     |FORTRAN-TO-LISP|::|P0| |FORTRAN-TO-LISP|::|P| |FORTRAN-TO-LISP|::|LV|
     |FORTRAN-TO-LISP|::|KA|))
(|COMMON-LISP|::|LET*|
 ((|FORTRAN-TO-LISP|::|DST0| 3.) (|FORTRAN-TO-LISP|::|DSTNRM| 2.)
  (|FORTRAN-TO-LISP|::|GTSTEP| 4.) (|FORTRAN-TO-LISP|::|NREDUC| 6.)
  (|FORTRAN-TO-LISP|::|PREDUC| 7.) (|FORTRAN-TO-LISP|::|RADIUS| 8.))
 (|COMMON-LISP|::|DECLARE|
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 3. 3.)
   |FORTRAN-TO-LISP|::|DST0|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 2. 2.)
   |FORTRAN-TO-LISP|::|DSTNRM|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 4. 4.)
   |FORTRAN-TO-LISP|::|GTSTEP|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 6. 6.)
   |FORTRAN-TO-LISP|::|NREDUC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 7. 7.)
   |FORTRAN-TO-LISP|::|PREDUC|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 8. 8.)
   |FORTRAN-TO-LISP|::|RADIUS|))
 (|COMMON-LISP|::|LET| ((|FORTRAN-TO-LISP|::|ZERO| #1=0.0d0))
  (|COMMON-LISP|::|DECLARE|
   (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
    |FORTRAN-TO-LISP|::|ZERO|))
  
;(incf\ *dg7qsb*)

   (|F2CL-LIB|::|WITH-MULTI-ARRAY-DATA|
    ((|FORTRAN-TO-LISP|::|IPIV| |F2CL-LIB|::|INTEGER4|
      |FORTRAN-TO-LISP|::|IPIV-%DATA%| |FORTRAN-TO-LISP|::|IPIV-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|IPIV1| |F2CL-LIB|::|INTEGER4|
      |FORTRAN-TO-LISP|::|IPIV1-%DATA%| |FORTRAN-TO-LISP|::|IPIV1-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|IPIV2| |F2CL-LIB|::|INTEGER4|
      |FORTRAN-TO-LISP|::|IPIV2-%DATA%| |FORTRAN-TO-LISP|::|IPIV2-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|DIHDI| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|DIHDI-%DATA%| |FORTRAN-TO-LISP|::|DIHDI-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|L| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|L-%DATA%| |FORTRAN-TO-LISP|::|L-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|B| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|B-%DATA%| |FORTRAN-TO-LISP|::|B-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|D| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|D-%DATA%| |FORTRAN-TO-LISP|::|D-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|G| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|G-%DATA%| |FORTRAN-TO-LISP|::|G-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|STEP$| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|STEP$-%DATA%| |FORTRAN-TO-LISP|::|STEP$-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|TD| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|TD-%DATA%| |FORTRAN-TO-LISP|::|TD-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|TG| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|TG-%DATA%| |FORTRAN-TO-LISP|::|TG-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|V| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|V-%DATA%| |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|W| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|W-%DATA%| |FORTRAN-TO-LISP|::|W-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|X| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|X-%DATA%| |FORTRAN-TO-LISP|::|X-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|X0| |COMMON-LISP|::|DOUBLE-FLOAT|
      |FORTRAN-TO-LISP|::|X0-%DATA%| |FORTRAN-TO-LISP|::|X0-%OFFSET%|))
    (|COMMON-LISP|::|PROG|
     ((|FORTRAN-TO-LISP|::|DS0| #1#) (|FORTRAN-TO-LISP|::|NRED| #1#)
      (|FORTRAN-TO-LISP|::|PRED| #1#) (|FORTRAN-TO-LISP|::|RAD| #1#)
      (|FORTRAN-TO-LISP|::|K| 0.) (|FORTRAN-TO-LISP|::|KB| 0.)
      (|FORTRAN-TO-LISP|::|KINIT| 0.) (|FORTRAN-TO-LISP|::|NS| 0.)
      (|FORTRAN-TO-LISP|::|P1| 0.) (|FORTRAN-TO-LISP|::|P10| 0.))
     (|COMMON-LISP|::|DECLARE|
      (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
       |FORTRAN-TO-LISP|::|RAD| |FORTRAN-TO-LISP|::|PRED|
       |FORTRAN-TO-LISP|::|NRED| |FORTRAN-TO-LISP|::|DS0|)
      (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|P10|
       |FORTRAN-TO-LISP|::|P1| |FORTRAN-TO-LISP|::|NS|
       |FORTRAN-TO-LISP|::|KINIT| |FORTRAN-TO-LISP|::|KB|
       |FORTRAN-TO-LISP|::|K|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|P1| |FORTRAN-TO-LISP|::|PC|)
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|<| |FORTRAN-TO-LISP|::|KA| 0.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL10|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|NRED|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|NREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DS0|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DST0|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL20|)
     |FORTRAN-TO-LISP|::|LABEL10|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|P0| 0.)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KA| -1.)
     |FORTRAN-TO-LISP|::|LABEL20|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KINIT| -1.)
     (|COMMON-LISP|::|IF|
      (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|P0| |FORTRAN-TO-LISP|::|P1|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KINIT|
       |FORTRAN-TO-LISP|::|KA|))
     (|FORTRAN-TO-LISP|::|DV7CPY| |FORTRAN-TO-LISP|::|P| |FORTRAN-TO-LISP|::|X|
      |FORTRAN-TO-LISP|::|X0|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PRED|
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|RAD|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|RADIUS|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KB| -1.)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|P1| 0.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL30|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|NRED|
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DS0| |FORTRAN-TO-LISP|::|ZERO|)
     (|FORTRAN-TO-LISP|::|DV7SCP| |FORTRAN-TO-LISP|::|P|
      |FORTRAN-TO-LISP|::|STEP$| |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL60|)
     |FORTRAN-TO-LISP|::|LABEL30|
     (|FORTRAN-TO-LISP|::|DV7CPY| |FORTRAN-TO-LISP|::|P|
      |FORTRAN-TO-LISP|::|TD| |FORTRAN-TO-LISP|::|D|)
     (|FORTRAN-TO-LISP|::|DV7IPR| |FORTRAN-TO-LISP|::|P|
      |FORTRAN-TO-LISP|::|IPIV| |FORTRAN-TO-LISP|::|TD|)
     (|FORTRAN-TO-LISP|::|DV7VMP| |FORTRAN-TO-LISP|::|P|
      |FORTRAN-TO-LISP|::|TG| |FORTRAN-TO-LISP|::|G| |FORTRAN-TO-LISP|::|D|
      -1.)
     (|FORTRAN-TO-LISP|::|DV7IPR| |FORTRAN-TO-LISP|::|P|
      |FORTRAN-TO-LISP|::|IPIV| |FORTRAN-TO-LISP|::|TG|)
     |FORTRAN-TO-LISP|::|LABEL40|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|KINIT|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KINIT| -1.)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|RADIUS|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|-| |FORTRAN-TO-LISP|::|RAD|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|DSTNRM|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
     (|COMMON-LISP|::|MULTIPLE-VALUE-BIND|
      (|FORTRAN-TO-LISP|::|VAR-0| |FORTRAN-TO-LISP|::|VAR-1|
       |FORTRAN-TO-LISP|::|VAR-2| |FORTRAN-TO-LISP|::|VAR-3|
       |FORTRAN-TO-LISP|::|VAR-4| |FORTRAN-TO-LISP|::|VAR-5|
       |FORTRAN-TO-LISP|::|VAR-6| |FORTRAN-TO-LISP|::|VAR-7|
       |FORTRAN-TO-LISP|::|VAR-8|)
      (|FORTRAN-TO-LISP|::|DG7QTS| |FORTRAN-TO-LISP|::|TD|
       |FORTRAN-TO-LISP|::|TG| |FORTRAN-TO-LISP|::|DIHDI|
       |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|P1|
       |FORTRAN-TO-LISP|::|STEP$| |FORTRAN-TO-LISP|::|V|
       |FORTRAN-TO-LISP|::|W|)
      (|COMMON-LISP|::|DECLARE|
       (|COMMON-LISP|::|IGNORE| |FORTRAN-TO-LISP|::|VAR-0|
        |FORTRAN-TO-LISP|::|VAR-1| |FORTRAN-TO-LISP|::|VAR-2|
        |FORTRAN-TO-LISP|::|VAR-4| |FORTRAN-TO-LISP|::|VAR-5|
        |FORTRAN-TO-LISP|::|VAR-6| |FORTRAN-TO-LISP|::|VAR-7|
        |FORTRAN-TO-LISP|::|VAR-8|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
       |FORTRAN-TO-LISP|::|VAR-3|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|P0| |FORTRAN-TO-LISP|::|P1|)
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|KA| 0.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL50|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|NRED|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|NREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DS0|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DST0|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|))
     |FORTRAN-TO-LISP|::|LABEL50|
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KA| |FORTRAN-TO-LISP|::|K|)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|RADIUS|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|RAD|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|P10| |FORTRAN-TO-LISP|::|P1|)
     (|COMMON-LISP|::|MULTIPLE-VALUE-BIND|
      (|FORTRAN-TO-LISP|::|VAR-0| |FORTRAN-TO-LISP|::|VAR-1|
       |FORTRAN-TO-LISP|::|VAR-2| |FORTRAN-TO-LISP|::|VAR-3|
       |FORTRAN-TO-LISP|::|VAR-4| |FORTRAN-TO-LISP|::|VAR-5|
       |FORTRAN-TO-LISP|::|VAR-6| |FORTRAN-TO-LISP|::|VAR-7|
       |FORTRAN-TO-LISP|::|VAR-8| |FORTRAN-TO-LISP|::|VAR-9|
       |FORTRAN-TO-LISP|::|VAR-10| |FORTRAN-TO-LISP|::|VAR-11|
       |FORTRAN-TO-LISP|::|VAR-12| |FORTRAN-TO-LISP|::|VAR-13|
       |FORTRAN-TO-LISP|::|VAR-14| |FORTRAN-TO-LISP|::|VAR-15|
       |FORTRAN-TO-LISP|::|VAR-16| |FORTRAN-TO-LISP|::|VAR-17|
       |FORTRAN-TO-LISP|::|VAR-18|)
      (|FORTRAN-TO-LISP|::|DS7BQN| |FORTRAN-TO-LISP|::|B|
       |FORTRAN-TO-LISP|::|D|
       (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|STEP$|
        |COMMON-LISP|::|DOUBLE-FLOAT| (1. 2.)
        ((1. |FORTRAN-TO-LISP|::|P|) (1. 2.)))
       |FORTRAN-TO-LISP|::|IPIV| |FORTRAN-TO-LISP|::|IPIV1|
       |FORTRAN-TO-LISP|::|IPIV2| |FORTRAN-TO-LISP|::|KB|
       |FORTRAN-TO-LISP|::|L| |FORTRAN-TO-LISP|::|LV| |FORTRAN-TO-LISP|::|NS|
       |FORTRAN-TO-LISP|::|P| |FORTRAN-TO-LISP|::|P1|
       |FORTRAN-TO-LISP|::|STEP$| |FORTRAN-TO-LISP|::|TD|
       |FORTRAN-TO-LISP|::|TG| |FORTRAN-TO-LISP|::|V| |FORTRAN-TO-LISP|::|W|
       |FORTRAN-TO-LISP|::|X| |FORTRAN-TO-LISP|::|X0|)
      (|COMMON-LISP|::|DECLARE|
       (|COMMON-LISP|::|IGNORE| |FORTRAN-TO-LISP|::|VAR-0|
        |FORTRAN-TO-LISP|::|VAR-1| |FORTRAN-TO-LISP|::|VAR-2|
        |FORTRAN-TO-LISP|::|VAR-3| |FORTRAN-TO-LISP|::|VAR-4|
        |FORTRAN-TO-LISP|::|VAR-5| |FORTRAN-TO-LISP|::|VAR-7|
        |FORTRAN-TO-LISP|::|VAR-8| |FORTRAN-TO-LISP|::|VAR-10|
        |FORTRAN-TO-LISP|::|VAR-12| |FORTRAN-TO-LISP|::|VAR-13|
        |FORTRAN-TO-LISP|::|VAR-14| |FORTRAN-TO-LISP|::|VAR-15|
        |FORTRAN-TO-LISP|::|VAR-16| |FORTRAN-TO-LISP|::|VAR-17|
        |FORTRAN-TO-LISP|::|VAR-18|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KB|
       |FORTRAN-TO-LISP|::|VAR-6|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|NS|
       |FORTRAN-TO-LISP|::|VAR-9|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|P1|
       |FORTRAN-TO-LISP|::|VAR-11|))
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|NS| 0.)
      (|FORTRAN-TO-LISP|::|DS7IPR| |FORTRAN-TO-LISP|::|P10|
       |FORTRAN-TO-LISP|::|IPIV1| |FORTRAN-TO-LISP|::|DIHDI|))
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PRED|
      (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|PRED|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
        (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
        |FORTRAN-TO-LISP|::|V-%OFFSET%|)))
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|/=| |FORTRAN-TO-LISP|::|NS| 0.)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|P0| 0.))
     (|COMMON-LISP|::|IF| (|COMMON-LISP|::|<=| |FORTRAN-TO-LISP|::|KB| 0.)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL40|))
     |FORTRAN-TO-LISP|::|LABEL60|
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|DST0|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|DS0|)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|NREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|NRED|)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|PREDUC|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      |FORTRAN-TO-LISP|::|PRED|)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|GTSTEP|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|P|
       |FORTRAN-TO-LISP|::|G| |FORTRAN-TO-LISP|::|STEP$|))
     |FORTRAN-TO-LISP|::|LABEL999|
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|END_LABEL|)
     |FORTRAN-TO-LISP|::|END_LABEL|
     (|COMMON-LISP|::|RETURN|
      (|COMMON-LISP|::|VALUES| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
       |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
       |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |FORTRAN-TO-LISP|::|KA|
       |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
       |FORTRAN-TO-LISP|::|P0| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
       |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
       |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|)))))))

