;;; Compiled by f2cl version 2.0 beta Date: 2006/05/05 20:28:21 
;;; Using Lisp CLISP 2.38 (2006-01-24) (built on guru.build.karan.org)
;;; Options: ((:prune-labels nil) (:auto-save t) (:relaxed-array-decls t)
;;;  (:coerce-assigns :as-needed) (:array-type ':array) (:array-slicing t)
;;;  (:declare-common nil) (:float-format single-float))

(in-package :common-lisp-user)


(|COMMON-LISP|::|DEFUN| |FORTRAN-TO-LISP|::|DQ7RSH|
 (|FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|P| |FORTRAN-TO-LISP|::|HAVQTR|
  |FORTRAN-TO-LISP|::|QTR| |FORTRAN-TO-LISP|::|R| |FORTRAN-TO-LISP|::|W|)
 (|COMMON-LISP|::|DECLARE|
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|P|
   |FORTRAN-TO-LISP|::|K|)
  (|COMMON-LISP|::|TYPE| |F2CL-LIB|::|LOGICAL| |FORTRAN-TO-LISP|::|HAVQTR|)
  (|COMMON-LISP|::|TYPE|
   (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT| (|COMMON-LISP|::|*|))
   |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|QTR|)
  (|COMMON-LISP|::|TYPE|
   (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT| (|COMMON-LISP|::|*|))
   |FORTRAN-TO-LISP|::|R|))
 (|COMMON-LISP|::|LET| ((|FORTRAN-TO-LISP|::|ZERO| #1=0.0d0))
  (|COMMON-LISP|::|DECLARE|
   (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
    |FORTRAN-TO-LISP|::|ZERO|))
 
;(incf *dq7rsh*)

  (|F2CL-LIB|::|WITH-MULTI-ARRAY-DATA|
   ((|FORTRAN-TO-LISP|::|R| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|R-%DATA%| |FORTRAN-TO-LISP|::|R-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|QTR| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|QTR-%DATA%| |FORTRAN-TO-LISP|::|QTR-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|W| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|W-%DATA%| |FORTRAN-TO-LISP|::|W-%OFFSET%|))
   (|COMMON-LISP|::|PROG|
    ((|FORTRAN-TO-LISP|::|A| #1#) (|FORTRAN-TO-LISP|::|B| #1#)
     (|FORTRAN-TO-LISP|::|T$| #1#) (|FORTRAN-TO-LISP|::|WJ| #1#)
     (|FORTRAN-TO-LISP|::|X| #1#) (|FORTRAN-TO-LISP|::|Y| #1#)
     (|FORTRAN-TO-LISP|::|Z| #1#) (|FORTRAN-TO-LISP|::|I| 0.)
     (|FORTRAN-TO-LISP|::|I1| 0.) (|FORTRAN-TO-LISP|::|J| 0.)
     (|FORTRAN-TO-LISP|::|JM1| 0.) (|FORTRAN-TO-LISP|::|JP1| 0.)
     (|FORTRAN-TO-LISP|::|J1| 0.) (|FORTRAN-TO-LISP|::|KM1| 0.)
     (|FORTRAN-TO-LISP|::|K1| 0.) (|FORTRAN-TO-LISP|::|PM1| 0.))
    (|COMMON-LISP|::|DECLARE|
     (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
      |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|Y| |FORTRAN-TO-LISP|::|X|
      |FORTRAN-TO-LISP|::|WJ| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|B|
      |FORTRAN-TO-LISP|::|A|)
     (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|PM1|
      |FORTRAN-TO-LISP|::|K1| |FORTRAN-TO-LISP|::|KM1| |FORTRAN-TO-LISP|::|J1|
      |FORTRAN-TO-LISP|::|JP1| |FORTRAN-TO-LISP|::|JM1| |FORTRAN-TO-LISP|::|J|
      |FORTRAN-TO-LISP|::|I1| |FORTRAN-TO-LISP|::|I|))
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|P|)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|KM1|
     (|F2CL-LIB|::|INT-SUB| |FORTRAN-TO-LISP|::|K| 1.))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K1|
     (|COMMON-LISP|::|THE| |F2CL-LIB|::|INTEGER4|
      (|COMMON-LISP|::|TRUNCATE|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|KM1|)
       2.)))
    (|FORTRAN-TO-LISP|::|DV7CPY| |FORTRAN-TO-LISP|::|K| |FORTRAN-TO-LISP|::|W|
     (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|R|
      |COMMON-LISP|::|DOUBLE-FLOAT|
      ((|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|K1| 1.)) ((1. 1.))))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|WJ|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%| (|FORTRAN-TO-LISP|::|K|)
      ((1. |FORTRAN-TO-LISP|::|P|)) |FORTRAN-TO-LISP|::|W-%OFFSET%|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|PM1|
     (|F2CL-LIB|::|INT-SUB| |FORTRAN-TO-LISP|::|P| 1.))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J1|
     (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K1| |FORTRAN-TO-LISP|::|KM1|))
    (|F2CL-LIB|::|FDO|
     (|FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|K|
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J| 1.))
     ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|PM1|)
      |COMMON-LISP|::|NIL|)
     (|COMMON-LISP|::|TAGBODY|
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|JM1|
       (|F2CL-LIB|::|INT-SUB| |FORTRAN-TO-LISP|::|J| 1.))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|JP1|
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J| 1.))
      (|COMMON-LISP|::|IF| (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|JM1| 0.)
       (|FORTRAN-TO-LISP|::|DV7CPY| |FORTRAN-TO-LISP|::|JM1|
        (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|R|
         |COMMON-LISP|::|DOUBLE-FLOAT|
         ((|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|K1| 1.)) ((1. 1.)))
        (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|R|
         |COMMON-LISP|::|DOUBLE-FLOAT|
         ((|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|J1| 2.)) ((1. 1.)))))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|J1|
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J1|
        |FORTRAN-TO-LISP|::|JP1|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K1|
       (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K1| |FORTRAN-TO-LISP|::|J|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|A|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|R-%DATA%|
        (|FORTRAN-TO-LISP|::|J1|) ((1. 1.)) |FORTRAN-TO-LISP|::|R-%OFFSET%|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|B|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|R-%DATA%|
        ((|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J1| 1.)) ((1. 1.))
        |FORTRAN-TO-LISP|::|R-%OFFSET%|))
      (|COMMON-LISP|::|IF|
       (|COMMON-LISP|::|/=| |FORTRAN-TO-LISP|::|B| |FORTRAN-TO-LISP|::|ZERO|)
       (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL10|))
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|R-%DATA%|
        (|FORTRAN-TO-LISP|::|K1|) ((1. 1.)) |FORTRAN-TO-LISP|::|R-%OFFSET%|)
       |FORTRAN-TO-LISP|::|A|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|X| |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|Z| |FORTRAN-TO-LISP|::|ZERO|)
      (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL40|)
      |FORTRAN-TO-LISP|::|LABEL10|
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|R-%DATA%|
        (|FORTRAN-TO-LISP|::|K1|) ((1. 1.)) |FORTRAN-TO-LISP|::|R-%OFFSET%|)
       (|COMMON-LISP|::|MULTIPLE-VALUE-BIND|
        (|FORTRAN-TO-LISP|::|RET-VAL| |FORTRAN-TO-LISP|::|VAR-0|
         |FORTRAN-TO-LISP|::|VAR-1| |FORTRAN-TO-LISP|::|VAR-2|
         |FORTRAN-TO-LISP|::|VAR-3| |FORTRAN-TO-LISP|::|VAR-4|)
        (|FORTRAN-TO-LISP|::|DH2RFG| |FORTRAN-TO-LISP|::|A|
         |FORTRAN-TO-LISP|::|B| |FORTRAN-TO-LISP|::|X| |FORTRAN-TO-LISP|::|Y|
         |FORTRAN-TO-LISP|::|Z|)
        (|COMMON-LISP|::|DECLARE|
         (|COMMON-LISP|::|IGNORE| |FORTRAN-TO-LISP|::|VAR-0|
          |FORTRAN-TO-LISP|::|VAR-1|))
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|X|
         |FORTRAN-TO-LISP|::|VAR-2|)
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|Y|
         |FORTRAN-TO-LISP|::|VAR-3|)
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|Z|
         |FORTRAN-TO-LISP|::|VAR-4|)
        |FORTRAN-TO-LISP|::|RET-VAL|))
      (|COMMON-LISP|::|IF|
       (|COMMON-LISP|::|=| |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|PM1|)
       (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL30|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|I1| |FORTRAN-TO-LISP|::|J1|)
      (|F2CL-LIB|::|FDO|
       (|FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|JP1|
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
       ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|PM1|)
        |COMMON-LISP|::|NIL|)
       (|COMMON-LISP|::|TAGBODY|
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|I1|
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I1|
          |FORTRAN-TO-LISP|::|I|))
        (|FORTRAN-TO-LISP|::|DH2RFA| 1.
         (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|R|
          |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|I1|) ((1. 1.)))
         (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|R|
          |COMMON-LISP|::|DOUBLE-FLOAT|
          ((|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|I1| 1.)) ((1. 1.)))
         |FORTRAN-TO-LISP|::|X| |FORTRAN-TO-LISP|::|Y| |FORTRAN-TO-LISP|::|Z|)
        |FORTRAN-TO-LISP|::|LABEL20|))
      |FORTRAN-TO-LISP|::|LABEL30|
      (|COMMON-LISP|::|IF| |FORTRAN-TO-LISP|::|HAVQTR|
       (|FORTRAN-TO-LISP|::|DH2RFA| 1.
        (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|QTR|
         |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|J|)
         ((1. |FORTRAN-TO-LISP|::|P|)))
        (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|QTR|
         |COMMON-LISP|::|DOUBLE-FLOAT| (|FORTRAN-TO-LISP|::|JP1|)
         ((1. |FORTRAN-TO-LISP|::|P|)))
        |FORTRAN-TO-LISP|::|X| |FORTRAN-TO-LISP|::|Y| |FORTRAN-TO-LISP|::|Z|))
      |FORTRAN-TO-LISP|::|LABEL40|
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|X| |FORTRAN-TO-LISP|::|WJ|))
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
        (|FORTRAN-TO-LISP|::|J|) ((1. |FORTRAN-TO-LISP|::|P|))
        |FORTRAN-TO-LISP|::|W-%OFFSET%|)
       (|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|WJ| |FORTRAN-TO-LISP|::|T$|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|WJ|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|Z|))
      |FORTRAN-TO-LISP|::|LABEL50|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%| (|FORTRAN-TO-LISP|::|P|)
      ((1. |FORTRAN-TO-LISP|::|P|)) |FORTRAN-TO-LISP|::|W-%OFFSET%|)
     |FORTRAN-TO-LISP|::|WJ|)
    (|FORTRAN-TO-LISP|::|DV7CPY| |FORTRAN-TO-LISP|::|P|
     (|F2CL-LIB|::|ARRAY-SLICE| |FORTRAN-TO-LISP|::|R|
      |COMMON-LISP|::|DOUBLE-FLOAT|
      ((|COMMON-LISP|::|+| |FORTRAN-TO-LISP|::|K1| 1.)) ((1. 1.)))
     |FORTRAN-TO-LISP|::|W|)
    |FORTRAN-TO-LISP|::|LABEL999|
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|END_LABEL|)
    |FORTRAN-TO-LISP|::|END_LABEL|
    (|COMMON-LISP|::|RETURN|
     (|COMMON-LISP|::|VALUES| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL|))))))

