;;; Compiled by f2cl version 2.0 beta Date: 2006/05/05 20:28:21 
;;; Using Lisp CLISP 2.38 (2006-01-24) (built on guru.build.karan.org)
;;; Options: ((:prune-labels nil) (:auto-save t) (:relaxed-array-decls t)
;;;  (:coerce-assigns :as-needed) (:array-type ':array) (:array-slicing t)
;;;  (:declare-common nil) (:float-format single-float))

(in-package :common-lisp-user)


(|COMMON-LISP|::|DEFUN| |FORTRAN-TO-LISP|::|DS7LUP|
 (|FORTRAN-TO-LISP|::|A| |FORTRAN-TO-LISP|::|COSMIN| |FORTRAN-TO-LISP|::|P|
  |FORTRAN-TO-LISP|::|SIZE| |FORTRAN-TO-LISP|::|STEP$| |FORTRAN-TO-LISP|::|U|
  |FORTRAN-TO-LISP|::|W| |FORTRAN-TO-LISP|::|WCHMTD|
  |FORTRAN-TO-LISP|::|WSCALE| |FORTRAN-TO-LISP|::|Y|)
 (|COMMON-LISP|::|DECLARE|
  (|COMMON-LISP|::|TYPE|
   (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT| (|COMMON-LISP|::|*|))
   |FORTRAN-TO-LISP|::|A|)
  (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
   |FORTRAN-TO-LISP|::|WSCALE| |FORTRAN-TO-LISP|::|SIZE|
   |FORTRAN-TO-LISP|::|COSMIN|)
  (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|P|)
  (|COMMON-LISP|::|TYPE|
   (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT| (|COMMON-LISP|::|*|))
   |FORTRAN-TO-LISP|::|Y| |FORTRAN-TO-LISP|::|WCHMTD| |FORTRAN-TO-LISP|::|W|
   |FORTRAN-TO-LISP|::|U| |FORTRAN-TO-LISP|::|STEP$|))
 (|COMMON-LISP|::|LET*|
  ((|FORTRAN-TO-LISP|::|HALF| #1=0.5d0) (|FORTRAN-TO-LISP|::|ONE| #2=1.0d0)
   (|FORTRAN-TO-LISP|::|ZERO| #3=0.0d0))
  (|COMMON-LISP|::|DECLARE|
   (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #1# #1#) |FORTRAN-TO-LISP|::|HALF|)
   (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #2# #2#) |FORTRAN-TO-LISP|::|ONE|)
   (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #3# #3#) |FORTRAN-TO-LISP|::|ZERO|))
;(incf *ds7lup*)

  (|F2CL-LIB|::|WITH-MULTI-ARRAY-DATA|
   ((|FORTRAN-TO-LISP|::|STEP$| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|STEP$-%DATA%| |FORTRAN-TO-LISP|::|STEP$-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|U| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|U-%DATA%| |FORTRAN-TO-LISP|::|U-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|W| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|W-%DATA%| |FORTRAN-TO-LISP|::|W-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|WCHMTD| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|WCHMTD-%DATA%| |FORTRAN-TO-LISP|::|WCHMTD-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|Y| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|Y-%DATA%| |FORTRAN-TO-LISP|::|Y-%OFFSET%|)
    (|FORTRAN-TO-LISP|::|A| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|A-%DATA%| |FORTRAN-TO-LISP|::|A-%OFFSET%|))
   (|COMMON-LISP|::|PROG|
    ((|FORTRAN-TO-LISP|::|DENMIN| #3#) (|FORTRAN-TO-LISP|::|SDOTWM| #3#)
     (|FORTRAN-TO-LISP|::|UI| #3#) (|FORTRAN-TO-LISP|::|WI| #3#)
     (|FORTRAN-TO-LISP|::|I| 0.) (|FORTRAN-TO-LISP|::|J| 0.)
     (|FORTRAN-TO-LISP|::|K| 0.) (|FORTRAN-TO-LISP|::|T$| #3#))
    (|COMMON-LISP|::|DECLARE|
     (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
      |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|WI| |FORTRAN-TO-LISP|::|UI|
      |FORTRAN-TO-LISP|::|SDOTWM| |FORTRAN-TO-LISP|::|DENMIN|)
     (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|K|
      |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|I|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|SDOTWM|
     (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|P|
      |FORTRAN-TO-LISP|::|STEP$| |FORTRAN-TO-LISP|::|WCHMTD|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|DENMIN|
     (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|COSMIN|
      (|FORTRAN-TO-LISP|::|DV2NRM| |FORTRAN-TO-LISP|::|P|
       |FORTRAN-TO-LISP|::|STEP$|)
      (|FORTRAN-TO-LISP|::|DV2NRM| |FORTRAN-TO-LISP|::|P|
       |FORTRAN-TO-LISP|::|WCHMTD|)))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|WSCALE|
     |FORTRAN-TO-LISP|::|ONE|)
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|/=| |FORTRAN-TO-LISP|::|DENMIN|
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|WSCALE|
      (|COMMON-LISP|::|MIN| |FORTRAN-TO-LISP|::|ONE|
       (|COMMON-LISP|::|ABS|
        (|COMMON-LISP|::|/| |FORTRAN-TO-LISP|::|SDOTWM|
         |FORTRAN-TO-LISP|::|DENMIN|)))))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$| |FORTRAN-TO-LISP|::|ZERO|)
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|/=| |FORTRAN-TO-LISP|::|SDOTWM|
      |FORTRAN-TO-LISP|::|ZERO|)
     (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
      (|COMMON-LISP|::|/| |FORTRAN-TO-LISP|::|WSCALE|
       |FORTRAN-TO-LISP|::|SDOTWM|)))
    (|F2CL-LIB|::|FDO|
     (|FORTRAN-TO-LISP|::|I| 1.
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
     ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
      |COMMON-LISP|::|NIL|)
     (|COMMON-LISP|::|TAGBODY| |FORTRAN-TO-LISP|::|LABEL10|
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
        (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|P|))
        |FORTRAN-TO-LISP|::|W-%OFFSET%|)
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T$|
        (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|WCHMTD-%DATA%|
         (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|P|))
         |FORTRAN-TO-LISP|::|WCHMTD-%OFFSET%|)))))
    (|FORTRAN-TO-LISP|::|DS7LVM| |FORTRAN-TO-LISP|::|P| |FORTRAN-TO-LISP|::|U|
     |FORTRAN-TO-LISP|::|A| |FORTRAN-TO-LISP|::|STEP$|)
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|T$|
     (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|HALF|
      (|COMMON-LISP|::|-|
       (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|SIZE|
        (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|P|
         |FORTRAN-TO-LISP|::|STEP$| |FORTRAN-TO-LISP|::|U|))
       (|FORTRAN-TO-LISP|::|DD7TPR| |FORTRAN-TO-LISP|::|P|
        |FORTRAN-TO-LISP|::|STEP$| |FORTRAN-TO-LISP|::|Y|))))
    (|F2CL-LIB|::|FDO|
     (|FORTRAN-TO-LISP|::|I| 1.
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
     ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
      |COMMON-LISP|::|NIL|)
     (|COMMON-LISP|::|TAGBODY| |FORTRAN-TO-LISP|::|LABEL20|
      (|COMMON-LISP|::|SETF|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|U-%DATA%|
        (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|P|))
        |FORTRAN-TO-LISP|::|U-%OFFSET%|)
       (|COMMON-LISP|::|-|
        (|COMMON-LISP|::|+|
         (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|T$|
          (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
           (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|P|))
           |FORTRAN-TO-LISP|::|W-%OFFSET%|))
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|Y-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|P|))
          |FORTRAN-TO-LISP|::|Y-%OFFSET%|))
        (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|SIZE|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|U-%DATA%|
          (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|P|))
          |FORTRAN-TO-LISP|::|U-%OFFSET%|))))))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K| 1.)
    (|F2CL-LIB|::|FDO|
     (|FORTRAN-TO-LISP|::|I| 1.
      (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|I| 1.))
     ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|I| |FORTRAN-TO-LISP|::|P|)
      |COMMON-LISP|::|NIL|)
     (|COMMON-LISP|::|TAGBODY|
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|UI|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|U-%DATA%|
        (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|P|))
        |FORTRAN-TO-LISP|::|U-%OFFSET%|))
      (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|WI|
       (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
        (|FORTRAN-TO-LISP|::|I|) ((1. |FORTRAN-TO-LISP|::|P|))
        |FORTRAN-TO-LISP|::|W-%OFFSET%|))
      (|F2CL-LIB|::|FDO|
       (|FORTRAN-TO-LISP|::|J| 1.
        (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|J| 1.))
       ((|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|J| |FORTRAN-TO-LISP|::|I|)
        |COMMON-LISP|::|NIL|)
       (|COMMON-LISP|::|TAGBODY|
        (|COMMON-LISP|::|SETF|
         (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|A-%DATA%|
          (|FORTRAN-TO-LISP|::|K|) ((1. 1.)) |FORTRAN-TO-LISP|::|A-%OFFSET%|)
         (|COMMON-LISP|::|+|
          (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|SIZE|
           (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|A-%DATA%|
            (|FORTRAN-TO-LISP|::|K|) ((1. 1.))
            |FORTRAN-TO-LISP|::|A-%OFFSET%|))
          (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|UI|
           (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|W-%DATA%|
            (|FORTRAN-TO-LISP|::|J|) ((1. |FORTRAN-TO-LISP|::|P|))
            |FORTRAN-TO-LISP|::|W-%OFFSET%|))
          (|COMMON-LISP|::|*| |FORTRAN-TO-LISP|::|WI|
           (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|U-%DATA%|
            (|FORTRAN-TO-LISP|::|J|) ((1. |FORTRAN-TO-LISP|::|P|))
            |FORTRAN-TO-LISP|::|U-%OFFSET%|))))
        (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|K|
         (|F2CL-LIB|::|INT-ADD| |FORTRAN-TO-LISP|::|K| 1.))
        |FORTRAN-TO-LISP|::|LABEL30|))
      |FORTRAN-TO-LISP|::|LABEL40|))
    |FORTRAN-TO-LISP|::|LABEL999|
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|END_LABEL|)
    |FORTRAN-TO-LISP|::|END_LABEL|
    (|COMMON-LISP|::|RETURN|
     (|COMMON-LISP|::|VALUES| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |FORTRAN-TO-LISP|::|WSCALE| |COMMON-LISP|::|NIL|))))))

