;;; Compiled by f2cl version 2.0 beta Date: 2006/05/05 20:28:21 
;;; Using Lisp CLISP 2.38 (2006-01-24) (built on guru.build.karan.org)
;;; Options: ((:prune-labels nil) (:auto-save t) (:relaxed-array-decls t)
;;;  (:coerce-assigns :as-needed) (:array-type ':array) (:array-slicing t)
;;;  (:declare-common nil) (:float-format single-float))

(in-package :common-lisp-user)

 (|COMMON-LISP|::|DEFUN| |FORTRAN-TO-LISP|::|DV7DFL|
  (|FORTRAN-TO-LISP|::|ALG| |FORTRAN-TO-LISP|::|LV| |FORTRAN-TO-LISP|::|V|)
  (|COMMON-LISP|::|DECLARE|
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4|) |FORTRAN-TO-LISP|::|LV|
    |FORTRAN-TO-LISP|::|ALG|)
   (|COMMON-LISP|::|TYPE|
    (|COMMON-LISP|::|ARRAY| |COMMON-LISP|::|DOUBLE-FLOAT| (|COMMON-LISP|::|*|))
    |FORTRAN-TO-LISP|::|V|)
   (|COMMON-LISP|::|IGNORE| |FORTRAN-TO-LISP|::|LV|))

  (|COMMON-LISP|::|LET*|
   ((|FORTRAN-TO-LISP|::|ONE| #1=1.0d0) (|FORTRAN-TO-LISP|::|THREE| #2=3.0d0)
    (|FORTRAN-TO-LISP|::|AFCTOL| 31.) (|FORTRAN-TO-LISP|::|BIAS| 43.)
    (|FORTRAN-TO-LISP|::|COSMIN| 47.) (|FORTRAN-TO-LISP|::|DECFAC| 22.)
    (|FORTRAN-TO-LISP|::|DELTA0| 44.) (|FORTRAN-TO-LISP|::|DFAC| 41.)
    (|FORTRAN-TO-LISP|::|DINIT| 38.) (|FORTRAN-TO-LISP|::|DLTFDC| 42.)
    (|FORTRAN-TO-LISP|::|DLTFDJ| 43.) (|FORTRAN-TO-LISP|::|DTINIT| 39.)
    (|FORTRAN-TO-LISP|::|D0INIT| 40.) (|FORTRAN-TO-LISP|::|EPSLON| 19.)
    (|FORTRAN-TO-LISP|::|ETA0| 42.) (|FORTRAN-TO-LISP|::|FUZZ| 45.)
    (|FORTRAN-TO-LISP|::|HUBERC| 48.) (|FORTRAN-TO-LISP|::|INCFAC| 23.)
    (|FORTRAN-TO-LISP|::|LMAX0| 35.) (|FORTRAN-TO-LISP|::|LMAXS| 36.)
    (|FORTRAN-TO-LISP|::|PHMNFC| 20.) (|FORTRAN-TO-LISP|::|PHMXFC| 21.)
    (|FORTRAN-TO-LISP|::|RDFCMN| 24.) (|FORTRAN-TO-LISP|::|RDFCMX| 25.)
    (|FORTRAN-TO-LISP|::|RFCTOL| 32.) (|FORTRAN-TO-LISP|::|RLIMIT| 46.)
    (|FORTRAN-TO-LISP|::|RSPTOL| 49.) (|FORTRAN-TO-LISP|::|SCTOL| 37.)
    (|FORTRAN-TO-LISP|::|SIGMIN| 50.) (|FORTRAN-TO-LISP|::|TUNER1| 26.)
    (|FORTRAN-TO-LISP|::|TUNER2| 27.) (|FORTRAN-TO-LISP|::|TUNER3| 28.)
    (|FORTRAN-TO-LISP|::|TUNER4| 29.) (|FORTRAN-TO-LISP|::|TUNER5| 30.)
    (|FORTRAN-TO-LISP|::|XCTOL| 33.) (|FORTRAN-TO-LISP|::|XFTOL| 34.))
  (|COMMON-LISP|::|DECLARE|
   (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #1# #1#) |FORTRAN-TO-LISP|::|ONE|)
   (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT| #2# #2#) |FORTRAN-TO-LISP|::|THREE|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 31. 31.) |FORTRAN-TO-LISP|::|AFCTOL|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 43. 43.) |FORTRAN-TO-LISP|::|BIAS|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 47. 47.) |FORTRAN-TO-LISP|::|COSMIN|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 22. 22.) |FORTRAN-TO-LISP|::|DECFAC|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 44. 44.) |FORTRAN-TO-LISP|::|DELTA0|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 41. 41.) |FORTRAN-TO-LISP|::|DFAC|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 38. 38.) |FORTRAN-TO-LISP|::|DINIT|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 42. 42.) |FORTRAN-TO-LISP|::|DLTFDC|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 43. 43.) |FORTRAN-TO-LISP|::|DLTFDJ|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 39. 39.) |FORTRAN-TO-LISP|::|DTINIT|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 40. 40.) |FORTRAN-TO-LISP|::|D0INIT|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 19. 19.) |FORTRAN-TO-LISP|::|EPSLON|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 42. 42.) |FORTRAN-TO-LISP|::|ETA0|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 45. 45.) |FORTRAN-TO-LISP|::|FUZZ|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 48. 48.) |FORTRAN-TO-LISP|::|HUBERC|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 23. 23.) |FORTRAN-TO-LISP|::|INCFAC|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 35. 35.) |FORTRAN-TO-LISP|::|LMAX0|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 36. 36.) |FORTRAN-TO-LISP|::|LMAXS|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 20. 20.) |FORTRAN-TO-LISP|::|PHMNFC|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 21. 21.) |FORTRAN-TO-LISP|::|PHMXFC|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 24. 24.) |FORTRAN-TO-LISP|::|RDFCMN|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 25. 25.) |FORTRAN-TO-LISP|::|RDFCMX|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 32. 32.) |FORTRAN-TO-LISP|::|RFCTOL|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 46. 46.) |FORTRAN-TO-LISP|::|RLIMIT|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 49. 49.) |FORTRAN-TO-LISP|::|RSPTOL|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 37. 37.) |FORTRAN-TO-LISP|::|SCTOL|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 50. 50.) |FORTRAN-TO-LISP|::|SIGMIN|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 26. 26.) |FORTRAN-TO-LISP|::|TUNER1|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 27. 27.) |FORTRAN-TO-LISP|::|TUNER2|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 28. 28.) |FORTRAN-TO-LISP|::|TUNER3|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 29. 29.) |FORTRAN-TO-LISP|::|TUNER4|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 30. 30.) |FORTRAN-TO-LISP|::|TUNER5|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 33. 33.) |FORTRAN-TO-LISP|::|XCTOL|)
   (|COMMON-LISP|::|TYPE| (|F2CL-LIB|::|INTEGER4| 34. 34.) |FORTRAN-TO-LISP|::|XFTOL|))
;  (incf *dv7dfl*) 
  (|F2CL-LIB|::|WITH-MULTI-ARRAY-DATA|
   ((|FORTRAN-TO-LISP|::|V| |COMMON-LISP|::|DOUBLE-FLOAT|
     |FORTRAN-TO-LISP|::|V-%DATA%| |FORTRAN-TO-LISP|::|V-%OFFSET%|))
   (|COMMON-LISP|::|PROG|
    ((|FORTRAN-TO-LISP|::|MACHEP| #3=0.0d0) (|FORTRAN-TO-LISP|::|MEPCRT| #3#)
     (|FORTRAN-TO-LISP|::|SQTEPS| #3#))
    (|COMMON-LISP|::|DECLARE|
     (|COMMON-LISP|::|TYPE| (|COMMON-LISP|::|DOUBLE-FLOAT|)
      |FORTRAN-TO-LISP|::|SQTEPS| |FORTRAN-TO-LISP|::|MEPCRT|
      |FORTRAN-TO-LISP|::|MACHEP|))
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|MACHEP|
     (|FORTRAN-TO-LISP|::|DR7MDC| 3.))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|AFCTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     1.0d-20)
    (|COMMON-LISP|::|IF|
     (|COMMON-LISP|::|>| |FORTRAN-TO-LISP|::|MACHEP| 1.0d-10)
     (|COMMON-LISP|::|SETF|
      (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
       (|FORTRAN-TO-LISP|::|AFCTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
       |FORTRAN-TO-LISP|::|V-%OFFSET%|)
      (|COMMON-LISP|::|EXPT| |FORTRAN-TO-LISP|::|MACHEP| 2.)))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DECFAC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     0.5d0)
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|SQTEPS|
     (|FORTRAN-TO-LISP|::|DR7MDC| 4.))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DFAC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     0.6d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DTINIT|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     1.0d-6)
    (|COMMON-LISP|::|SETF| |FORTRAN-TO-LISP|::|MEPCRT|
     (|COMMON-LISP|::|EXPT| |FORTRAN-TO-LISP|::|MACHEP|
      (|COMMON-LISP|::|/| |FORTRAN-TO-LISP|::|ONE|
       |FORTRAN-TO-LISP|::|THREE|)))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|D0INIT|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     1.0d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|EPSLON|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     0.1d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|INCFAC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     2.0d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|LMAX0|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     1.0d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|LMAXS|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     1.0d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|PHMNFC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     -0.1d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|PHMXFC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     0.1d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|RDFCMN|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     0.1d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|RDFCMX|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     4.0d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|RFCTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|COMMON-LISP|::|MAX| 1.0d-10
      (|COMMON-LISP|::|EXPT| |FORTRAN-TO-LISP|::|MEPCRT| 2.)))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|SCTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|RFCTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|TUNER1|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     0.1d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|TUNER2|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     1.0d-4)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|TUNER3|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     0.75d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|TUNER4|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     0.5d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|TUNER5|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     0.75d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|XCTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     |FORTRAN-TO-LISP|::|SQTEPS|)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|XFTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|COMMON-LISP|::|*| 100.0d0 |FORTRAN-TO-LISP|::|MACHEP|))
    (|COMMON-LISP|::|IF| (|COMMON-LISP|::|>=| |FORTRAN-TO-LISP|::|ALG| 2.)
     (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL10|))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|COSMIN|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|COMMON-LISP|::|MAX| 1.0d-6
      (|COMMON-LISP|::|*| 100.0d0 |FORTRAN-TO-LISP|::|MACHEP|)))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DINIT|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     #3#)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DELTA0|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     |FORTRAN-TO-LISP|::|SQTEPS|)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DLTFDC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     |FORTRAN-TO-LISP|::|MEPCRT|)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DLTFDJ|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     |FORTRAN-TO-LISP|::|SQTEPS|)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|FUZZ|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     1.5d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|HUBERC|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     0.7d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|RLIMIT|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|FORTRAN-TO-LISP|::|DR7MDC| 5.))
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|RSPTOL|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     0.001d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|SIGMIN|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     1.0d-4)
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|LABEL999|)
    |FORTRAN-TO-LISP|::|LABEL10|
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|BIAS|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     0.8d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|DINIT|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     -1.0d0)
    (|COMMON-LISP|::|SETF|
     (|F2CL-LIB|::|FREF| |FORTRAN-TO-LISP|::|V-%DATA%|
      (|FORTRAN-TO-LISP|::|ETA0|) ((1. |FORTRAN-TO-LISP|::|LV|))
      |FORTRAN-TO-LISP|::|V-%OFFSET%|)
     (|COMMON-LISP|::|*| 1000.0d0 |FORTRAN-TO-LISP|::|MACHEP|))
    |FORTRAN-TO-LISP|::|LABEL999|
    (|COMMON-LISP|::|GO| |FORTRAN-TO-LISP|::|END_LABEL|)
    |FORTRAN-TO-LISP|::|END_LABEL|
    (|COMMON-LISP|::|RETURN|
     (|COMMON-LISP|::|VALUES| |COMMON-LISP|::|NIL| |COMMON-LISP|::|NIL|
      |COMMON-LISP|::|NIL|))))))

